
import { Question, Topic, TopicInfo } from './types';
import { Globe, BookOpen, Palette, Moon, Rocket, Clapperboard, Cpu, Dumbbell } from 'lucide-react';

export const TOPICS: TopicInfo[] = [
  { id: 'COGRAFIYA', label: 'Coğrafiya', icon: 'Globe', description: 'Dünya ölkələri, paytaxtlar və təbiət', color: 'blue' },
  { id: 'TARIX', label: 'Tarix', icon: 'BookOpen', description: 'Azərbaycan və Dünya tarixi, hadisələr', color: 'amber' },
  { id: 'INCESENET', label: 'İncəsənət', icon: 'Palette', description: 'Rəsm, Musiqi, Ədəbiyyat və Memarlıq', color: 'fuchsia' },
  { id: 'DIN', label: 'Din', icon: 'Moon', description: 'İslam tarixi, Peyğəmbərlər və inanclar', color: 'emerald' },
  { id: 'FANTASTIK', label: 'Fantastik', icon: 'Rocket', description: 'Elmi-fantastika, kosmos və gələcək', color: 'violet' },
  { id: 'FILM', label: 'Film', icon: 'Clapperboard', description: 'Kino, aktyorlar və məşhur sitatlar', color: 'rose' },
  { id: 'TEXNOLOGIYA', label: 'Texnologiya', icon: 'Cpu', description: 'Kompüterlər, İxtiralar və İT', color: 'cyan' },
  { id: 'IDMAN', label: 'İdman', icon: 'Dumbbell', description: 'Futbol, Olimpiada və İdman növləri', color: 'orange' },
];

// Helper to create questions
const createQ = (text: string, options: string[], correct: number): Omit<Question, 'id' | 'prize'> => ({
  text,
  options,
  correctAnswerIndex: correct,
});

// --- QUESTION DATABASE BY TOPIC ---
const DB: Record<string, { easy: any[], medium: any[], hard: any[] }> = {
  COGRAFIYA: {
    easy: [
      createQ("Azərbaycanın paytaxtı hansı şəhərdir?", ["Gəncə", "Bakı", "Sumqayıt", "Mingəçevir"], 1),
      createQ("Dünyanın ən böyük okeanı hansıdır?", ["Atlantik okeanı", "Hind okeanı", "Sakit okean", "Şimal Buzlu okeanı"], 2),
      createQ("Azərbaycanın ən uzun çayı hansıdır?", ["Kür", "Araz", "Qabırri", "Samur"], 0),
      createQ("Avropa qitəsinin ən hündür dağı hansıdır?", ["Montblan", "Elbrus", "Matterhorn", "Mont Blanc"], 1),
      createQ("Xəzər dənizi hansı qitələr arasında yerləşir?", ["Asiya və Afrika", "Avropa və Asiya", "Avropa və Afrika", "Asiya və Avstraliya"], 1),
      createQ("Azərbaycanın ən böyük gölü hansıdır?", ["Göygöl", "Sarısu", "Məhmədbağırlı", "Böyükşor"], 1),
      createQ("Rusiya hansı qitədədir?", ["Yalnız Asiyada", "Yalnız Avropada", "Avropa və Asiyada", "Amerika və Asiyada"], 2),
      createQ("Nil çayı hansı qitədədir?", ["Asiya", "Afrika", "Cənubi Amerika", "Avropa"], 1),
      createQ("Azərbaycanın ən hündür zirvəsi hansıdır?", ["Camışdağ", "Savalan", "Tufandağ", "Bazardüzü"], 3),
      createQ("Amazon çayı hansı qitədədir?", ["Afrika", "Asiya", "Cənubi Amerika", "Şimali Amerika"], 2),
      createQ("Türkiyənin paytaxtı hansı şəhərdir?", ["İstanbul", "Ankara", "İzmir", "Antalya"], 1),
      createQ("Azərbaycanda neçə inzibati rayon var?", ["59", "66", "78", "82"], 1),
      createQ("Yaponiyanın paytaxtı hansıdır?", ["Kioto", "Osaka", "Tokio", "Yokohama"], 2),
      createQ("Qafqaz dağları hansı dənizlər arasındadır?", ["Xəzər və Qara dəniz", "Xəzər və Aral", "Qara və Aralıq dənizi", "Baltik və Qara dəniz"], 0),
      createQ("Fransanın paytaxtı hansıdır?", ["Lion", "Marsel", "Paris", "Bordo"], 2),
      createQ("Azərbaycan neçə ölkə ilə sərhəddir?", ["3", "4", "5", "6"], 2),
      createQ("Dünyanın ən böyük səhrası hansıdır?", ["Qobi", "Kalahari", "Səhəra", "Araviya səhrası"], 2),
      createQ("İtaliyanın paytaxtı hansıdır?", ["Milan", "Roma", "Veneysiya", "Florensiya"], 1),
      createQ("Naxçıvan Muxtar Respublikası hansı ölkə ilə sərhəddir?", ["Rusiya", "Gürcüstan", "Türkiyə", "Qazaxıstan"], 2),
      createQ("Almanyanın paytaxtı hansıdır?", ["Münhen", "Frankfurt", "Hamburg", "Berlin"], 3),
      createQ("Azərbaycanın sahəsi təqribən neçə min kv.km-dir?", ["66,6", "76,6", "86,6", "96,6"], 2),
      createQ("İspaniyanın paytaxtı hansıdır?", ["Barselona", "Madrid", "Valensiya", "Sevilya"], 1),
      createQ("Abşeron yarımadası hansı dənizə uzanır?", ["Qara dəniz", "Aralıq dənizi", "Xəzər dənizi", "Aral gölü"], 2),
      createQ("Misirin paytaxtı hansıdır?", ["İsgəndəriyyə", "Qahirə", "Lüksor", "Asuan"], 1),
      createQ("Avstraliyanın paytaxtı hansıdır?", ["Sidney", "Melburn", "Kanberra", "Brisben"], 2),
      createQ("Gəncə şəhəri hansı çayın sahilindədir?", ["Kür", "Gəncəçay", "Xəzər", "Şəmkirçay"], 1),
      createQ("Braziliyanın paytaxtı hansıdır?", ["Rio-de-Janeyro", "San-Paulo", "Braziliya", "Buenosaires"], 2),
      createQ("Kanadanın paytaxtı hansıdır?", ["Toronto", "Vankuver", "Ottava", "Monreal"], 2),
      createQ("Azərbaycanın hansı şəhəri \"Qafqazın Şimalı\" adlanır?", ["Bakı", "Gəncə", "Şuşa", "Quba"], 2),
      createQ("Çinin paytaxtı hansıdır?", ["Şanxay", "Pekin", "Honq-Konq", "Çunqinq"], 1),
    ],
    medium: [
      createQ("Azərbaycanın ən şimal nöqtəsi hansı rayondadır?", ["Qusar", "Xaçmaz", "Quba", "Siyəzən"], 0),
      createQ("Böyük Qafqaz dağ silsiləsi hansı istiqamətdədir?", ["Şimal-cənub", "Şərq-qərb", "Şimal-qərb - cənub-şərq", "Şimal-şərq - cənub-qərb"], 2),
      createQ("Himalay dağları hansı ölkələrdə yerləşir?", ["Çin və Hindistan", "Nepal, Hindistan, Çin", "Pakistan və Hindistan", "Nepal və Çin"], 1),
      createQ("And dağları hansı qitədədir?", ["Şimali Amerika", "Cənubi Amerika", "Afrika", "Asiya"], 1),
      createQ("Azərbaycanın ən cənub nöqtəsi hansı rayondadır?", ["Astara", "Lənkəran", "Lerik", "Masallı"], 2),
      createQ("Dünyanın ən dərin gölu hansıdır?", ["Baykal", "Tanqanika", "Kaspi dənizi", "Nyasa"], 0),
      createQ("Skandinaviya yarımadası hansı ölkələri əhatə edir?", ["Norveç və İsveç", "Norveç, İsveç və Finlandiya", "Danimarka və Norveç", "İsveç və Finlandiya"], 0),
      createQ("Azərbaycanın hansı rayonu \"Respublikanın tərəvəz-bostan əkinləri paytaxtı\" adlanır?", ["Qax", "Sabirabad", "Beyləqan", "İmişli"], 1),
      createQ("Aralıq dənizi hansı okeanın hövzəsinə aiddir?", ["Sakit okean", "Atlantik okean", "Hind okeanı", "Şimal Buzlu okeanı"], 1),
      createQ("Savalan dağının hündürlüyü neçə metrdir?", ["3629", "4466", "4104", "3906"], 1),
      createQ("Panama kanalı hansı okeanları birləşdirir?", ["Atlantik və Hind", "Sakit və Hind", "Atlantik və Sakit", "Hind və Şimal Buzlu"], 2),
      createQ("Azərbaycanın ən böyük yarımadası hansıdır?", ["Abşeron", "Sara", "Giləzi", "Saray"], 0),
      createQ("Süveyş kanalı hansı dənizləri birləşdirir?", ["Qara və Aralıq dənizi", "Aralıq və Qırmızı dəniz", "Xəzər və Qara dəniz", "Qırmızı və Ərəb dənizi"], 1),
      createQ("Kiçik Qafqaz dağ silsiləsi əsasən Azərbaycanın hansı hissəsindədir?", ["Şimal", "Şərq", "Qərb və cənub-qərb", "Cənub-şərq"], 2),
      createQ("Dünyanın ən uzun çayı hansıdır?", ["Amazon", "Nil", "Mississipi", "Yanszı"], 1),
      createQ("Mingəçevir su anbarı hansı çay üzərində yerləşir?", ["Araz", "Kür", "Qanıx", "Tərtər"], 1),
      createQ("Cəlilabad rayonu hansı iqtisadi rayona aiddir?", ["Lənkəran", "Şirvan", "Qarabağ", "Mil-Muğan"], 0),
      createQ("Dünyanın ən böyük adası hansıdır?", ["Malagasi", "Qrenlandiya", "Yeni Qvineya", "Borneo"], 1),
      createQ("Talış dağları Azərbaycanın hansı hissəsindədir?", ["Şimal", "Qərb", "Cənub-şərq", "Şimal-qərb"], 2),
      createQ("Bosfor və Dardanel boğazları hansı dənizləri birləşdirir?", ["Qara və Aralıq dənizi", "Qara və Marmara dənizi", "Marmara və Aralıq dənizi", "Qara dəniz - Marmara - Aralıq dənizi"], 3),
      createQ("Azərbaycanın ən böyük adası hansıdır?", ["Çilov", "Gil", "Pirallahı", "Qum adası"], 2),
      createQ("Alplar dağ silsiləsi hansı ölkələrdən keçir?", ["Fransa, İsveçrə, İtaliya", "Fransa, İsveçrə, İtaliya, Avstriya", "Almaniya, İsveçrə, İtaliya", "İtaliya və Avstriya"], 1),
      createQ("Göygöl hansı rayondadır?", ["Gədəbəy", "Daşkəsən", "Göygöl", "Goranboy"], 2),
      createQ("Volqa çayı hansı dənizə tökülür?", ["Qara dəniz", "Xəzər dənizi", "Azov dənizi", "Baltik dənizi"], 1),
      createQ("Azərbaycanın ən quru regionu hansıdır?", ["Abşeron", "Şirvan", "Naxçıvan", "Quba-Xaçmaz"], 2),
      createQ("Dünyanın ən kiçik ölkəsi hansıdır?", ["Monako", "Vatikan", "San-Marino", "Lixtenşteyn"], 1),
      createQ("Mərdəkan qalası hansı şəhərdədir?", ["Bakı", "Sumqayıt", "Xırdalan", "Şamaxı"], 0),
      createQ("Amazonka çayı hansı okeana tökülür?", ["Sakit okean", "Atlantik okean", "Hind okeanı", "Şimal Buzlu okeanı"], 1),
      createQ("Naxçıvanın ən hündür zirvəsi hansıdır?", ["Qapıcıq", "İlandağ", "Dərəleyəz", "Əhəndağ"], 0),
      createQ("Türkiyənin ən böyük gölü hansıdır?", ["Tuz gölü", "Van gölü", "Beyşəhir", "Eğirdir"], 1),
    ],
    hard: [
      createQ("Azərbaycanın ən qərb nöqtəsi hansı rayondadır?", ["Qazax", "Ağstafa", "Tovuz", "Kəlbəcər"], 3),
      createQ("Bazardüzü zirvəsinin hündürlüyü neçə metrdir?", ["4446", "4466", "4656", "4736"], 2),
      createQ("Murovdağ dağ silsiləsi hansı dağ sisteminin tərkibindədir?", ["Böyük Qafqaz", "Kiçik Qafqaz", "Talış dağları", "Naxçıvan dağları"], 1),
      createQ("Azərbaycanın palçıq vulkanlarının sayı təqribən neçədir?", ["250", "350", "450", "550"], 1),
      createQ("Kür çayının uzunluğu neçə km-dir?", ["1264", "1364", "1464", "1564"], 2),
      createQ("Yanardag Abşeronun hansı hissəsindədir?", ["Şimal", "Cənub", "Qərb", "Şərq"], 0),
      createQ("Dünyanın ən hündür zirvəsi Jomolungma (Everest) neçə metr hündürlükdədir?", ["8748", "8848", "8948", "9048"], 1),
      createQ("Azərbaycanın Botanika İnstitutu hansı rayondadır?", ["Bakı", "Lənkəran", "Masallı", "Şəki"], 1),
      createQ("Araz çayının uzunluğu neçə km-dir?", ["666", "776", "886", "1072"], 3),
      createQ("Qobustanın qədim qaya rəsmləri hansı dövrdən qalmaqdır?", ["E.ə. 3-2-ci minillik", "E.ə. 10-20-ci minillik", "E.ə. 5-ci minillik", "E.ə. 1-ci minillik"], 1),
      createQ("Azərbaycanda ən çox atmosfer yağıntısı düşən yer hansıdır?", ["Şəki", "Lənkəran", "Yardımlı", "Lerik"], 2),
      createQ("Məşəli dağ landşaftları Azərbaycanda əsasən hansı hündürlükdə yayılmışdır?", ["500-1500 m", "600-1800 m", "800-2000 m", "1000-2500 m"], 1),
      createQ("Şahdağ Milli Parkı hansı rayonlarda yerləşir?", ["Quba, Qusar, Oğuz, İsmayıllı", "Şəki, Qəbələ, Oğuz", "Quba, Xaçmaz, Qusar", "Balakən, Zaqatala, Qəbələ"], 0),
      createQ("Azərbaycanın ən böyük çay deltası hansıdır?", ["Kür deltası", "Araz deltası", "Samur deltası", "Astaraçay deltası"], 0),
      createQ("Batı Yarımkürə ilə Şərq Yarımkürəni ayıran meridian hansıdır?", ["Başlanğıc meridian (0°)", "90° meridian", "180° meridian", "45° meridian"], 2),
      createQ("Hirkan Milli Parkı hansı bölgədədir?", ["Talış zonası", "Lənkəran zonası", "Gəncə-Qazax zonası", "Şirvan zonası"], 1),
      createQ("Azərbaycanın ən şərq nöqtəsi hansı şəhərdədir?", ["Neftçala", "Bakı", "Sumqayıt", "Xıllı dəniz neft daşları"], 3),
      createQ("Qobustan qoruğunun sahəsi təqribən neçə hektar?", ["3096", "4096", "5096", "6096"], 1),
      createQ("Naxçıvan MR-in sahəsi neçə kv.km-dir?", ["4500", "5500", "5502", "6500"], 2),
      createQ("Azərbaycanda il ərzində orta temperatur neçə dərəcədir?", ["12-13°C", "14-15°C", "16-17°C", "18-19°C"], 1),
      createQ("Dünyanın ən böyük mərcan rifi hansı okeanın sahilindədir?", ["Sakit okean (Avstraliya)", "Atlantik okean", "Hind okeanı", "Şimal Buzlu okeanı"], 0),
      createQ("Xəzər dənizinin ən dərin yeri neçə metr dərinlikdədir?", ["980", "1025", "1115", "1250"], 1),
      createQ("Azərbaycanın enerji potensialı ən yüksək olan çayı hansıdır?", ["Kür", "Araz", "Astaraçay", "Samur"], 0),
      createQ("Ordubad Milli Parkı hansı əyalətdədir?", ["Naxçıvan MR", "Kəlbəcər", "Şuşa", "Ağdam"], 0),
      createQ("Azərbaycan subtropik iqlim qurşağında hansı sahədə yerləşir?", ["Şimal", "Cənub (Lənkəran zonası)", "Qərb", "Mərkəz"], 1),
      createQ("Dünyanın ən duzlu gölü hansıdır?", ["Böyük Duz gölü (İran)", "Ölü dəniz", "Böyük Duz gölü (ABŞ)", "Aral gölü"], 1),
      createQ("Azərbaycanın torpaq örtüyünün neçə faizi boz-qəhvəyi torpaqlardır?", ["Təqribən 20%", "Təqribən 30%", "Təqribən 40%", "Təqribən 50%"], 2),
      createQ("Mariana çuxuru dünyanın ən dərin yeridir. Neçə metr dərinlikdədir?", ["10.000", "10.500", "10.994", "11.500"], 2),
      createQ("Abşeronun neçə palçıq vulkanı var?", ["Təqribən 30", "Təqribən 40", "Təqribən 50", "Təqribən 60"], 1),
      createQ("Azərbaycanın Flora Muzeyi ilk dəfə hansıl ildə yaradılmışdır?", ["1935", "1945", "1950", "1960"], 1),
    ]
  },
  DIN: {
    easy: [
      createQ("İslamda müqəddəs kitab hansıdır?", ["Tövrat", "Quran", "İncil", "Zəbur"], 1),
      createQ("Müsəlmanların qibləsi hansı şəhərdədir?", ["Mədinə", "Qüds", "Məkkə", "Bağdad"], 2),
      createQ("İslam dininə görə peyğəmbərlərin sonuncusu kimdir?", ["İsa", "Musa", "İbrahim", "Məhəmməd"], 3),
      createQ("Müsəlmanlar gündə neçə dəfə namaz qılarlar?", ["3", "5", "7", "10"], 1),
      createQ("İslamın müqəddəs ayı hansıdır?", ["Məhərrəm", "Ramazan", "Şəvval", "Zilhiccə"], 1),
      createQ("Xristianlığın müqəddəs kitabı hansıdır?", ["Tövrat", "Quran", "İncil", "Avesta"], 2),
      createQ("Müsəlmanların həcc ziyarəti hansı şəhərdədir?", ["Mədinə", "Qüds", "Məkkə", "Kərbəla"], 2),
      createQ("İslam dininə görə oruc hansı ayda tutulur?", ["Məhərrəm", "Ramazan", "Şaban", "Rəcəb"], 1),
      createQ("İslam dinində əsas iman rüknlərinin sayı neçədir?", ["3", "4", "5", "6"], 3),
      createQ("Yəhudilərin müqəddəs kitabı hansıdır?", ["Tövrat", "İncil", "Quran", "Zəbur"], 0),
      createQ("İslam dinində rükünlərin (əsas şərtlərin) sayı neçədir?", ["3", "4", "5", "6"], 2),
      createQ("Kəbə hansı şəhərdədir?", ["Mədinə", "Məkkə", "Qüds", "Bağdad"], 1),
      createQ("Qurban bayramı hansı ayda qeyd edilir?", ["Ramazan", "Şəvval", "Zilhiccə", "Zilqədə"], 2),
      createQ("Məhəmməd peyğəmbər hansı şəhərdə doğulub?", ["Mədinə", "Məkkə", "Tə'if", "Qüds"], 1),
      createQ("Ramazan bayramı neçə gün qeyd edilir?", ["1 gün", "2 gün", "3 gün", "4 gün"], 2),
      createQ("İslam dininə görə zəkat nədir?", ["Namaz", "Oruc", "Xeyriyyə, sədəqə", "Həcc"], 2),
      createQ("Məscid nədir?", ["Müsəlmanların ibadət yeri", "Xristianların ibadət yeri", "Yəhudilərin ibadət yeri", "Buddistlərin ibadət yeri"], 0),
      createQ("Müsəlmanların müqəddəs gecəsi hansıdır?", ["Mirac gecəsi", "Qədir gecəsi", "Bərat gecəsi", "Hamısı"], 3),
      createQ("İslam təqvimi hansı hadisədən başlanır?", ["Məhəmmədin doğulması", "Hicri", "İlk vəhyin nazil olması", "Məkkənin fəthi"], 1),
      createQ("Cümə namazı həftənin hansı günü qılınır?", ["Şənbə", "Bazar", "Cümə", "Cümə axşamı"], 2),
      createQ("İslam dininə görə peyğəmbərlərin ilki kimdir?", ["Adəm", "Nuh", "İbrahim", "Musa"], 0),
      createQ("Qurani-Kərimin nazil olduğu ay hansıdır?", ["Məhərrəm", "Ramazan", "Şaban", "Rəcəb"], 1),
      createQ("İslamda haram olan içki hansıdır?", ["Alkoqollu içkilər", "Şərbət", "Çay", "Qəhvə"], 0),
      createQ("Müsəlmanların təqvimi hansı adla tanınır?", ["Şəmsi təqvim", "Hicri təqvim", "Miladi təqvim", "Qəməri təqvim"], 1),
      createQ("Namaz qılmaq üçün hansı istiqamətə üz tutulur?", ["Şərqə", "Qərbə", "Qibləyə (Kəbəyə)", "Şimala"], 2),
      createQ("Məhəmməd peyğəmbərin əmisi oğlu və zövcəsinin ərinin adı?", ["Əbu Bəkir", "Əli", "Ömər", "Osman"], 1),
      createQ("Qurban bayramı neçə gün qeyd edilir?", ["2 gün", "3 gün", "4 gün", "5 gün"], 2),
      createQ("Hicri təqvimdə ilk ay hansıdır?", ["Ramazan", "Məhərrəm", "Şəvval", "Rəcəb"], 1),
      createQ("İslam dinində namaz əvvəlində nə deyilir?", ["Təkbir (Allahu Əkbər)", "Əmin", "Salam", "Bismillah"], 0),
      createQ("Peyğəmbərə ilk vəhy hansı mələk tərəfindən gəldi?", ["Mikail", "Cəbrayıl", "İsrafil", "Azrail"], 1),
    ],
    medium: [
      createQ("Qurani-Kərimin neçə surəsi var?", ["100", "110", "114", "120"], 2),
      createQ("İslamda ilk xəlifə kim olmuşdur?", ["Əli", "Əbu Bəkir", "Ömər", "Osman"], 1),
      createQ("Qədir gecəsi hansı ayın hansı gecəsidir?", ["Ramazanın 21-ci gecəsi", "Ramazanın 23-cü gecəsi", "Ramazanın 25-ci gecəsi", "Ramazanın 27-ci gecəsi"], 3),
      createQ("Hicri Azərbaycanın hansı ildə baş verdi?", ["610", "622", "630", "632"], 1),
      createQ("İslamda \"təvhid\" nə deməkdir?", ["Namaz qılmaq", "Allahın birliyinə iman", "Həcc etmək", "Oruc tutmaq"], 1),
      createQ("Məhəmməd peyğəmbər neçə yaşında peyğəmbərliyə çağırıldı?", ["30", "35", "40", "45"], 2),
      createQ("İslamda beş vaxt namazın adları hansılardır?", ["Səhər, günorta, əsr, axşam, gecə", "Sübh, zöhr, əsr, məğrib, işa", "Fəcr, günorta, ikindi, axşam, yatsı", "B və C düzgündür"], 3),
      createQ("Qurani-Kərimin ən uzun surəsi hansıdır?", ["Fatiha", "Bəqərə", "Ali-İmran", "Nisa"], 1),
      createQ("Mədinə şəhərinin əvvəlki adı nə idi?", ["Yəsrib", "Tə'if", "Qüds", "Xeybər"], 0),
      createQ("Cümə namazından əvvəl oxunan xütbə neçə hissədən ibarətdir?", ["1", "2", "3", "4"], 1),
      createQ("İslamda \"şəhadət\" nə deməkdir?", ["Şahidlik", "Şəhid olmaq", "\"Allahdan başqa ilah yoxdur\" kəlməsi", "Namaz qılmaq"], 2),
      createQ("Qurani-Kərimdə neçə ayə var (təqribi)?", ["5000", "6000", "6236", "7000"], 2),
      createQ("Məkkənin fəthi hansı ildə baş verdi?", ["622", "625", "630", "632"], 2),
      createQ("İslam dinində \"ümmət\" nə deməkdir?", ["Millət", "İslam icması", "Qəbilə", "Dövlət"], 1),
      createQ("Həccin fərzlərindən biri hansıdır?", ["İhram", "Ərəfatda dayanmaq", "Təvaf", "Hamısı"], 3),
      createQ("Mirac gecəsi nə ilə əlaqədardır?", ["Peyğəmbərin doğum günü", "Peyğəmbərin səmaya qalxması", "İlk vəhyin nazil olması", "Hicri hadisəsi"], 1),
      createQ("Qurani-Kərimin ən qısa surəsi hansıdır?", ["Fatiha", "Kövsar", "İxlas", "Nəsr"], 1),
      createQ("Zəkət vermək kimə vacibdir?", ["Yalnız kişilərə", "Nisaba malik olanlara", "Hamıya", "Yalnız zənginlərə"], 1),
      createQ("İslamda \"sünni\" və \"şiə\" bölgüsü nə ilə əlaqədardır?", ["Namaz fərqləri", "Xəlifəlik məsələsi", "Oruc qaydaları", "Həcc fərqləri"], 1),
      createQ("Əşura günü hansı ayda qeyd edilir?", ["Ramazan", "Məhərrəm", "Şəban", "Zilhiccə"], 1),
      createQ("İslamda \"müctəhid\" kimi tanınır?", ["Hakim", "İslam alimlərindən, şəriət mütəxəssisi", "İmam", "Mütərcim"], 1),
      createQ("Peyğəmbər Məhəmmədin neçə oğlu olmuşdur?", ["2", "3", "4", "5"], 1),
      createQ("Bədr döyüşü hansı ildə baş vermişdir?", ["622", "624", "625", "627"], 1),
      createQ("Qurani-Kərimdə \"Yusif\" surəsi nə ilə məşhurdur?", ["Ən uzun surədir", "Ən qısa surədir", "Əhsən qisələr (ən gözəl hekayə)", "Əbədi qanunlar"], 2),
      createQ("Məhəmməd peyğəmbərin qızı Fatimənin əri kim idi?", ["Əbu Bəkir", "Əli", "Ömər", "Osman"], 1),
      createQ("Ramazan orucunun tutulması nə vaxt başlayır?", ["Sübh namazından", "Fəcr vaxtından", "Günəş çıxandan", "Gecə yarısından"], 1),
      createQ("İslamda \"icma\" nə deməkdir?", ["Yığıncaq", "Alimlərin ittifaqı", "Məclis", "Namaz"], 1),
      createQ("Peyğəmbər Məhəmməd neçə yaşında vəfat etmişdir?", ["60", "63", "65", "70"], 1),
      createQ("Əli xəlifənin dövründə paytaxt hansı şəhər idi?", ["Məkkə", "Mədinə", "Küfə", "Bağdad"], 2),
      createQ("İslamda \"hədis\" nə deməkdir?", ["Peyğəmbərin sözləri və əməlləri", "Quran ayələri", "Dua", "Qanun"], 0),
    ],
    hard: [
      createQ("\"Əl-Buhari\" kimdir?", ["Xəlifə", "Məşhur hədis alimi", "Filosof", "Şair"], 1),
      createQ("Qurani-Kərimin ilk nazil olan ayələri hansı surədəndir?", ["Fatiha", "Ələk", "Qələm", "Müddəssir"], 1),
      createQ("İslam hüququnun dörd əsas mənbəyi hansılardır?", ["Quran, Hədis, İcma, Qiyas", "Quran, Hədis, Rəy, İcma", "Quran, Sünni, İcma, İctihad", "Quran, Hədis, Fiqh, İcma"], 0),
      createQ("İmam Əbu Hanifə hansı məzhəbin banisidir?", ["Şafei", "Hənbəli", "Hənəfi", "Maliki"], 2),
      createQ("Uhud döyüşü hansı ildə baş vermişdir?", ["623", "625", "627", "630"], 1),
      createQ("Kərbəla faciəsi hansı ildə baş vermişdir?", ["661", "670", "680", "690"], 2),
      createQ("İslamda dörd böyük mələyin adları hansılardır?", ["Cəbrayıl, Mikail, İsrafil, Azrail", "Cəbrayıl, Mikail, Rəfayıl, Azrail", "Cəbrayıl, Mikail, İsrafil, Münkər", "Cəbrayıl, Mikail, Nəkir, Azrail"], 0),
      createQ("\"Təfsir\" elmi nə ilə məşğul olur?", ["Hədislərin şərhi", "Quranın şərhi və izahı", "Fiqh qaydaları", "Ərəb dili qrammatikası"], 1),
      createQ("Peyğəmbər Məhəmmədin ilk arvadının adı nə idi?", ["Ayşə", "Xədicə", "Hafsa", "Zeynəb"], 1),
      createQ("Əməvi xilafəti hansı ildə quruldu?", ["632", "644", "661", "750"], 2),
      createQ("İslamda \"Əhli-beyt\" kimləri əhatə edir?", ["Bütün müsəlmanlar", "Peyğəmbərin ailəsi", "Səhabələr", "Xəlifələr"], 1),
      createQ("Abbasi xilafəti hansı ildə başladı?", ["661", "711", "750", "800"], 2),
      createQ("İslam tarixində \"Ridda müharibələri\" nə ilə əlaqədardır?", ["Məkkənin fəthi", "Peyğəmbərdən sonra dindən dönənlərə qarşı", "Fəth döyüşləri", "Xaricilərə qarşı"], 1),
      createQ("İmam Malik hansı məzhəbin banisidir?", ["Hənəfi", "Maliki", "Şafei", "Hənbəli"], 1),
      createQ("\"Əl-Muvətta\" hansı alimin əsəridir?", ["İmam Əbu Hanifə", "İmam Malik", "İmam Şafei", "İmam Əl-Buhari"], 1),
      createQ("İslamda \"müctəhid\" olmaq üçün neçə elm bilmək lazımdır?", ["5-6", "8-10", "12-15", "20-dən çox"], 2),
      createQ("Peyğəmbər Məhəmmədin doğum ili hansıdır?", ["570", "571", "580", "590"], 1),
      createQ("İslamda \"müfti\" kimi tanınır?", ["Hakim", "Fetva verən alim", "İmam", "Xətib"], 1),
      createQ("Qurani-Kərimdə neçə peyğəmbərin adı çəkilir?", ["20", "25", "30", "35"], 1),
      createQ("Xəndək döyüşü hansı ildə baş vermişdir?", ["625", "627", "628", "630"], 1),
      createQ("İslamda \"vəli\" kimi tanınır?", ["Hakim", "Allaha yaxın olan, müqəddəs şəxs", "Xəlifə", "Qazi"], 1),
      createQ("Osmanlı dövlətinin ilk xəlifəsi kim olmuşdur?", ["Osman Qazi", "Orxan Qazi", "I Yavuz Sultan Səlim", "Fateh Sultan Mehmet"], 2),
      createQ("\"Təqlid\" termini nə deməkdir?", ["İctihad etmək", "Müctəhidə əməl etmək, izləmək", "Öyrənmək", "Tərcümə etmək"], 1),
      createQ("İslamda \"bida\" nə deməkdir?", ["Yenilik", "Dində sonradan əlavə edilən əməl", "İcad", "Kəşf"], 1),
      createQ("Peyğəmbərin Hicrətdən əvvəl Məkkədə qaldığı müddət neçə ildir?", ["10", "11", "12", "13"], 3),
      createQ("İslam düşüncəsində \"Mötəzilə\" məktəbi nə ilə tanınır?", ["Mistisizm", "Əqli, rasional yanaşma", "Fəlsəfi təfəkkür", "Sufi təlimləri"], 1),
      createQ("\"Qurani-Kərimin toplanması\" hansı xəlifə dövründə tamamlandı?", ["Əbu Bəkir", "Ömər", "Osman", "Əli"], 2),
      createQ("İslamda \"təriqət\" nə deməkdir?", ["Fiqh məzhəbi", "Təsəvvüf yolu", "Siyasi hərəkat", "Təhsil sistemi"], 1),
      createQ("Hüdeybiyə sülhü hansı ildə bağlanmışdır?", ["626", "627", "628", "629"], 2),
      createQ("İslam fəlsəfəsində \"İbn Sina\" hansı adla tanınır?", ["Əl-Farabi", "Avicenna", "Əl-Kindi", "İbn Rüşd"], 1),
    ]
  },
  TARIX: {
    easy: [
      createQ("Azərbaycan Xalq Cümhuriyyəti hansı ildə yaradılmışdır?", ["1917", "1918", "1919", "1920"], 1),
      createQ("Birinci Dünya Müharibəsi hansı illərdə baş vermişdir?", ["1912-1916", "1914-1918", "1916-1920", "1918-1922"], 1),
      createQ("Azərbaycanın milli liderinə hansı ünvan verilib?", ["Əbdürrəhim bəy Haqverdiyev", "Məmməd Əmin Rəsulzadə", "Heydər Əliyev", "Nəriman Nərimanov"], 2),
      createQ("İkinci Dünya Müharibəsi hansı illərdə baş vermişdir?", ["1939-1945", "1940-1946", "1938-1944", "1941-1945"], 0),
      createQ("Azərbaycanın müstəqilliyi hansı tarixdə bərpa edilmişdir?", ["28 May 1918", "28 Aprel 1920", "18 Oktyabr 1991", "31 Dekabr 1991"], 2),
      createQ("Sovet İttifaqı hansı ildə dağılmışdır?", ["1989", "1990", "1991", "1992"], 2),
      createQ("Qanlı Yanvar hadisəsi hansı tarixdə baş vermişdir?", ["19-20 Yanvar 1990", "20-21 Yanvar 1990", "18-19 Yanvar 1990", "21-22 Yanvar 1990"], 1),
      createQ("Azərbaycanın bayrağı hansı rənglərdən ibarətdir?", ["Qırmızı, yaşıl, ağ", "Mavi, qırmızı, yaşıl", "Göy, qırmızı, yaşıl", "Mavi, sarı, qırmızı"], 2),
      createQ("Xocalı soyqırımı hansı tarixdə baş vermişdir?", ["25-26 Fevral 1992", "26-27 Fevral 1992", "27-28 Fevral 1992", "28-29 Fevral 1992"], 1),
      createQ("Osmanlı İmperiyası hansı ildə süqut etmişdir?", ["1918", "1920", "1922", "1923"], 2),
      createQ("Türkiyə Respublikası hansı ildə yaradılmışdır?", ["1920", "1922", "1923", "1924"], 2),
      createQ("Azərbaycan SSR-i hansı ildə yaradılmışdır?", ["1918", "1920", "1922", "1936"], 1),
      createQ("Birinci Qarabağ müharibəsi hansı illərdə olmuşdur?", ["1988-1994", "1990-1994", "1991-1994", "1992-1994"], 0),
      createQ("44 günlük Vətən müharibəsi hansı tarixdə başlamışdır?", ["27 Sentyabr 2020", "28 Sentyabr 2020", "29 Sentyabr 2020", "30 Sentyabr 2020"], 0),
      createQ("Şuşa şəhəri hansı tarixdə azad edilmişdir?", ["8 Noyabr 2020", "9 Noyabr 2020", "10 Noyabr 2020", "7 Noyabr 2020"], 0),
      createQ("Azərbaycan hansı ildə BMT-yə üzv olmuşdur?", ["1991", "1992", "1993", "1994"], 1),
      createQ("Heydər Əliyev ilk dəfə hansı ildə Azərbaycana rəhbərlik etməyə başladı?", ["1969", "1970", "1971", "1972"], 0),
      createQ("Berlin divarı hansı ildə yıxılmışdır?", ["1987", "1989", "1990", "1991"], 1),
      createQ("Naxçıvan Muxtar Respublikası hansı ildə yaradılmışdır?", ["1920", "1921", "1924", "1936"], 2),
      createQ("Heydər Əliyev Fondunun prezidenti kimdir?", ["İlham Əliyev", "Mehriban Əliyeva", "Leyla Əliyeva", "Arzu Əliyeva"], 1),
      createQ("Bakı şəhəri neçənci əsrdə yaranmışdır?", ["V əsr", "VIII əsr", "X əsr", "XII əsr"], 0),
      createQ("Azərbaycanın \"Əsrin müqaviləsi\" hansı ildə imzalanmışdır?", ["1992", "1993", "1994", "1995"], 2),
      createQ("İlham Əliyev ilk dəfə prezident seçiləndə hansı ildə idi?", ["2001", "2002", "2003", "2004"], 2),
      createQ("Bakı-Tbilisi-Ceyhan neft kəməri hansı ildə istifadəyə verilmişdir?", ["2004", "2005", "2006", "2007"], 2),
      createQ("Sovet İttifaqının ilk rəhbəri kim olmuşdur?", ["İosif Stalin", "Vladimir Lenin", "Lev Troçki", "Nikita Xruşşov"], 1),
      createQ("Azərbaycan alfabeti neçə dəfə dəyişdirilmişdir?", ["1", "2", "3", "4"], 2),
      createQ("Heydər Əliyev hansı ildə vəfat etmişdir?", ["2001", "2002", "2003", "2004"], 2),
      createQ("I Avropa Oyunları Bakıda hansı ildə keçirilmişdir?", ["2013", "2014", "2015", "2016"], 2),
      createQ("Formula 1 yarışı Bakıda ilk dəfə hansı ildə keçirildi?", ["2014", "2015", "2016", "2017"], 2),
      createQ("Azərbaycan Respublikasının Konstitusiyası hansı ildə qəbul edilmişdir?", ["1992", "1993", "1994", "1995"], 3),
    ],
    medium: [
      createQ("Azərbaycan Xalq Cümhuriyyətinin ilk baş naziri kim olmuşdur?", ["Məmməd Əmin Rəsulzadə", "Fətəli xan Xoyski", "Nəsib bəy Yusifbəyli", "Əlimərdan bəy Topçubaşov"], 1),
      createQ("Neftçilər günü Azərbaycanda nə vaxt qeyd edilir?", ["19 Sentyabr", "20 Sentyabr", "21 Sentyabr", "22 Sentyabr"], 1),
      createQ("Nizami Gəncəvi hansı əsrdə yaşamışdır?", ["X əsr", "XI əsr", "XII əsr", "XIII əsr"], 2),
      createQ("Şirvanşahlar sarayı kompleksi hansı əsrdə tikilmişdir?", ["XII-XIII əsr", "XIII-XIV əsr", "XIV-XV əsr", "XV-XVI əsr"], 3),
      createQ("Qız qalası hansı əsrə aiddir?", ["VII-VIII əsr", "VIII-IX əsr", "X-XI əsr", "XII əsr"], 3),
      createQ("Atropat dövləti hansı ərazilərdə mövcud olmuşdur?", ["Şimali Azərbaycan", "Cənubi Azərbaycan", "Qərbi Azərbaycan", "Şərqi Azərbaycan"], 1),
      createQ("Qafqaz Albaniyası dövləti təqribən hansı dövrdə mövcud olmuşdur?", ["E.ə. VIII əsr - VII əsr", "E.ə. IV əsr - VIII əsr", "E.ə. II əsr - X əsr", "E.ə. I əsr - V əsr"], 1),
      createQ("Azərbaycan ərazisində ilk müsəlman dövləti hansıdır?", ["Səlcuqlular", "Şirvanşahlar", "Sacilər", "Osmanlı"], 2),
      createQ("Naxçıvan qədim şəhər kimi neçənci minilliyə aiddir?", ["II minillik", "III minillik", "IV minillik", "V minillik"], 2),
      createQ("Qədim Azərbaycan şairi Xətai kimdir?", ["Füzuli", "Nəsimi", "Şah İsmayıl Xətai", "Qazi Bürhanəddin"], 2),
      createQ("Səfəvilər dövləti hansı ildə yaradılmışdır?", ["1491", "1501", "1511", "1521"], 1),
      createQ("Azərbaycan ərazisində ilk neft quyusu hansı ildə qazılmışdır?", ["1846", "1848", "1847", "1849"], 2),
      createQ("Nobel qardaşları Bakıda neft sənayesinə hansı ildə başladılar?", ["1873", "1875", "1877", "1879"], 0),
      createQ("İrəvan xanlığı hansı ildə ruslar tərəfindən ələ keçirilmişdir?", ["1826", "1827", "1828", "1829"], 2),
      createQ("Gülüstan müqaviləsi hansı ildə bağlanmışdır?", ["1812", "1813", "1814", "1815"], 1),
      createQ("Türkmənçay müqaviləsi hansı ildə imzalanmışdır?", ["1826", "1827", "1828", "1829"], 2),
      createQ("Azərbaycan Milli Şurası hansı tarixdə yaradılmışdır?", ["25 Oktyabr 1917", "27 Oktyabr 1917", "29 Oktyabr 1917", "30 Oktyabr 1917"], 2),
      createQ("Mart soyqırımı hansı ildə baş vermişdir?", ["1917", "1918", "1919", "1920"], 1),
      createQ("Azərbaycan Xalq Cümhuriyyəti neçə il mövcud olmuşdur?", ["21 ay", "22 ay", "23 ay", "24 ay"], 2),
      createQ("Müsavat partiyası hansı ildə yaradılmışdır?", ["1909", "1911", "1912", "1915"], 0),
      createQ("Məmməd Əmin Rəsulzadə hansı ildə Türkiyədə vəfat etmişdir?", ["1953", "1954", "1955", "1956"], 2),
      createQ("Azərbaycan teatrının banisi kimdir?", ["Hüseyn Cavid", "Cəfər Cabbarlı", "Həsən bəy Zərdabi", "Mirzə Fətəli Axundzadə"], 3),
      createQ("\"Əkinçi\" qəzeti hansı ildə nəşrə başladı?", ["1873", "1875", "1877", "1879"], 1),
      createQ("İlk Azərbaycan teatr tamaşası hansı ildə nümayiş olunmuşdur?", ["1873", "1874", "1875", "1876"], 0),
      createQ("Azərbaycanın ilk operası hansıdır?", ["Koroğlu", "Leyli və Məcnun", "Əsli və Kərəm", "Şah İsmayıl"], 1),
      createQ("\"Leyli və Məcnun\" operası hansı ildə tamaşaya qoyulmuşdur?", ["1906", "1908", "1910", "1912"], 1),
      createQ("Bakı şəhəri hansı ildə qala divarlarından kənara çıxdı?", ["1850", "1860", "1865", "1870"], 1),
      createQ("Azərbaycanın ilk kinematoqrafiyası hansı ildə yaradılmışdır?", ["1898", "1905", "1908", "1915"], 0),
      createQ("Qacar sülaləsi hansı illərdə hakimiyyətdə olmuşdur?", ["1779-1925", "1785-1920", "1794-1925", "1800-1930"], 2),
      createQ("Nəsrəddin şah hansı sülaləyə mənsub idi?", ["Səfəvilər", "Afşarlar", "Qacarlar", "Pəhləvilər"], 2),
    ],
    hard: [
      createQ("Azərbaycan Xalq Cümhuriyyətində qadınlara seçki hüququ nə vaxt verilmişdir?", ["1918", "1919", "1920", "Heç vaxt"], 0),
      createQ("Manna dövləti hansı dövrdə mövcud olmuşdur?", ["E.ə. XII-VII əsrlər", "E.ə. X-VI əsrlər", "E.ə. IX-VII əsrlər", "E.ə. VIII-V əsrlər"], 2),
      createQ("Əlincə qalası hansı xanlıqda yerləşirdi?", ["Qarabağ xanlığı", "İrəvan xanlığı", "Naxçıvan xanlığı", "Gəncə xanlığı"], 1),
      createQ("Şuşa qalası hansı ildə təsis edilmişdir?", ["1750", "1752", "1755", "1757"], 1),
      createQ("Panah Əli xan tərəfindən Qarabağ xanlığının paytaxtı hansı şəhər idi?", ["Şuşa", "Şəki", "Gəncə", "Bayat"], 3),
      createQ("İbrahim xəlil xan hansı xanlığın hökmdarı idi?", ["Şəki xanlığı", "Qarabağ xanlığı", "Naxçıvan xanlığı", "Gəncə xanlığı"], 1),
      createQ("Bakı xanlığı hansı ildə Rusiya tərəfindən ələ keçirilmişdir?", ["1803", "1804", "1805", "1806"], 3),
      createQ("Gəncə xanlığı hansı ildə ləğv edildi?", ["1802", "1803", "1804", "1805"], 2),
      createQ("Cəvad xan Ziyadov hansı xanlığın sonuncu xanı idi?", ["Bakı xanlığı", "Quba xanlığı", "Şirvan xanlığı", "Lənkəran xanlığı"], 0),
      createQ("Nədir şah Əfşar hansı ildə öldürüldü?", ["1746", "1747", "1748", "1749"], 1),
      createQ("Qaraqoyunlu dövləti hansı illərdə mövcud olmuşdur?", ["1375-1468", "1380-1469", "1410-1468", "1350-1468"], 0),
      createQ("Ağqoyunlu dövləti hansı illərdə mövcud olmuşdur?", ["1378-1508", "1390-1501", "1400-1508", "1403-1507"], 0),
      createQ("Atabəylər dövləti hansı illərdə mövcud olmuşdur?", ["1136-1225", "1146-1231", "1136-1231", "1140-1225"], 2),
      createQ("Eldəniz Atabəy hansı ildə hakimiyyətə gəldi?", ["1135", "1136", "1137", "1138"], 1),
      createQ("Şirvanlı İbrahim bin Məhəmməd kimdir?", ["Filosof", "Astronomiya alimi və riyaziyyatçı", "Şair", "Sərkərdə"], 1),
      createQ("Məhəmməd Füzuli hansı ildə vəfat etmişdir?", ["1555", "1556", "1557", "1558"], 1),
      createQ("Nəsimi hansı şəhərdə şəhid edilmişdir?", ["Bakı", "Təbriz", "Hələb", "Şamaxı"], 2),
      createQ("Xaqani Şirvani hansı əsrdə yaşamışdır?", ["XI əsr", "XII əsr", "XIII əsr", "XIV əsr"], 1),
      createQ("Qazi Bürhanəddin dövləti hansı illərdə mövcud olmuşdur?", ["1356-1398", "1360-1398", "1364-1398", "1370-1398"], 0),
      createQ("Şah İsmayıl Xətainin Çaldıran döyüşündə məğlubiyyəti hansı ildə baş vermişdir?", ["1512", "1513", "1514", "1515"], 2),
      createQ("Azərbaycan SSR-də \"xalqlar düşməni\" kimi repressiya olunanların sayı təqribən nə qədərdir?", ["50.000", "80.000", "100.000", "120.000"], 3),
      createQ("Azərbaycan ərazisində olan ilk Aşələn mədəniyyəti hansı dövrdəndir?", ["E.ə. 1,5 milyon il", "E.ə. 1 milyon il", "E.ə. 500 min il", "E.ə. 100 min il"], 0),
      createQ("Naxçıvanda Mömünə xatun türbəsi hansı ildə tikilmişdir?", ["1175", "1186", "1190", "1195"], 1),
      createQ("Azərbaycan ərazisində ilk qədim insan daşınmaz nümunəsi Azıx mağarasında hansı dövrdən tapılmışdır?", ["E.ə. 300 min il", "E.ə. 400 min il", "E.ə. 500 min il", "E.ə. 600 min il"], 1),
      createQ("Uzun Həsən hansı dövlətin hökmdarı idi?", ["Qaraqoyunlu", "Ağqoyunlu", "Səfəvi", "Afşar"], 1),
      createQ("Babək üsyanı hansı illərdə baş vermişdir?", ["816-837", "820-838", "816-838", "817-837"], 0),
      createQ("Məhəmməd Cahan Pəhləvan atabəyləri hansı ildə hakimiyyətə gəldi?", ["1169", "1174", "1175", "1179"], 1),
      createQ("Osmanlı-Səfəvi Əməsiyyə sülh müqaviləsi hansı ildə imzalanmışdır?", ["1553", "1555", "1557", "1559"], 1),
      createQ("I Şah Abbas hakimiyyəti hansı illərdə sürmüşdür?", ["1587-1629", "1588-1629", "1587-1630", "1590-1629"], 0),
      createQ("Mirzə Kazım bəy tərəfindən yazılmış məşhur tarix əsəri hansıdır?", ["Gülüstani-İrəm", "Tarix-i Aləmaray-i Abbasi", "Təzkirət ül-Müluk", "Kitabi Dədə Qorqud"], 0),
    ]
  },
  FANTASTIK: {
    easy: [
      createQ("\"Harry Potter\" seriyasının müəllifi kimdir?", ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "C.S. Lewis"], 1),
      createQ("\"Üzüklərin Hökmdarı\" əsərinin müəllifi kimdir?", ["J.K. Rowling", "C.S. Lewis", "J.R.R. Tolkien", "George R.R. Martin"], 2),
      createQ("Harry Potter hansı evdə oxuyurdu?", ["Slytherin", "Ravenclaw", "Hufflepuff", "Gryffindor"], 3),
      createQ("\"Ulduz Müharibələri\" (Star Wars) hansı janrda əsərdir?", ["Qorxu", "Elm-fantastika", "Detektiv", "Romantika"], 1),
      createQ("Superman hansı planetdəndir?", ["Mars", "Krypton", "Vulkan", "Asgard"], 1),
      createQ("\"Narnia salnaməsi\" əsərlərinin müəllifi kimdir?", ["J.R.R. Tolkien", "C.S. Lewis", "Philip Pullman", "Terry Pratchett"], 1),
      createQ("Harry Potter-in ən yaxşı dostları kim olub?", ["Ron və Hermiona", "Neville və Luna", "Fred və George", "Draco və Crabbe"], 0),
      createQ("Spider-Man-in əsl adı nədir?", ["Bruce Wayne", "Peter Parker", "Tony Stark", "Clark Kent"], 1),
      createQ("\"Hobbits\" əsərinin əsas qəhrəmanı kimdir?", ["Frodo", "Gandalf", "Bilbo", "Aragorn"], 2),
      createQ("Batman-in əsl adı nədir?", ["Peter Parker", "Bruce Wayne", "Tony Stark", "Clark Kent"], 1),
      createQ("\"Game of Thrones\" serialı hansı roman seriyasından əsaslanıb?", ["Wheel of Time", "The Witcher", "A Song of Ice and Fire", "The Kingkiller Chronicle"], 2),
      createQ("Iron Man-in əsl adı nədir?", ["Bruce Banner", "Tony Stark", "Steve Rogers", "Thor Odinson"], 1),
      createQ("Voldemort-un əsl adı nədir?", ["Tom Riddle", "Severus Snape", "Lucius Malfoy", "Barty Crouch"], 0),
      createQ("\"The Avengers\" hansı kino kainatına aiddir?", ["DC", "Marvel", "Star Wars", "Star Trek"], 1),
      createQ("Gandalf hansı əsərin personajıdır?", ["Harry Potter", "Narnia", "Üzüklərin Hökmdarı", "Witcher"], 2),
      createQ("Thor hansı mifologiyadan götürülüb?", ["Yunan", "Roma", "Skandinav", "Misir"], 2),
      createQ("\"The Matrix\" filminin baş qəhrəmanı kimdir?", ["John Wick", "Neo", "John Connor", "Kyle Reese"], 1),
      createQ("Darth Vader hansı filmlərdə görünür?", ["Star Trek", "Star Wars", "Guardians of the Galaxy", "Avatar"], 1),
      createQ("\"Avatar\" filmində hansı planetdə hərəkət baş verir?", ["Pandora", "Krypton", "Tatooine", "LV-426"], 0),
      createQ("Wonder Woman hansı yerə məxsusdur?", ["Asgard", "Krypton", "Themyscira", "Wakanda"], 2),
      createQ("\"E.T.\" filmində E.T. nədir?", ["Robot", "Əcnəbi (yadplanetli)", "Mutant", "Android"], 1),
      createQ("Hulk-un əsl adı nədir?", ["Tony Stark", "Bruce Banner", "Steve Rogers", "Peter Parker"], 1),
      createQ("\"Terminator\" filminin baş qəhrəmanı kimdir?", ["Arnold Schwarzenegger", "Sylvester Stallone", "Bruce Willis", "Jean-Claude Van Damme"], 0),
      createQ("Black Panther hansı ölkənin hökmdarıdır?", ["Themyscira", "Asgard", "Wakanda", "Atlantis"], 2),
      createQ("\"Doctor Strange\" hansı növ supergüclərə malikdir?", ["Super güc", "Sehrli güclər", "Texnologiya", "Mutasiya"], 1),
      createQ("\"Interstellar\" filminin mövzusu nədir?", ["Vaxt səyahəti", "Kosmik səyahət", "Zombi apokalipsisi", "Süpermen hekayələri"], 1),
      createQ("Elflər hansı əsərlərdə çox rast gəlinir?", ["Marvel komiksləri", "DC komiksləri", "Fantaziya romanları", "Qorxu hekayələri"], 2),
      createQ("\"Dune\" (Qumtepe) əsərinin müəllifi kimdir?", ["Isaac Asimov", "Frank Herbert", "Arthur C. Clarke", "Ray Bradbury"], 1),
      createQ("Draqonlar ən çox hansı janrda istifadə olunur?", ["Detektiv", "Fantaziya", "Romantika", "Tarixı roman"], 1),
      createQ("\"Aquaman\" hansı elementlə əlaqəlidir?", ["Od", "Su", "Torpaq", "Hava"], 1),
    ],
    medium: [
      createQ("\"The Hobbit\" və \"Üzüklərin Hökmdarı\" hansı kainatda cərəyan edir?", ["Narnia", "Middle-earth (Orta Dünya)", "Westeros", "Azeroth"], 1),
      createQ("Harry Potter-in valideynləri necə ölmüşlər?", ["Qəzada", "Xəstəlikdən", "Voldemort tərəfindən öldürülüblər", "Qocalıqdan"], 2),
      createQ("\"Foundation\" (Bünövrə) seriyasının müəllifi kimdir?", ["Arthur C. Clarke", "Isaac Asimov", "Robert Heinlein", "Philip K. Dick"], 1),
      createQ("\"A Song of Ice and Fire\" (Buz və Alov Nəğməsi) seriyasında neçə əsas ev var?", ["5", "7", "9", "12"], 1),
      createQ("Frodo Üzüyü hansı yerə aparmalı idi?", ["Rivendell", "Gondor", "Mordor", "Rohan"], 2),
      createQ("\"The Witcher\" seriyasının müəllifi kimdir?", ["George R.R. Martin", "Andrzej Sapkowski", "Terry Pratchett", "Brandon Sanderson"], 1),
      createQ("Marvel Cinematic Universe-də Infinity Stones neçədir?", ["4", "5", "6", "7"], 2),
      createQ("\"Blade Runner\" filmi hansı yazıçının əsərinə əsaslanır?", ["Isaac Asimov", "Arthur C. Clarke", "Philip K. Dick", "Ray Bradbury"], 2),
      createQ("\"1984\" distopiyasının müəllifi kimdir?", ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Margaret Atwood"], 1),
      createQ("Doctor Who serialında əsas personaj nə ilə səyahət edir?", ["Spaceship", "TARDIS", "DeLorean", "Millennium Falcon"], 1),
      createQ("\"Fahrenheit 451\" əsərində nə yandırılır?", ["Evlər", "Kitablar", "Pul", "Məktəblər"], 1),
      createQ("Thanos hansı əşyanı toplamaq istəyirdi?", ["Infinity Stones", "Horcruxes", "Dragon Balls", "Chaos Emeralds"], 0),
      createQ("\"Ender's Game\" əsərinin müəllifi kimdir?", ["Orson Scott Card", "Isaac Asimov", "Robert Heinlein", "Arthur C. Clarke"], 0),
      createQ("Geralt of Rivia (Witcher) hansı ölkədəndir?", ["Temeria", "Rivia", "Cintra", "Nilfgaard"], 1),
      createQ("\"Mad Max\" hansı post-apokaliptik dünyada cərəyan edir?", ["Zombi dünyası", "Nüvə müharibəsindən sonra", "Əcnəbi işğalından sonra", "Vərəm pandemiyasından sonra"], 1),
      createQ("Sauron hansı əsərdə əsas antagonistdir?", ["The Hobbit", "Üzüklərin Hökmdarı", "Narnia", "A və B"], 3),
      createQ("\"The Handmaid's Tale\" (Qarabaşın Nağılı) müəllifi kimdir?", ["Ursula K. Le Guin", "Margaret Atwood", "Octavia Butler", "N.K. Jemisin"], 1),
      createQ("Captain America-nın qalxanı hansı materialdan hazırlanıb?", ["Adamantium", "Titanium", "Vibranium", "Mithril"], 2),
      createQ("\"Dune\" əsərində ən qiymətli resurs nədir?", ["Su", "Spice (Ədviyyat)", "Qızıl", "Neft"], 1),
      createQ("Severus Snape hansı evə aid idi?", ["Gryffindor", "Hufflepuff", "Ravenclaw", "Slytherin"], 3),
      createQ("\"Stranger Things\" serialı hansı ildə başladı?", ["2014", "2015", "2016", "2017"], 2),
      createQ("Loki hansı planetdəndir?", ["Asgard", "Jotunheim", "Midgard", "Vanaheim"], 1),
      createQ("\"The Expanse\" hansı janrdadır?", ["Fantasy", "Qorxu", "Space opera (Kosmik opera)", "Steampunk"], 2),
      createQ("Dumbledore-un Patronusu hansı heyvandır?", ["Maral", "Phoenix", "Qartal", "Şir"], 1),
      createQ("\"Westworld\" serialı hansı mövzuya əsaslanır?", ["Zombilər", "Androidlər və süni intellekt", "Vampirlər", "Vaxt səyahəti"], 1),
      createQ("Aragorn-un başqa adı nədir?", ["Strider (Addımlayan)", "Ranger", "Elessar", "Hamısı"], 3),
      createQ("\"The Dark Tower\" seriyasının müəllifi kimdir?", ["Stephen King", "Dean Koontz", "Clive Barker", "H.P. Lovecraft"], 0),
      createQ("Black Widow-un əsl adı nədir?", ["Natasha Romanoff", "Maria Hill", "Peggy Carter", "Wanda Maximoff"], 0),
      createQ("\"Ready Player One\" əsərinin müəllifi kimdir?", ["Neal Stephenson", "Ernest Cline", "William Gibson", "Bruce Sterling"], 1),
      createQ("Gandalf necə növ varlıqdır?", ["İnsan", "Elf", "Maia (mələk)", "Sehrbaz"], 2),
    ],
    hard: [
      createQ("\"Neuromancer\" əsərinin müəllifi kimdir?", ["William Gibson", "Neal Stephenson", "Bruce Sterling", "Philip K. Dick"], 0),
      createQ("Tolkien-in Middle-earth əfsanəsində Valar neçə nəfərdir?", ["12", "14", "15", "17"], 2),
      createQ("\"Hyperion Cantos\" seriyasının müəllifi kimdir?", ["Iain M. Banks", "Dan Simmons", "Alastair Reynolds", "Peter F. Hamilton"], 1),
      createQ("Tolkien-in Quenya dili hansı dillərə əsaslanır?", ["Latın və Yunan", "Fin və Latın", "Kelt və Qədim İngilis", "Sanskrit və Yunan"], 1),
      createQ("\"The Left Hand of Darkness\" əsərinin müəllifi kimdir?", ["Ursula K. Le Guin", "Octavia Butler", "Lois McMaster Bujold", "C.J. Cherryh"], 0),
      createQ("Harry Potter-də \"Deathly Hallows\" (Ölüm Simvolları) neçə əşyadır?", ["2", "3", "4", "5"], 1),
      createQ("\"The Culture\" seriyasının müəllifi kimdir?", ["Alastair Reynolds", "Iain M. Banks", "Peter F. Hamilton", "Ken MacLeod"], 1),
      createQ("Silmarillion əsərində Morgoth-un əsl adı nədir?", ["Sauron", "Melkor", "Gothmog", "Ungoliant"], 1),
      createQ("\"Do Androids Dream of Electric Sheep?\" əsərinin müəllifi kimdir?", ["Isaac Asimov", "Arthur C. Clarke", "Philip K. Dick", "Robert Heinlein"], 2),
      createQ("Tolkien-in eposunda Silmaril daşları neçədir?", ["1", "2", "3", "7"], 2),
      createQ("\"The Broken Earth\" trilogiyasının müəllifi kimdir?", ["N.K. Jemisin", "Ann Leckie", "Kameron Hurley", "Nnedi Okorafor"], 0),
      createQ("Marvel Comics-də \"Beyonder\" hansı event-də əsas antagonist idi?", ["Infinity Gauntlet", "Secret Wars", "Civil War", "House of M"], 1),
      createQ("\"Ringworld\" əsərinin müəllifi kimdir?", ["Arthur C. Clarke", "Larry Niven", "Gregory Benford", "Greg Bear"], 1),
      createQ("Sandman (DC Comics) əsl adı ilə kimdir?", ["Daniel Hall", "Dream of the Endless", "Morpheus", "Hamısı doğrudur"], 3),
      createQ("\"The Stormlight Archive\" seriyasının müəllifi kimdir?", ["Patrick Rothfuss", "Brandon Sanderson", "Brent Weeks", "Brian McClellan"], 1),
      createQ("Isaac Asimov-un \"Robotlar Qanunları\" neçə maddədir?", ["2", "3", "4", "5"], 1),
      createQ("\"The Expanse\" seriyasının müəllifləri hansı təxəllüs altında yazırlar?", ["Robert Ludlum", "James S.A. Corey", "Richard Bachman", "Lemony Snicket"], 1),
      createQ("DC Comics-də \"Crisis on Infinite Earths\" hansı ildə dərc olundu?", ["1984-1985", "1985-1986", "1986-1987", "1987-1988"], 1),
      createQ("\"The Kingkiller Chronicle\" seriyasının müəllifi kimdir?", ["Brandon Sanderson", "Patrick Rothfuss", "Scott Lynch", "Joe Abercrombie"], 1),
      createQ("Middle-earth-də Elvish dillərin neçə əsas növü var?", ["2", "3", "4", "5"], 0),
      createQ("\"Snow Crash\" əsərinin müəllifi kimdir?", ["William Gibson", "Bruce Sterling", "Neal Stephenson", "Rudy Rucker"], 2),
      createQ("\"Malazan Book of the Fallen\" seriyasının müəllifi kimdir?", ["Steven Erikson", "Ian C. Esslemont", "Glen Cook", "R. Scott Bakker"], 0),
      createQ("DC Comics-də ilk Green Lantern kimdir?", ["Hal Jordan", "Alan Scott", "Guy Gardner", "John Stewart"], 1),
      createQ("\"The Three-Body Problem\" (Üç Bədən Problemi) müəllifi kimdir?", ["Liu Cixin", "Ken Liu", "Hao Jingfang", "Chen Qiufan"], 0),
      createQ("Tolkien-in Arda dünyasında Aman qitəsində hansı şəhər yerləşir?", ["Gondolin", "Tirion", "Minas Tirith", "Rivendell"], 1),
      createQ("\"The Wheel of Time\" seriyasında neçə kitab var?", ["12", "13", "14", "15"], 2),
      createQ("Marvel Comics-də \"The Watcher\" hansı adla tanınır?", ["Galactus", "Uatu", "Ego", "Eternity"], 1),
      createQ("\"A Canticle for Leibowitz\" əsərinin müəllifi kimdir?", ["Walter M. Miller Jr.", "Philip K. Dick", "Harlan Ellison", "Robert Silverberg"], 0),
      createQ("Harry Potter-də Nicolas Flamel neçə yaşında idi?", ["500", "600", "665", "750"], 2),
      createQ("\"The First Law\" trilogiyasının müəllifi kimdir?", ["Mark Lawrence", "Joe Abercrombie", "Brent Weeks", "Michael R. Fletcher"], 1),
    ]
  },
  INCESENET: {
    easy: [
      createQ("\"Mona Lisa\" əsərinin müəllifi kimdir?", ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], 1),
      createQ("Azərbaycanın milli rəssamı kimdir?", ["Sattar Bəhlulzadə", "Mir Mövsüm Nəvvab", "Tahir Salahov", "Tofiq Bəhramov"], 0),
      createQ("\"Leyli və Məcnun\" operasının bəstəkarı kimdir?", ["Qara Qarayev", "Fikrət Əmirov", "Üzeyir Hacıbəyov", "Niyazi"], 2),
      createQ("Vincent van Gogh hansı ölkədəndir?", ["Belçika", "Fransa", "Hollandiya", "Almaniya"], 2),
      createQ("\"Koroğlu\" operasının bəstəkarı kimdir?", ["Üzeyir Hacıbəyov", "Müslüm Maqomayev", "Qara Qarayev", "Fikrət Əmirov"], 0),
      createQ("Pablo Picasso hansı ölkədəndir?", ["İtaliya", "Fransa", "İspaniya", "Portuqaliya"], 2),
      createQ("\"Yeddi gözəl\" baleti hansı bəstəkarın əsəridir?", ["Üzeyir Hacıbəyov", "Qara Qarayev", "Fikrət Əmirov", "Niyazi"], 1),
      createQ("Klassik musiqinin atası kim sayılır?", ["Mozart", "Beethoven", "Johann Sebastian Bach", "Haydn"], 2),
      createQ("\"Qız qalası\" baleti hansı bəstəkarın əsəridir?", ["Qara Qarayev", "Fikrət Əmirov", "Arif Məlikov", "Niyazi"], 2),
      createQ("Bethovenin ən məşhur simfoniyası neçəncidir?", ["3-cü", "5-ci", "7-ci", "9-cu"], 3),
      createQ("\"Təzə gəlin\" tamaşasının müəllifi kimdir?", ["Hüseyn Cavid", "Mirzə Fətəli Axundzadə", "Cəfər Cabbarlı", "Üzeyir Hacıbəyov"], 2),
      createQ("Mozart hansı ölkədəndir?", ["Almaniya", "Avstriya", "İsveçrə", "Çexiya"], 1),
      createQ("\"Ərsəli və Qərəb\" tamaşasının müəllifi kimdir?", ["Mirzə Fətəli Axundzadə", "Hüseyn Cavid", "Cəfər Cabbarlı", "Əbdürrəhim bəy Haqverdiyev"], 3),
      createQ("İmpressionist rəssam kimdir?", ["Leonardo da Vinci", "Claude Monet", "Pablo Picasso", "Salvador Dali"], 1),
      createQ("Azərbaycan Dövlət Akademik Opera və Balet Teatrı nə vaxt açılmışdır?", ["1908", "1911", "1920", "1930"], 1),
      createQ("\"Füsunkar\" rəsm əsərinin müəllifi kimdir?", ["Sattar Bəhlulzadə", "Tahir Salahov", "Mir Mövsüm Nəvvab", "Tofiq Cavadov"], 0),
      createQ("Pyotr İlyiç Çaykovski hansı ölkədəndir?", ["Polşa", "Rusiya", "Ukrayna", "Belarusiya"], 1),
      createQ("\"Oqtay Eloğlu\" hansı sənət sahəsində məşhurdur?", ["Musiqi", "Rəssamlıq", "Teatr", "Heykəltəraşlıq"], 1),
      createQ("\"Haqqında düşündüyüm rəssam\" əsərinin müəllifi kimdir?", ["Tahir Salahov", "Mir Mövsüm Nəvvab", "Sattar Bəhlulzadə", "Tofiq Cavadov"], 0),
      createQ("Jazz musiqisinin atası kim sayılır?", ["Louis Armstrong", "Duke Ellington", "Charlie Parker", "Miles Davis"], 0),
      createQ("\"David\" heykəlinin müəllifi kimdir?", ["Leonardo da Vinci", "Donatello", "Michelangelo", "Raphael"], 2),
      createQ("Azərbaycanın ilk xalq artisti kim olmuşdur?", ["Bülbül", "Rəşid Behbudov", "Müslüm Maqomayev", "Seyid Şuşinski"], 0),
      createQ("\"Qaranlıq gecə\" tamaşasının müəllifi kimdir?", ["Cəfər Cabbarlı", "Hüseyn Cavid", "Səməd Vurğun", "Mirzə İbrahimov"], 1),
      createQ("Salvador Dali hansı cərəyanın nümayəndəsidir?", ["İmpressionism", "Kubizm", "Sürrealizm", "Realizm"], 2),
      createQ("\"Arşın mal alan\" operettasının müəllifi kimdir?", ["Qara Qarayev", "Üzeyir Hacıbəyov", "Fikrət Əmirov", "Müslüm Maqomayev"], 1),
      createQ("\"Son axşam yemək\" əsərinin müəllifi kimdir?", ["Michelangelo", "Leonardo da Vinci", "Raphael", "Titian"], 1),
      createQ("Rəşid Behbudov hansı sənət sahəsində məşhurdur?", ["Rəssamlıq", "Musiqi", "Heykəltəraşlıq", "Balet"], 1),
      createQ("\"Milyonçu\" tamaşasının müəllifi kimdir?", ["Mirzə Fətəli Axundzadə", "Cəfər Cabbarlı", "Hüseyn Cavid", "Səməd Vurğun"], 0),
      createQ("Frederic Chopin hansı aləti çalırdı?", ["Skripka", "Pianino", "Violonçel", "Fleyta"], 1),
      createQ("\"Azərbaycan mahnısı\" əsərinin müəllifi kimdir?", ["Fikrət Əmirov", "Niyazi", "Qara Qarayev", "Üzeyir Hacıbəyov"], 0),
    ],
    medium: [
      createQ("\"Gülüstan\" operasının bəstəkarı kimdir?", ["Üzeyir Hacıbəyov", "Fikrət Əmirov", "Qara Qarayev", "Niyazi"], 2),
      createQ("Michelangelo-nun Sikstin kapellasındakı freska əsəri nə vaxt tamamlanmışdır?", ["1508-1512", "1512-1516", "1516-1520", "1520-1524"], 0),
      createQ("\"Sənsiz\" mahnısının müəllifi kimdir?", ["Rəşid Behbudov", "Müslüm Maqomayev", "Polad Bülbüloğlu", "Bülbül"], 1),
      createQ("Rembrandt hansı əsrdə yaşamışdır?", ["XV əsr", "XVI əsr", "XVII əsr", "XVIII əsr"], 2),
      createQ("\"Sevil\" operasının bəstəkarı kimdir?", ["Qara Qarayev", "Fikrət Əmirov", "Üzeyir Hacıbəyov", "Niyazi"], 1),
      createQ("Antonio Vivaldi-nin ən məşhur əsəri hansıdır?", ["Dörd fəsil", "Requiem", "Messiah", "Water Music"], 0),
      createQ("\"Qaranquş\" tamaşasının müəllifi kimdir?", ["Cəfər Cabbarlı", "Hüseyn Cavid", "Səməd Vurğun", "Mirzə İbrahimov"], 2),
      createQ("Edvard Munch hansı ölkədəndir?", ["İsveç", "Danimarka", "Norveç", "Finlandiya"], 2),
      createQ("\"Nəsimi\" operasının bəstəkarı kimdir?", ["Soltan Hacıbəyov", "Ramiz Mustafayev", "Cavanşir Quliyev", "Həşim Həşimov"], 2),
      createQ("Gustav Klimt hansı cərəyanın nümayəndəsidir?", ["Art Nouveau", "Ekspressionism", "Kubizm", "Fauvizm"], 0),
      createQ("\"Min bir gecə\" baleti hansı bəstəkarın əsəridir?", ["Qara Qarayev", "Fikrət Əmirov", "Arif Məlikov", "Niyazi"], 2),
      createQ("Johannes Brahms hansı dövrdə yaşamışdır?", ["Barok", "Klassik", "Romantik", "Müasir"], 2),
      createQ("\"Nərgiz\" operasının bəstəkarı kimdir?", ["Müslüm Maqomayev", "Soltan Hacıbəyov", "Şəfiqə Axundova", "Həşim Həşimov"], 0),
      createQ("Diego Velazquez hansı ölkənin rəssamıdır?", ["İtaliya", "Fransa", "İspaniya", "Portuqaliya"], 2),
      createQ("\"Vətən\" simfoniyası kimə aiddir?", ["Qara Qarayev", "Fikrət Əmirov", "Niyazi", "Rauf Hacıyev"], 2),
      createQ("Henri Matisse hansı cərəyanın liderlərindən biridir?", ["Kubizm", "Fauvizm", "Dadaizm", "Sürrealizm"], 1),
      createQ("\"Aşıq Qərib\" operasının bəstəkarı kimdir?", ["Üzeyir Hacıbəyov", "Zülfüqar Hacıbəyov", "Qara Qarayev", "Fikrət Əmirov"], 1),
      createQ("Caravaggio hansı əsrdə yaşamışdır?", ["XV əsr", "XVI əsr", "XVI-XVII əsr", "XVII-XVIII əsr"], 2),
      createQ("\"Şur\" simfoniyası kimə aiddir?", ["Fikrət Əmirov", "Qara Qarayev", "Niyazi", "Rauf Hacıyev"], 0),
      createQ("Kazimir Malevich hansı cərəyanın banisidir?", ["Konstruktivizm", "Suprematizm", "Kubofuturizm", "Rayonizm"], 1),
      createQ("\"Nəsirəddin\" operasının bəstəkarı kimdir?", ["Ramiz Mustafayev", "Cavanşir Quliyev", "Soltan Hacıbəyov", "Niyazi"], 0),
      createQ("Georges Seurat hansı texnikadan istifadə edirdi?", ["İmpasto", "Pointilizm", "Sfumato", "Chiaroscuro"], 1),
      createQ("\"Nizami\" simfoniyası kimə aiddir?", ["Qara Qarayev", "Fikrət Əmirov", "Afrasiyab Bədəlbəyli", "Niyazi"], 2),
      createQ("Wassily Kandinsky hansı cərəyanın əsasını qoymuşdur?", ["Abstrakt sənət", "Ekspressionism", "Konstruktivizm", "Kubizm"], 0),
      createQ("\"Gəlin qayası\" baleti hansı bəstəkarın əsəridir?", ["Afrasiyab Bədəlbəyli", "Qara Qarayev", "Fikrət Əmirov", "Niyazi"], 0),
      createQ("Paul Cezanne hansı cərəyanın əsasını qoymuşdur?", ["İmpressionism", "Post-impressionism", "Kubizm", "Fauvizm"], 1),
      createQ("\"Azərbaycan kapriççiosu\" əsərinin müəllifi kimdir?", ["Qara Qarayev", "Niyazi", "Fikrət Əmirov", "Cavanşir Quliyev"], 1),
      createQ("Francisco Goya hansı ölkənin rəssamıdır?", ["İtaliya", "İspaniya", "Portuqaliya", "Fransa"], 1),
      createQ("\"Şah İsmayıl\" operasının bəstəkarı kimdir?", ["Müslüm Maqomayev", "Soltan Hacıbəyov", "Qara Qarayev", "Zülfüqar Hacıbəyov"], 0),
      createQ("Arnold Schönberg hansı musiqi sistemini yaratmışdır?", ["Serializm", "Minimalizm", "Aleatorika", "Dodekafon"], 3),
    ],
    hard: [
      createQ("\"Doktor Faustus\" kantatasının bəstəkarı kimdir?", ["Igor Stravinski", "Arnold Schönberg", "Alban Berg", "Anton Webern"], 1),
      createQ("Hieronymus Bosch hansı əsrdə yaşamışdır?", ["XIV əsr", "XV əsr", "XV-XVI əsr", "XVI əsr"], 2),
      createQ("\"Qarabağ şikəstəsi\" əsərinin müəllifi kimdir?", ["Qara Qarayev", "Fikrət Əmirov", "Üzeyir Hacıbəyov", "Niyazi"], 2),
      createQ("El Greco (Domenikos Theotokopoulos) hansı ölkədə yaşamış və yaratmışdır?", ["İtaliya", "İspaniya", "Yunanıstan", "Portuqaliya"], 1),
      createQ("\"Don Kixot\" simfoniyası kimə aiddir?", ["Richard Strauss", "Gustav Mahler", "Anton Bruckner", "Max Reger"], 0),
      createQ("Piet Mondrian hansı cərəyanın banisidir?", ["Konstruktivizm", "De Stijl", "Bauhaus", "Suprematizm"], 1),
      createQ("\"Yol nəğməsi\" simfoniyası kimə aiddir?", ["Dmitri Şostakoviç", "Sergey Prokofyev", "Aram Xaçaturyan", "Qara Qarayev"], 3),
      createQ("Tintoretto (Jacopo Robusti) hansı məktəbə aiddir?", ["Florensiya məktəbi", "Venesiya məktəbi", "Roma məktəbi", "Lombard məktəbi"], 1),
      createQ("Olivier Messiaen hansı alət üçün ən çox əsər yazmışdır?", ["Orqan", "Pianino", "Skripka", "Fleyta"], 0),
      createQ("Giotto di Bondone hansı cərəyanın əsasını qoymuşdur?", ["Qotika", "Barok", "Renessans", "Proto-Renessans"], 3),
      createQ("\"Leyli və Məcnun\" simfoniyasının müəllifi kimdir?", ["Qara Qarayev", "Fikrət Əmirov", "Arif Məlikov", "Niyazi"], 0),
      createQ("Albrecht Dürer hansı ölkənin rəssamıdır?", ["Hollandiya", "Almaniya", "Avstriya", "İsveçrə"], 1),
      createQ("Dmitri Şostakoviçin \"Leninqrad\" simfoniyası neçəncidir?", ["5-ci", "7-ci", "9-ci", "11-ci"], 1),
      createQ("Andrea Mantegna hansı məktəbə aiddir?", ["Venesiya", "Florensiya", "Padua", "Ferrara"], 2),
      createQ("\"Poema haqqında vurulan atlet\" əsərinin müəllifi kimdir?", ["Qara Qarayev", "Fikrət Əmirov", "Arif Məlikov", "Səid Rüstəmov"], 0),
      createQ("Jan van Eyck hansı texnikanı təkmilləşdirmişdir?", ["Freska", "Yağlı boya", "Tempera", "Akril"], 1),
      createQ("Benjamin Britten \"War Requiem\" əsərini hansı ildə yazmışdır?", ["1960", "1961", "1962", "1963"], 2),
      createQ("Sandro Botticelli \"Veneranın doğuluşu\" əsərini hansı texnika ilə yaratmışdır?", ["Freska", "Tempera", "Yağlı boya", "Mozaika"], 1),
      createQ("\"Rus\" triptixinin müəllifi kimdir?", ["Qara Qarayev", "Fikrət Əmirov", "Niyazi", "Səid Rüstəmov"], 3),
      createQ("Matthias Grünewald \"İsenheim altarı\" əsərini hansı ildə yaratmışdır?", ["1506-1515", "1510-1515", "1512-1516", "1515-1520"], 2),
      createQ("Krzysztof Penderecki \"Hiroşima qurbanlarının xatirəsinə treniya\" əsərini hansı ildə yazmışdır?", ["1958", "1959", "1960", "1961"], 2),
      createQ("Paolo Uccello hansı texnikadan istifadə edən ilk rəssamlardandır?", ["Sfumato", "Perspektiv", "Chiaroscuro", "İmpasto"], 1),
      createQ("\"Simarq\" simfoniyası kimə aiddir?", ["Rauf Hacıyev", "Firəngiz Əlizadə", "Fərəc Qarayev", "Vasif Adıgözəlov"], 1),
      createQ("Pieter Bruegel the Elder hansı ölkənin rəssamıdır?", ["Hollandiya", "Belçika", "Flamand (Hollandiya-Belçika)", "Almaniya"], 2),
      createQ("Karlheinz Stockhausen \"Gesang der Jünglinge\" əsərində hansı texnikadan istifadə etmişdir?", ["Serializm", "Elektron musiqi", "Minimalizm", "Aleatorika"], 1),
      createQ("Masaccio \"Müqəddəs Üçlük\" freskasını hansı kilsədə yaratmışdır?", ["Santa Maria Novella", "Santa Croce", "San Lorenzo", "Santa Maria del Carmine"], 0),
      createQ("\"Don Carlos\" operasının bəstəkarı kimdir?", ["Richard Wagner", "Giuseppe Verdi", "Giacomo Puccini", "Gioachino Rossini"], 1),
      createQ("Artemisia Gentileschi hansı cərəyanın nümayəndəsidir?", ["Renessans", "Barok (Caravaggism)", "Rokoko", "Neoklassisizm"], 1),
      createQ("György Ligeti \"Atmosphères\" əsərini hansı ildə yazmışdır?", ["1958", "1959", "1961", "1963"], 2),
      createQ("Titian \"Assunta\" (Məryəmin göyə qalxması) əsərini hansı şəhərdə yaratmışdır?", ["Roma", "Florensiya", "Venesiya", "Milan"], 2),
    ]
  },
  FILM: {
    easy: [
      createQ("\"Titanic\" filminin rejissoru kimdir?", ["Steven Spielberg", "James Cameron", "Martin Scorsese", "Christopher Nolan"], 1),
      createQ("\"Arşın mal alan\" filmi hansı ildə çəkilmişdir?", ["1945", "1955", "1965", "1975"], 2),
      createQ("\"Godfather\" (Xaç ata) filminin rejissoru kimdir?", ["Martin Scorsese", "Francis Ford Coppola", "Brian De Palma", "Sidney Lumet"], 1),
      createQ("\"O olmasın, bu olsun\" filmində baş rolu kim oynayıb?", ["Həsənağa Turabov", "Məmməd Səfa", "Əliqulu Səmədov", "Lutfəli Abdullayev"], 0),
      createQ("\"Avatar\" filminin rejissoru kimdir?", ["Peter Jackson", "James Cameron", "Ridley Scott", "Denis Villeneuve"], 1),
      createQ("\"Babək\" filmi hansı ildə çəkilmişdir?", ["1975", "1979", "1982", "1985"], 2),
      createQ("\"Star Wars\" (Ulduz Müharibələri) seriyasının yaradıcısı kimdir?", ["Steven Spielberg", "George Lucas", "James Cameron", "Ridley Scott"], 1),
      createQ("\"Əli və Nino\" filminin rejissoru kimdir?", ["Asif Rüstəmov", "Eldar Quliyev", "Rəşid Behbudov", "İlham Quliyev"], 0),
      createQ("\"Jurassic Park\" filminin rejissoru kimdir?", ["James Cameron", "Steven Spielberg", "George Lucas", "Robert Zemeckis"], 1),
      createQ("\"Dədə Qorqud\" filmi hansı ildə çəkilmişdir?", ["1973", "1975", "1977", "1979"], 0),
      createQ("\"Forrest Gump\" filmində baş rolu kim oynayıb?", ["Brad Pitt", "Tom Hanks", "Tom Cruise", "Leonardo DiCaprio"], 1),
      createQ("\"Koroğlu\" filmi hansı ildə çəkilmişdir?", ["1958", "1960", "1962", "1964"], 0),
      createQ("\"Inception\" filminin rejissoru kimdir?", ["Denis Villeneuve", "Christopher Nolan", "Darren Aronofsky", "Danny Boyle"], 1),
      createQ("\"Telefon\" filmi hansı ildə çəkilmişdir?", ["1985", "1988", "1991", "1994"], 1),
      createQ("\"The Shawshank Redemption\" filminin rejissoru kimdir?", ["Frank Darabont", "Rob Reiner", "Sydney Pollack", "Norman Jewison"], 0),
      createQ("\"Qanun naminə\" filmi hansı ildə çəkilmişdir?", ["1965", "1968", "1970", "1972"], 1),
      createQ("\"The Lion King\" (Şir Şah) hansı studiya tərəfindən hazırlanıb?", ["Pixar", "DreamWorks", "Disney", "Warner Bros"], 2),
      createQ("\"Bizim Cəbrayıl\" filmi hansı ildə çəkilmişdir?", ["1976", "1978", "1980", "1982"], 2),
      createQ("\"Pulp Fiction\" filminin rejissoru kimdir?", ["Quentin Tarantino", "Martin Scorsese", "Oliver Stone", "David Lynch"], 0),
      createQ("\"Xəzər nəğməsi\" filmi hansı ildə çəkilmişdir?", ["1945", "1948", "1952", "1955"], 0),
      createQ("\"The Dark Knight\" filmində Batman rolunu kim oynayıb?", ["Michael Keaton", "Val Kilmer", "Christian Bale", "Ben Affleck"], 2),
      createQ("\"Dağlarda döyüş\" filmi hansı ildə çəkilmişdir?", ["1964", "1966", "1968", "1970"], 1),
      createQ("\"Matrix\" filmində Neo rolunu kim oynayıb?", ["Brad Pitt", "Keanu Reeves", "Tom Cruise", "Will Smith"], 1),
      createQ("\"İstintaq davam edir\" filmi hansı ildə çəkilmişdir?", ["1960", "1962", "1964", "1966"], 3),
      createQ("\"Pirates of the Caribbean\" seriyasında Jack Sparrow rolunu kim oynayıb?", ["Orlando Bloom", "Johnny Depp", "Geoffrey Rush", "Javier Bardem"], 1),
      createQ("\"Oqtay Eloğlu\" sənədli filmi hansı ildə çəkilmişdir?", ["1980", "1983", "1985", "1987"], 2),
      createQ("\"Lord of the Rings\" (Üzüklərin Hökmdarı) trilogiyasının rejissoru kimdir?", ["Guillermo del Toro", "Peter Jackson", "Sam Raimi", "Ridley Scott"], 1),
      createQ("\"Şəhərdə günorta vaxtı\" filmi hansı ildə çəkilmişdir?", ["1961", "1962", "1963", "1964"], 0),
      createQ("\"Iron Man\" rolunu kim oynayıb?", ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], 2),
      createQ("\"Uzaq sahillərdə\" filmi hansı ildə çəkilmişdir?", ["1956", "1958", "1960", "1962"], 0),
    ],
    medium: [
      createQ("\"Schindler's List\" filmində Oskar Schindler rolunu kim oynayıb?", ["Tom Hanks", "Liam Neeson", "Anthony Hopkins", "Russell Crowe"], 1),
      createQ("\"Qoca dairəçi\" filmi hansı ildə çəkilmişdir?", ["1973", "1975", "1977", "1979"], 0),
      createQ("\"2001: A Space Odyssey\" filminin rejissoru kimdir?", ["Ridley Scott", "Stanley Kubrick", "Steven Spielberg", "George Lucas"], 1),
      createQ("\"Taleyə pəncə vuran\" filminin rejissoru kimdir?", ["Tofiq Tağızadə", "Həsən Seyidbəyli", "Ələsgər Əlakbərov", "Əlisəttər Atakişiyev"], 0),
      createQ("\"Citizen Kane\" filmi hansı ildə çəkilmişdir?", ["1939", "1941", "1943", "1945"], 1),
      createQ("\"Səhər naminə\" filmi hansı ildə çəkilmişdir?", ["1967", "1970", "1973", "1976"], 0),
      createQ("\"Casablanca\" filmində Rick rolunu kim oynayıb?", ["Gary Cooper", "Humphrey Bogart", "James Stewart", "Cary Grant"], 1),
      createQ("\"Ağ-qara\" filminin rejissoru kimdir?", ["Rza Tahmasib", "Kamran Şahtaxtinskiy", "Eldar Quliyev", "Rasim Ocaqov"], 3),
      createQ("\"Apocalypse Now\" filminin rejissoru kimdir?", ["Oliver Stone", "Francis Ford Coppola", "Stanley Kubrick", "Michael Cimino"], 1),
      createQ("\"Axırıncı aşırım\" filmi hansı ildə çəkilmişdir?", ["1966", "1968", "1970", "1971"], 3),
      createQ("\"The Silence of the Lambs\" filmində Hannibal Lecter rolunu kim oynayıb?", ["Anthony Hopkins", "Gary Oldman", "Robert De Niro", "Jack Nicholson"], 0),
      createQ("\"Yaşıl qəsr əsirləri\" filmi hansı ildə çəkilmişdir?", ["1969", "1970", "1971", "1972"], 2),
      createQ("\"Gladiator\" filminin rejissoru kimdir?", ["Oliver Stone", "Ridley Scott", "Tony Scott", "Michael Mann"], 1),
      createQ("\"Sarı yazma\" filmi hansı ildə çəkilmişdir?", ["1968", "1969", "1970", "1971"], 0),
      createQ("\"The Departed\" filminin rejissoru kimdir?", ["Quentin Tarantino", "Martin Scorsese", "Michael Mann", "Brian De Palma"], 1),
      createQ("\"Dəniz küləyi\" filmi hansı ildə çəkilmişdir?", ["1974", "1976", "1978", "1980"], 0),
      createQ("\"Fight Club\" filminin rejissoru kimdir?", ["Danny Boyle", "David Fincher", "Darren Aronofsky", "Paul Thomas Anderson"], 1),
      createQ("\"Yaramaz\" filmi hansı ildə çəkilmişdir?", ["1978", "1980", "1982", "1984"], 2),
      createQ("\"Seven Samurai\" (Yeddi Samuray) filminin rejissoru kimdir?", ["Yasujirō Ozu", "Akira Kurosawa", "Kenji Mizoguchi", "Masaki Kobayashi"], 1),
      createQ("\"Xatirə\" filmi hansı ildə çəkilmişdir?", ["1975", "1978", "1981", "1984"], 0),
      createQ("\"Blade Runner\" filmi hansı ildə çəkilmişdir?", ["1980", "1981", "1982", "1983"], 2),
      createQ("\"Qorxma, mən səninləyəm\" filmi hansı ildə çəkilmişdir?", ["1978", "1979", "1980", "1981"], 3),
      createQ("\"No Country for Old Men\" filminin rejissorları kimlərdir?", ["Coen Brothers (Qardaşlar Koen)", "Wachowski Brothers", "Russo Brothers", "Farrelly Brothers"], 0),
      createQ("\"Təhminə\" filmi hansı ildə çəkilmişdir?", ["1990", "1993", "1995", "1997"], 1),
      createQ("\"La La Land\" filminin rejissoru kimdir?", ["Damien Chazelle", "Ryan Gosling", "Denis Villeneuve", "Christopher Nolan"], 0),
      createQ("\"Həsrət\" filmi hansı ildə çəkilmişdir?", ["1972", "1974", "1976", "1978"], 1),
      createQ("\"Parasite\" (Parazit) filmi hansı ölkədə çəkilib?", ["Çin", "Yaponiya", "Cənubi Koreya", "Tayvan"], 2),
      createQ("\"Böyük dayaq\" filmi hansı ildə çəkilmişdir?", ["1962", "1963", "1964", "1965"], 2),
      createQ("\"The Grand Budapest Hotel\" filminin rejissoru kimdir?", ["Wes Anderson", "Paul Thomas Anderson", "Quentin Tarantino", "Edgar Wright"], 0),
      createQ("\"Ölülər xiyabanı\" filmi hansı ildə çəkilmişdir?", ["1987", "1989", "1991", "1993"], 0),
    ],
    hard: [
      createQ("\"Rashomon\" filmi hansı ildə çəkilmişdir?", ["1948", "1950", "1952", "1954"], 1),
      createQ("\"Məşədi İbad 94\" filmi hansı ildə çəkilmişdir?", ["1978", "1980", "1982", "1984"], 1),
      createQ("\"8½\" filminin rejissoru kimdir?", ["Michelangelo Antonioni", "Federico Fellini", "Luchino Visconti", "Vittorio De Sica"], 1),
      createQ("\"Qızıl körpü\" filmi hansı ildə çəkilmişdir?", ["1983", "1985", "1987", "1989"], 0),
      createQ("\"The Seventh Seal\" (Yeddinci möhür) filminin rejissoru kimdir?", ["Ingmar Bergman", "Carl Theodor Dreyer", "Lars von Trier", "Roy Andersson"], 0),
      createQ("\"İki sahil arasında\" filmi hansı ildə çəkilmişdir?", ["1976", "1978", "1980", "1982"], 1),
      createQ("\"Bicycle Thieves\" (Velosiped oğruları) filmi hansı ildə çəkilmişdir?", ["1946", "1948", "1950", "1952"], 1),
      createQ("\"Anadan olmamışdan qabaq\" filmi hansı ildə çəkilmişdir?", ["1968", "1970", "1972", "1974"], 3),
      createQ("\"Stalker\" filminin rejissoru kimdir?", ["Sergei Eisenstein", "Andrei Tarkovsky", "Dziga Vertov", "Alexander Dovzhenko"], 1),
      createQ("\"Əlavə təsir\" filmi hansı ildə çəkilmişdir?", ["1980", "1982", "1984", "1986"], 3),
      createQ("\"Battleship Potemkin\" filmi hansı ildə çəkilmişdir?", ["1923", "1925", "1927", "1929"], 1),
      createQ("\"Qara qayalar\" filmi hansı ildə çəkilmişdir?", ["1969", "1970", "1971", "1972"], 3),
      createQ("\"Tokyo Story\" filminin rejissoru kimdir?", ["Akira Kurosawa", "Yasujirō Ozu", "Kenji Mizoguchi", "Mikio Naruse"], 1),
      createQ("\"Sənsiz\" filmi hansı ildə çəkilmişdir?", ["1976", "1978", "1980", "1982"], 2),
      createQ("\"Persona\" filminin rejissoru kimdir?", ["Ingmar Bergman", "Andrei Tarkovsky", "Lars von Trier", "Carl Theodor Dreyer"], 0),
      createQ("\"Qatir Məmməd\" filmi hansı ildə çəkilmişdir?", ["1972", "1974", "1976", "1978"], 3),
      createQ("\"L'Avventura\" filminin rejissoru kimdir?", ["Federico Fellini", "Michelangelo Antonioni", "Pier Paolo Pasolini", "Bernardo Bertolucci"], 1),
      createQ("\"Ailəm\" filmi hansı ildə çəkilmişdir?", ["1993", "1995", "1997", "1999"], 0),
      createQ("\"Mirror\" (Güzgü) filmi hansı ildə çəkilmişdir?", ["1973", "1975", "1977", "1979"], 1),
      createQ("\"İtirdiyim yol\" filmi hansı ildə çəkilmişdir?", ["1975", "1976", "1977", "1978"], 2),
      createQ("\"Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles\" filminin rejissoru kimdir?", ["Agnès Varda", "Chantal Akerman", "Claire Denis", "Marguerite Duras"], 1),
      createQ("\"Qocalıq\" filmi hansı ildə çəkilmişdir?", ["1978", "1980", "1982", "1984"], 1),
      createQ("\"Au Hasard Balthazar\" filminin rejissoru kimdir?", ["Jean-Luc Godard", "François Truffaut", "Robert Bresson", "Eric Rohmer"], 2),
      createQ("\"Həyat nağılı\" filmi hansı ildə çəkilmişdir?", ["1991", "1993", "1995", "1997"], 0),
      createQ("\"Late Spring\" (Gec yaz) filmi hansı ildə çəkilmişdir?", ["1947", "1949", "1951", "1953"], 1),
      createQ("\"Tapdığım ovçu\" filmi hansı ildə çəkilmişdir?", ["1976", "1978", "1980", "1982"], 0),
      createQ("\"Sansho the Bailiff\" filminin rejissoru kimdir?", ["Akira Kurosawa", "Kenji Mizoguchi", "Yasujirō Ozu", "Masaki Kobayashi"], 1),
      createQ("\"Yarım ölüm\" filmi hansı ildə çəkilmişdir?", ["1984", "1986", "1988", "1990"], 2),
      createQ("\"Pather Panchali\" (Panther Pançali) filminin rejissoru kimdir?", ["Satyajit Ray", "Ritwik Ghatak", "Mrinal Sen", "Bimal Roy"], 0),
      createQ("\"Dördüncü adam\" filmi hansı ildə çəkilmişdir?", ["1982", "1984", "1986", "1988"], 0),
    ]
  },
  // --- PLACEHOLDERS FOR OTHER TOPICS TO PREVENT ERRORS ---
  TEXNOLOGIYA: {
    easy: [
      createQ("WWW nəyin qısaltmasıdır?", ["World Wide Web", "World Web Wide", "Wide World Web", "Web World Wide"], 0),
      createQ("Kompüterin beyni nədir?", ["RAM", "CPU", "HDD", "SSD"], 1),
      createQ("Apple şirkətinin qurucusu kimdir?", ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"], 1),
      createQ("Wi-Fi nədir?", ["Simsiz internet", "Simli internet", "Bluetooth", "Radio"], 0),
      createQ("PDF nəyin qısaltmasıdır?", ["Portable Document Format", "Personal Document File", "Public Data File", "Print Document File"], 0)
    ],
    medium: [
      createQ("İlk proqramçı kim sayılır?", ["Ada Lovelace", "Alan Turing", "Charles Babbage", "Grace Hopper"], 0),
      createQ("Python proqramlaşdırma dili nə vaxt yaranıb?", ["1989", "1991", "1995", "2000"], 1),
      createQ("Linux əməliyyat sisteminin yaradıcısı kimdir?", ["Linus Torvalds", "Steve Wozniak", "Dennis Ritchie", "Ken Thompson"], 0),
      createQ("RAM nəyin qısaltmasıdır?", ["Read Access Memory", "Random Access Memory", "Run Access Memory", "Read All Memory"], 1),
      createQ("HTTP nə deməkdir?", ["HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperText Transmission Protocol", "Hyper Transfer Text Protocol"], 0)
    ],
    hard: [
      createQ("İlk elektron kompüter hansıdır?", ["ENIAC", "UNIVAC", "EDSAC", "Colossus"], 0),
      createQ("Bitcoin-in yaradıcısı kimdir (ləqəb)?", ["Satoshi Nakamoto", "Vitalik Buterin", "Charlie Lee", "Nick Szabo"], 0),
      createQ("C++ dili kim tərəfindən yaradılıb?", ["Bjarne Stroustrup", "James Gosling", "Guido van Rossum", "Brendan Eich"], 0),
      createQ("TCP/IP protokolunu kimlər yaradıb?", ["Vint Cerf və Bob Kahn", "Tim Berners-Lee", "Marc Andreessen", "Ray Tomlinson"], 0),
      createQ("Süni intellekt termini ilk dəfə nə vaxt işlənib?", ["1950", "1956", "1960", "1965"], 1)
    ]
  },
  IDMAN: {
    easy: [
      createQ("Futbol komandasında neçə oyunçu olur?", ["9", "10", "11", "12"], 2),
      createQ("Olimpiya halqaları neçə rəngdədir?", ["4", "5", "6", "7"], 1),
      createQ("Basketbol topu hansı rəngdədir?", ["Ağ", "Qara", "Narıncı", "Sarı"], 2),
      createQ("Tennis oyununda xallar necə hesablanır?", ["1, 2, 3", "10, 20, 30", "15, 30, 40", "5, 10, 15"], 2),
      createQ("Dünya çempionatı neçə ildən bir keçirilir?", ["2", "3", "4", "5"], 2)
    ],
    medium: [
      createQ("İlk Olimpiya oyunları harada keçirilib?", ["Roma", "Afina", "Paris", "London"], 1),
      createQ("Boks rinqi hansı formadadır?", ["Dairəvi", "Üçbucaqlı", "Kvadrat", "Altıbucaqlı"], 2),
      createQ("Marafon qaçışının məsafəsi nə qədərdir?", ["40 km", "42.195 km", "45 km", "50 km"], 1),
      createQ("NBA hansı idman növünə aiddir?", ["Futbol", "Basketbol", "Tennis", "Voleybol"], 1),
      createQ("Formula 1 yarışında ən sürətli dövrəyə nə deyilir?", ["Pole position", "Fastest lap", "Pit stop", "Grand Slam"], 1)
    ],
    hard: [
      createQ("Futbol üzrə ilk dünya çempionatı hansı ildə keçirilib?", ["1924", "1928", "1930", "1934"], 2),
      createQ("Maykl Felps cəmi neçə Olimpiya qızıl medalı qazanıb?", ["18", "21", "23", "28"], 2),
      createQ("Usain Bolt 100 metri neçə saniyəyə qaçıb (dünya rekordu)?", ["9.58", "9.63", "9.69", "9.72"], 0),
      createQ("Şahmatda neçə fiqur var (bir tərəf üçün)?", ["14", "15", "16", "18"], 2),
      createQ("Super Bowl hansı idman növünün final oyunudur?", ["Reqbi", "Amerika futbolu", "Beysbol", "Kriket"], 1)
    ]
  }
};

export const getQuestionsByTopic = (topicId: string, seenQuestions: string[]): Question[] => {
  const topicData = DB[topicId];
  if (!topicData) return [];

  // Helper to shuffle
  const shuffle = (array: any[]) => [...array].sort(() => 0.5 - Math.random());

  // Logic: 5 Easy, 5 Medium, 5 Hard
  // If a category has fewer than 5, we take what's available, but since we updated DB, it should be fine.
  // We prioritize questions not seen yet if possible, but for simplicity in this static set, we just shuffle all.
  
  const easy = shuffle(topicData.easy || []).slice(0, 5);
  const medium = shuffle(topicData.medium || []).slice(0, 5);
  const hard = shuffle(topicData.hard || []).slice(0, 5);

  const combined = [...easy, ...medium, ...hard].map((q, index) => ({
    ...q,
    id: index, // Assign a temporary ID
    topic: topicId,
    difficulty: index < 5 ? 'easy' : index < 10 ? 'medium' : 'hard'
  }));

  return combined;
};
