
import { Question, Topic, TopicInfo } from './types';
import { Globe, BookOpen, Palette, Moon, Rocket, Clapperboard, Cpu, Dumbbell } from 'lucide-react';

export const TOPICS: TopicInfo[] = [
  { 
    id: 'COGRAFIYA', 
    label: { az: 'Coğrafiya', en: 'Geography' }, 
    icon: 'Globe', 
    description: { az: 'Dünya ölkələri, paytaxtlar və təbiət', en: 'Countries, capitals, and nature' }, 
    color: 'blue' 
  },
  { 
    id: 'TARIX', 
    label: { az: 'Tarix', en: 'History' }, 
    icon: 'BookOpen', 
    description: { az: 'Azərbaycan və Dünya tarixi, hadisələr', en: 'World and local history, events' }, 
    color: 'amber' 
  },
  { 
    id: 'INCESENET', 
    label: { az: 'İncəsənət', en: 'Art' }, 
    icon: 'Palette', 
    description: { az: 'Rəsm, Musiqi, Ədəbiyyat və Memarlıq', en: 'Painting, Music, Literature, Architecture' }, 
    color: 'fuchsia' 
  },
  { 
    id: 'DIN', 
    label: { az: 'Din', en: 'Religion' }, 
    icon: 'Moon', 
    description: { az: 'İslam tarixi, Peyğəmbərlər və inanclar', en: 'Islamic history, Prophets, and beliefs' }, 
    color: 'emerald' 
  },
  { 
    id: 'FANTASTIK', 
    label: { az: 'Fantastik', en: 'Sci-Fi' }, 
    icon: 'Rocket', 
    description: { az: 'Elmi-fantastika, kosmos və gələcək', en: 'Sci-fi, space, and the future' }, 
    color: 'violet' 
  },
  { 
    id: 'FILM', 
    label: { az: 'Film', en: 'Movies' }, 
    icon: 'Clapperboard', 
    description: { az: 'Kino, aktyorlar və məşhur sitatlar', en: 'Cinema, actors, and famous quotes' }, 
    color: 'rose' 
  },
  { 
    id: 'TEXNOLOGIYA', 
    label: { az: 'Texnologiya', en: 'Technology' }, 
    icon: 'Cpu', 
    description: { az: 'Kompüterlər, İxtiralar və İT', en: 'Computers, Inventions, and IT' }, 
    color: 'cyan' 
  },
  { 
    id: 'IDMAN', 
    label: { az: 'İdman', en: 'Sports' }, 
    icon: 'Dumbbell', 
    description: { az: 'Futbol, Olimpiada və İdman növləri', en: 'Football, Olympics, and Sports' }, 
    color: 'orange' 
  },
];

// Helper to create questions (Defaults to 'az' language)
const createQ = (text: string, options: string[], correct: number, lang: 'az' | 'en' = 'az'): Omit<Question, 'id' | 'prize'> => ({
  text,
  options,
  correctAnswerIndex: correct,
  language: lang
});

// --- QUESTION DATABASE BY TOPIC ---
const DB: Record<string, { easy: any[], medium: any[], hard: any[] }> = {
  COGRAFIYA: {
    easy: [
      createQ("Dünyanın ən hündür dağı hansıdır?", ["Kançencaqna", "Kilimancaro", "Everest", "Mak-Kinli"], 2),
      createQ("Avropanın ən uzun çayı hansıdır?", ["Dunay", "Rona", "Volqa", "Reyn"], 2),
      createQ("Yaponiyanın paytaxtı hansı şəhərdir?", ["Seul", "Pekin", "Tokio", "Nyu-Dehli"], 2),
      createQ("Qitələrin ayrılmasını və hərəkətini izah edən nəzəriyyə nə adlanır?", ["İqlim dəyişikliyi", "Tektonik lövhələr nəzəriyyəsi", "Dəniz səviyyəsinin qalxması", "Yer kürəsinin fırlanması"], 1),
      createQ("Afrikanın ən böyük səhrası hansıdır?", ["Qobi", "Kalahari", "Böyük Viktoriya", "Saxara"], 3),
      createQ("Ekvator xətti hansı dərəcə paraleldən keçir?", ["90°", "0°", "45°", "180°"], 1),
      createQ("Avstraliyanın paytaxtı hansıdır?", ["Sidney", "Melburn", "Kanberra", "Pert"], 2),
      createQ("Dünyanın ən dərin gölü hansıdır?", ["Superior", "Baykal", "Xəzər", "Titan"], 1),
      createQ("Cənubi Amerikanın ən uzun dağ silsiləsi hansıdır?", ["Qayalı dağlar", "And dağları", "Himalay", "Alp dağları"], 1),
      createQ("Zaman fərqlərini müəyyən edən xətlər nə adlanır?", ["Paralellər", "Ekvator", "Meridianlar", "İzotermlər"], 2),
      createQ("Dünyanın ən böyük adası hansıdır?", ["Yeni Qvineya", "Madaqaskar", "Böyük Britaniya", "Qrenlandiya"], 3),
      createQ("Hansı okean \"Sakit\" adlanır?", ["Atlantik", "Hind", "Sakit", "Arktik"], 2),
      createQ("Braziliyanın rəsmi dili hansıdır?", ["İspan", "Portuqal", "İngilis", "Fransız"], 1),
      createQ("Avropa və Asiya qitələrini ayıran dağ silsiləsi hansıdır?", ["Alp", "Karpat", "Ural", "Apenin"], 2),
      createQ("Şimal Buzlu Okeanının ən böyük dənizi hansıdır?", ["Barens dənizi", "Çukot dənizi", "Ağ dənizi", "Qara dəniz"], 0),
      createQ("Coğrafi koordinatlar nəyin kəsişməsi ilə müəyyən edilir?", ["Dəniz və torpaq", "En dairəsi və uzunluq dairəsi", "İqlim zonaları", "Quru və su səthi"], 1),
      createQ("\"Beş Böyük Göl\" sistemi hansı iki qitədə yerləşir?", ["Avropa və Asiya", "Şimali Amerika və Cənubi Amerika", "Şimali Amerika və Avropa", "Şimali Amerika"], 3),
      createQ("\"Dünyanın damı\" adlandırılan yüksəklik haradadır?", ["And dağları", "Pamir yaylası", "Qayalı dağlar", "Tibet"], 1),
      createQ("Misir üçün həyati əhəmiyyətə malik çay hansıdır?", ["Konqo", "Amazon", "Nil", "Meqan"], 2),
      createQ("\"Günəşin batmadığı ölkə\" kimi tanınan ölkə hansıdır?", ["Kanada", "İspaniya", "Norveç", "İrlandiya"], 2),
    ],
    medium: [
      createQ("Böyük Sədd Rifi hansı ölkənin sahillərində yerləşir?", ["İndoneziya", "Fici", "Avstraliya", "Yeni Zelandiya"], 2),
      createQ("İqlim diaqramlarında qırmızı xətt adətən hansı göstəricini təmsil edir?", ["Küləyin sürəti", "Yağış miqdarı", "Temperatur", "Rütubət"], 2),
      createQ("Aral gölünün əsas qidalandırıcı çayları hansılardır?", ["Sırdərya və Amudərya", "Nil və Konqo", "İrtış və Ob", "Dunay və Dnestr"], 0),
      createQ("Şimali və Cənubi Amerika qitələrini birləşdirən zolaq necə adlanır?", ["Süveyş bərzəği", "Panama bərzəği", "Bering bərzəği", "Gibraltar boğazı"], 1),
      createQ("Avropanın ən aşağı nöqtəsi (dəniz səviyyəsinə görə) haradadır?", ["Kaspian Depressiyası (Xəzər ətrafı)", "Hollandiya sahilləri", "Ölü dəniz", "Böyük Britaniya"], 0),
      createQ("Havay adaları hansı okeanda yerləşir?", ["Atlantik", "Hind", "Sakit", "Arktik"], 2),
      createQ("Səhra ərazilərində müvəqqəti çay yataqları nə adlanır?", ["Fiyord", "Vadi", "Deltalar", "Atollar"], 1),
      createQ("Qırmızı dənizlə Aralıq dənizini birləşdirən süni kanal hansıdır?", ["Panama", "Kiel", "Süveyş", "Korint"], 2),
      createQ("Nəhəng quru parçalarının \"Pangea\" adı altında birləşməsi neçə il əvvəl baş vermişdir?", ["Təxminən 50 milyon il", "Təxminən 200-300 milyon il", "Təxminən 1 milyard il", "Təxminən 5000 il"], 1),
      createQ("\"Od Halqası\" (Ring of Fire) hansı okeanın ətrafındadır?", ["Atlantik", "Hind", "Sakit", "Arktik"], 2),
      createQ("Tundra və Tayqa hansı iqlim zonalarına xasdır?", ["Mülayim", "Subtropik", "Subarktik və mülayim", "Tropik"], 2),
      createQ("Coğrafiyada izobarlar nəyi göstərən xətlərdir?", ["Eyni hündürlük", "Eyni temperatur", "Eyni rütubət", "Eyni atmosfer təzyiqi"], 3),
      createQ("Yeni Zelandiyanın yerləşdiyi böyük coğrafi region necə adlanır?", ["Mikroneziya", "Polineziya", "Avstraliya", "Okeaniya"], 3),
      createQ("Böyük Kanyon hansı çayın fəaliyyəti nəticəsində yaranmışdır?", ["Missisipi", "Kolorado", "Rio Grande", "Yukon"], 1),
      createQ("Dünyanın ən çox əhaliyə malik ölkəsi hansıdır (2024)?", ["Çin", "Hindistan", "ABŞ", "İndoneziya"], 1),
      createQ("Quru materiklərinin ümumi sahəsi təqribən nə qədərdir?", ["70 milyon km²", "100 milyon km²", "150 milyon km²", "300 milyon km²"], 2),
      createQ("Okean suyunun duzluluğu hansı vahidlə ölçülür?", ["Faizi (%)", "Promille (‰)", "Millilitr (ml)", "Dərəcə (°C)"], 1),
      createQ("Türkiyənin ən hündür zirvəsi olan Ağrı dağı hansı tip vulkandır?", ["Qalxanvari vulkan", "Stratovulkan", "Monogenetik vulkan", "Çökəklik vulkanı"], 1),
      createQ("Dünyanın ən kiçik qitəsi hansıdır?", ["Avstraliya", "Antarktida", "Avropa", "Cənubi Amerika"], 0),
      createQ("Baykal gölü mənşəyinə görə necə bir göldür?", ["Buzlaq mənşəli", "Tektonik mənşəli", "Vulkanik mənşəli", "Axmaz göl"], 1),
    ],
    hard: [
      createQ("Afrikanın ən cənub nöqtəsi hansıdır?", ["Ümid burnu", "İynə burnu (Cape Agulhas)", "Yaşıl burun", "Horn burnu"], 1),
      createQ("Yer kürəsinin mərkəzinin (nüvə) təxmini temperaturu nə qədərdir?", ["1000 °C", "2500 °C", "4000-6000 °C", "10000 °C-dən çox"], 2),
      createQ("Qranit və bazalt hansı növ süxurlara aiddir?", ["Çökmə süxurlar", "Metamorfik süxurlar", "Maqmatik süxurlar", "Üzvi süxurlar"], 2),
      createQ("Şimal Buzlu Okeanında buzlaqların əriməsi ilə açılan nəqliyyat yolu hansıdır?", ["Qərb su yolu", "Şimal-Qərb keçidi", "Atlantik dəhlizi", "Süveyş alternativi"], 1),
      createQ("Dünyanın ən yüksək şəlaləsi olan Anqel şəlaləsi hansı ölkədədir?", ["Braziliya", "Venesuela", "Kanada", "Cənubi Afrika"], 1),
      createQ("Atlantik okeanının dibində formalaşan dağ silsiləsi necə adlanır?", ["Qayalı dağlar", "Mid-Atlantik silsiləsi", "Karpat silsiləsi", "Himalay silsiləsi"], 1),
      createQ("Yayı quraq və isti, qışı rütubətli və sərin olan iqlim tipi hansıdır?", ["Kontinental", "Monson", "Aralıq dənizi", "Ekvatorial"], 2),
      createQ("Dəniz səviyyəsinə görə eyni hündürlükdə olan nöqtələri birləşdirən xətlər?", ["İzobarlar", "İzotermlər", "İzoqonslar", "İzohipslər"], 3),
      createQ("Qondvana superqitəsinin parçalanmasından hansı qitələr yaranmışdır?", ["Şimali Amerika və Avropa", "Antarktida, Avstraliya, Cənubi Amerika, Afrika", "Asiya və Avropa", "Şimali Amerika və Asiya"], 1),
      createQ("Xəzər dənizinin ən dərin nöqtəsi hansı çökəklikdədir?", ["Şimali Xəzər", "Mərkəzi Xəzər", "Dərin Kaspian", "Cənubi Xəzər"], 3),
      createQ("Coğrafiyada meqapolis nə deməkdir?", ["Kiçik şəhərlər toplusu", "Milyonlarla sakini olan böyük şəhər", "Birləşmiş böyük şəhərlər toplusu", "Yalnız sənaye mərkəzləri"], 2),
      createQ("Azot və oksigen atmosferin təxminən neçə faizini təşkil edir?", ["50%", "70%", "90%", "99%"], 3),
      createQ("Cənubi Çin dənizi hansı okeanın tərkib hissəsidir?", ["Atlantik", "Sakit", "Hind", "Arktik"], 1),
      createQ("Təpəlik ərazilərdə torpağın yuyulmasının qarşısını alan üsul?", ["Dövri əkinçilik", "Teraslama", "Şumlama", "Rotasiya"], 1),
      createQ("Böyük Britaniyanın ən qədim geoloji massivlər necə adlanır?", ["Kaledonid", "Hersinid", "Qondevanid", "Alpine"], 0),
      createQ("Küləklərin istiqamətini dəyişən fırlanma qüvvəsi necə adlanır?", ["Maqnit qüvvəsi", "Cazibə qüvvəsi", "Fırlanma qüvvəsi", "Koriolis qüvvəsi"], 3),
      createQ("Quru ilə əhatə olunmuş ən böyük göl (su hövzəsi) hansıdır?", ["Superior", "Baykal", "Xəzər", "Böyük Duzlu göl"], 2),
      createQ("Dünya əhalisinin əsas hissəsi hansı yarımkürədədir?", ["Cənub", "Şimal", "Qərb", "Şərq"], 1),
      createQ("Cənub-Şərqi Asiyada məşhur olan və təkrar əkilən bitki?", ["Buğda", "Qəhvə", "Çəltik", "Pambıq"], 2),
      createQ("Geosinxron orbitdəki peyklər əsasən nə üçün istifadə olunur?", ["Hərbi", "Meteoroloji və Rabitə", "Elmi tədqiqat", "Mədən axtarışı"], 1),
    ]
  },
  TARIX: {
    easy: [
      createQ("Qədim Misirin hökmdarları hansı adla tanınırdılar?", ["İmperator", "Padşah", "Firon", "Kral"], 2),
      createQ("İkinci Dünya müharibəsi neçənci ildə başlamışdır?", ["1914", "1939", "1945", "1918"], 1),
      createQ("İlk insan Aya nə vaxt və hansı kosmik gəmi ilə ayaq basmışdır?", ["1965, Vostok 1", "1969, Apollon 11", "1971, Soyuz 4", "1981, Space Shuttle"], 1),
      createQ("Qədim Romada plebeylərə qarşı çıxan, məşhur qladiator üsyanına başçılıq edən kimdir?", ["Yuli Sezar", "Spartak", "Neron", "Mark Antoni"], 1),
      createQ("Böyük Çin Səddi hansı dövrdə və hansı məqsədlə tikilmişdir?", ["Orta əsrlər, karvan yollarını qorumaq", "Qədim dövr, şimal tayfalarının hücumlarından qorunmaq", "Yeni dövr, şəhərləri ayırmaq", "Müasir dövr, turistik məqsədlə"], 1),
      createQ("\"Kolumbiyanın kəşfi\" deyilən hadisə nə vaxt baş vermişdir?", ["1492", "1517", "1607", "1776"], 0),
      createQ("Fransız inqilabı hansı ildə başlamışdır?", ["1789", "1815", "1688", "1848"], 0),
      createQ("Azərbaycanın cənubunda Səfəvilər dövlətinin əsasını qoyan hökmdar kimdir?", ["Uzun Həsən", "Şah İsmayıl Xətai", "Nadir Şah Əfşar", "I Şah Abbas"], 1),
      createQ("Qədim Yunanıstanda demokratiyanın vətəni sayılan şəhər dövləti hansıdır?", ["Sparta", "Afina", "Korinf", "Teben"], 1),
      createQ("Birinci Dünya müharibəsində hansı ölkə \"Mərkəzi Güclər\" blokuna daxil idi?", ["Fransa", "Böyük Britaniya", "ABŞ", "Almaniya"], 3),
      createQ("Böyük İpək Yolunun əsas funksiyası nə idi?", ["Hərbi məlumat ötürülməsi", "Qitələrarası ticarət əlaqələri", "Dəniz səyahətləri", "Poçt xidməti"], 1),
      createQ("Rusiyada bolşevik inqilabı hansı ildə baş vermişdir?", ["1905", "1917", "1922", "1930"], 1),
      createQ("Türkiyə Respublikasının banisi və ilk prezidenti kimdir?", ["İsmət İnönü", "Mustafa Kamal Atatürk", "Süleyman Dəmirəl", "Tansu Çillər"], 1),
      createQ("Azərbaycan ərazisində yaranmış ən qədim dövlət qurumu hansıdır (Manna dövründən əvvəl)?", ["Atropatena", "Albaniya", "Midiya", "Kuti"], 3),
      createQ("Müasir tarixin başlanğıcı sayılan hadisələrdən biri hansıdır?", ["Sənaye İnqilabı", "Qədim Roma İmperiyasının süqutu", "Neolit İnqilabı", "Bizansın yaranması"], 0),
      createQ("İnsanlığın tarixdən əvvəlki dövrü necə adlanır?", ["Orta Əsrlər", "Antik dövr", "Tarixdən əvvəlki dövr (Prehistory)", "Yeni dövr"], 2),
      createQ("Xristianlığın rəsmi din olaraq qəbul edildiyi Roma İmperatoru kimdir (IV əsr)?", ["Avqust", "Trayan", "Konstantin", "Kaliqula"], 2),
      createQ("Bütün ərəb tayfalarını birləşdirən və İslam dövlətinin əsasını qoyan kimdir?", ["Ömər", "Osman", "Əbu Bəkr", "Məhəmməd peyğəmbər"], 3),
      createQ("\"Soyuq müharibə\" dövründə ABŞ-ın rəhbərlik etdiyi hərbi blok necə adlanırdı?", ["Varşava Müqaviləsi Təşkilatı", "NATO", "BMT", "SEATO"], 1),
      createQ("SSRİ neçənci ildə süqut etmişdir?", ["1985", "1989", "1991", "2000"], 2),
    ],
    medium: [
      createQ("Bizans İmperiyasının paytaxtı hansı şəhər idi (indiki adı nədir)?", ["Roma", "Afina", "Konstantinopol (İstanbul)", "İsgəndəriyyə"], 2),
      createQ("Yüzillik müharibə hansı iki ölkə arasında baş vermişdir?", ["Fransa və İspaniya", "İngiltərə və Fransa", "Almaniya və Rusiya", "İtaliya və Avstriya"], 1),
      createQ("Qədim Çində \"Səma Mandatı\" nəzəriyyəsi nəyi əsaslandırırdı?", ["Qadınların hüquqlarını", "İmperatorun hakimiyyətinin ilahi mənşəyini", "Ticarət yollarının açılmasını", "Kəndlilərin vergi azadlığını"], 1),
      createQ("Maqna Karta (Böyük Azadlıq Xartiyası) İngiltərədə Kral I İohanna neçənci ildə imzalatdırılmışdır?", ["1066", "1215", "1485", "1688"], 1),
      createQ("Reformasiya hərəkatının Avropada başlamasına səbəb olan alman ilahiyyatçısı kimdir?", ["Jan Kalvin", "Martin Lüter", "Tomas Mor", "Henri VIII"], 1),
      createQ("1959-cu ildə Kubada inqilaba rəhbərlik edən kimdir?", ["Fulxensio Batista", "Ernesto \"Çe\" Gevara", "Fidel Kastro", "Rafael Trujillo"], 2),
      createQ("Azərbaycanı işğal edən Rusiya imperiyası ilə İran arasında imzalanmış və Azərbaycanın iki yerə bölünməsini rəsmiləşdirən müqavilə hansıdır (1813)?", ["İstanbul", "Gülüstan", "Türkmənçay", "Ədirnə"], 1),
      createQ("Qədim Mesopotamiyada ilk qanunlar toplusu hansı hökmdara məxsusdur?", ["Navuxodonosor", "Aşşurbanipal", "Hammurapi", "Kir"], 2),
      createQ("\"Aydınlanma dövrü\" əsasən hansı əsrləri əhatə edir?", ["XV-XVI əsrlər", "XVII-XVIII əsrlər", "XIX əsr", "XX əsr"], 1),
      createQ("Osmanlı İmperiyasının süqutundan sonra Türkiyə Cümhuriyyətini quran müqavilə hansıdır (1923)?", ["Brest-Litovsk", "Lozanna", "Sevr", "Paris"], 1),
      createQ("Birinci Pun müharibəsi hansı ərazilər uğrunda baş vermişdir?", ["Yunanıstan", "Kiçik Asiya", "Siciliya və Aralıq dənizi", "Misir"], 2),
      createQ("Qanlı bazar hadisəsi Rusiyada hansı inqilabın başlanğıcı sayılır?", ["1905-1907-ci illər inqilabı", "Fevral inqilabı (1917)", "Oktyabr inqilabı (1917)", "1991-ci il çevrilişi"], 0),
      createQ("\"Azərbaycan Xalq Cümhuriyyəti\" (AXC) neçənci ildə elan edilmişdir?", ["1905", "1918", "1920", "1991"], 1),
      createQ("Hansı imperatorun dövründə Roma İmperiyası \"Pax Romana\" (Roma Sülhü) dövrünü yaşamışdır?", ["Neron", "Diokletian", "Avqust", "Kaliqula"], 2),
      createQ("ABŞ-ın Müstəqillik Bəyannaməsi hansı ildə qəbul edilmişdir?", ["1776", "1789", "1812", "1865"], 0),
      createQ("Macarıstan və Bolqarıstanın iştirak etdiyi İkinci Dünya müharibəsindəki hərbi blok necə adlanırdı?", ["Antanta", "Ox dövlətləri", "NATO", "Müttəfiqlər"], 1),
      createQ("Xəzəryanı ərazilərdə ərəblərə qarşı uzun müddət müqavimət göstərən dövlət hansıdır?", ["Xəzər Xaqanlığı", "Sasanilər", "Göytürklər", "Ağqoyunlular"], 0),
      createQ("Səlib yürüşləri əsasən hansı əraziyə yönəlmişdi?", ["İtaliya", "İspaniya", "Müqəddəs Torpaq (Yaxın Şərq)", "Almaniya"], 2),
      createQ("Rusiyanın \"Böyük Vətən Müharibəsi\" hansı illəri əhatə edir?", ["1914-1918", "1939-1945", "1941-1945", "1950-1953"], 2),
      createQ("İlk dəfə mətbəəni Avropada kəşf edən kimdir?", ["Leonardo da Vinçi", "Qalileo Qaliley", "İohann Qutenberq", "İsaak Nyuton"], 2),
    ],
    hard: [
      createQ("\"Otuz İllik Müharibəni\" (1618-1648) rəsmən sona çatdıran sülh müqaviləsi necə adlanır?", ["Rastatt sülhü", "Vestfaliya sülhü", "Utrext sülhü", "Paris sülhü"], 1),
      createQ("Çin tarixinə görə, hansı sülalənin hakimiyyəti dövründə Konfutsi təlimi rəsmi ideologiyaya çevrildi?", ["Çjou", "Han", "Tan", "Min"], 1),
      createQ("1898-ci ildə ABŞ-ın İspaniyadan ələ keçirdiyi əsas ərazilər (Kubadan başqa) hansılardır?", ["Alyaska və Havay", "Puerto Riko və Filippin", "Meksika və Kanada", "Vyetnam və Laos"], 1),
      createQ("Xəzər Xaqanlığının süqutunda əsas rol oynayan qədim rus knyazı kimdir?", ["İqor", "Oleq", "Svyatoslav", "Vladimir"], 2),
      createQ("Səfəvi-Osmanlı müharibələrinə son qoyan və Səfəvi dövlətinin süqutundan əvvəl imzalanmış sonuncu böyük müqavilə hansıdır (1736)?", ["Ərzurum", "Kirmanşah", "İstanbul", "Dərviş Sülhü"], 2),
      createQ("\"Qızıl Orda\" dövlətinin əsasını qoyan monqol sərkərdəsi kimdir?", ["Çingiz Xan", "Hülakü Xan", "Batı Xan", "Teymur"], 2),
      createQ("1947-ci ildə Hindistanın müstəqillik qazanmasından sonra ölkənin iki dövlətə bölünmə prosesi necə adlanır?", ["Birləşmə", "Partisiya (Bölünmə)", "Dezinteqrasiya", "Dekolonizasiya"], 1),
      createQ("Qədim İrandakı Zərdüştilik dininin müqəddəs kitabı necə adlanır?", ["İncil", "Tövrat", "Avesta", "Vedas"], 2),
      createQ("\"İslamın qızıl dövrü\" əsasən hansı xilafətin dövrünə təsadüf edir?", ["Rəşidi Xilafəti", "Əməvilər Xilafəti", "Abbasilər Xilafəti", "Osmanlı Xilafəti"], 2),
      createQ("Napoleon Bonapartın ilk sürgün edildiyi ada hansıdır?", ["Müqəddəs Yelena", "Elba", "Korsika", "Malta"], 1),
      createQ("1861-ci ildə ABŞ-da Vətəndaş müharibəsinə səbəb olan əsas amil nə idi?", ["Vergi siyasəti", "Ərazi mübahisələri", "Kölelik (quldarlıq) məsələsi", "Dini ziddiyyətlər"], 2),
      createQ("Bütün türk tayfalarını ilk dəfə vahid dövlət altında birləşdirən qədim imperiya hansıdır?", ["Hun İmperiyası", "Göytürk Xaqanlığı", "Uyğur Xaqanlığı", "Səlcuqlular İmperiyası"], 1),
      createQ("\"Soyuq müharibə\" dövrünün ən kritik məqamlarından biri olan və nüvə müharibəsi təhlükəsi yaradan böhran hansıdır (1962)?", ["Berlin böhranı", "Koreya müharibəsi", "Karib (Kuba) böhranı", "Süveyş böhranı"], 2),
      createQ("Böyük Britaniyada \"Şanlı İnqilab\" (Glorious Revolution) nə vaxt baş vermişdir?", ["1640", "1688", "1789", "1832"], 1),
      createQ("Qədim Roma tərəfindən dağıdılan və Hannibalın vətəni olan şəhər hansıdır?", ["İsgəndəriyyə", "Karfagen", "Afina", "Perqam"], 1),
      createQ("1937-1938-ci illərdə SSRİ-də Stalinin əsas siyasi rəqiblərini və ordu generallarını məhv etdiyi dövr necə adlanır?", ["Kollektivləşdirmə", "Yeni İqtisadi Siyasət", "Böyük Təmizləmə (Terror)", "Perestroyka"], 2),
      createQ("Monqol işğallarından sonra Yaxın Şərqdə Elxanilər dövlətinin (Hülakülər) paytaxtı hansı şəhər olmuşdur?", ["Bağdad", "Təbriz", "Marağa", "Şamaxı"], 1),
      createQ("Dünyanın ən qədim yazılı hüquq sistemi olan \"Hammurapi Qanunları\" hansı yazı ilə yazılmışdır?", ["Hiyeroqlif", "Ərəb", "Mixi (Küncvari) yazı", "Latın"], 2),
      createQ("Şimali və Cənubi Vyetnamı birləşdirən müharibə nə vaxt başa çatmışdır?", ["1954", "1968", "1975", "1989"], 2),
      createQ("Qədim Mayya sivilizasiyasının əsas yerləşdiyi region (indiki ölkə) haradır?", ["Peru", "Meksikanın cənubu və Mərkəzi Amerika", "Braziliya", "Misir"], 1),
    ]
  },
  INCESENET: {
    easy: [
      createQ("\"Mona Liza\" əsərinin müəllifi kimdir?", ["Vinsent van Qoq", "Pablo Pikasso", "Leonardo da Vinçi", "Klod Mone"], 2),
      createQ("Rənglərin qarışdırılması ilə yeni rənglərin yaradılması nə adlanır?", ["Perspektiv", "Kompozisiya", "Palitra", "Rəngarənglik"], 2),
      createQ("Qədim Yunan heykəltəraşlığında insan bədəninin ideal təsvirinə nə deyilirdi?", ["Amfora", "Qrot", "Kanon", "Freska"], 2),
      createQ("\"Ulduzlu gecə\" (The Starry Night) rəsmi hansı postimpressionist rəssama aiddir?", ["Pol Sezann", "Vinsent van Qoq", "Pol Qogen", "Edqar Deqa"], 1),
      createQ("\"Nəfəs almış\" (Qədim Roma heykəltəraşlığına görə) ən məşhur abidələrdən biri olan \"David\" heykəlinin müəllifi kimdir?", ["Donatello", "Rafael Santi", "Mikelancelo", "Cotto"], 2),
      createQ("Musiqidə yüksək və incə səsləri ifadə etmək üçün istifadə olunan açar nə adlanır?", ["Bas açarı", "Treble açarı (Skripka açarı)", "Tenor açarı", "Altd açarı"], 1),
      createQ("Teatrda tamaşa zamanı aktyorların geyindikləri geyimlər necə adlanır?", ["Dekorasiya", "Makiyaj", "Kostyum", "Rekvizit"], 2),
      createQ("Əsası yağlı boyalardan ibarət olan rəsm texnikası necə adlanır?", ["Akvarel", "Qouş", "Yağlı boya (Oyl)", "Pastel"], 2),
      createQ("Opera janrının vətəni hansı ölkə sayılır?", ["Fransa", "Almaniya", "İtaliya", "Böyük Britaniya"], 2),
      createQ("\"Impressionizm\" sənət cərəyanı əsasən hansı ölkədə yaranmışdır?", ["İtaliya", "İspaniya", "Fransa", "Almaniya"], 2),
      createQ("Bir heykəlin bütün tərəflərdən baxıla bilən, ətrafı boş formada hazırlanması necə adlanır?", ["Relyef", "Heykəl-portret", "Dairəvi heykəltəraşlıq", "Abidə"], 2),
      createQ("Memarlıqda binaların xarici və daxili divarlarını bəzəyən rəngli şüşə parçalarından ibarət əsər nə adlanır?", ["Freska", "Vitraj", "Mozaika", "Qobelen"], 1),
      createQ("Əsərdə işıq və kölgənin kəskin ziddiyyətindən istifadə edilməsi texnikası necə adlanır?", ["Sfumato", "Xiyaroskuro (İşıq-kölgə)", "Fovizm", "Puantilizm"], 1),
      createQ("Rəssamın özünü təsvir etdiyi əsər necə adlanır?", ["Portret", "Mənzərə", "Natiürmort", "Avtoportret"], 3),
      createQ("Klassik baletdə qadın rəqqasənin geyindiyi qısa, çoxqatlı ətək necə adlanır?", ["Kilt", "Tutu", "Sarafan", "Şanel"], 1),
      createQ("Məşhur sənət əsərlərinin saxlandığı Parisdəki əsas muzey hansıdır?", ["Ermitaj", "Metropoliten Muzeyi", "Luvr", "Prado Muzeyi"], 2),
      createQ("Əsas mövzusu cansız əşyalar (meyvələr, güllər, qablar) olan rəsm janrı nə adlanır?", ["Portret", "Mənzərə (Peysaj)", "Natiürmort", "Bataliya"], 2),
      createQ("Yazılı əsərləri səhnəyə çıxaran sənət növü necə adlanır?", ["Kino", "Rəqs", "Teatr", "Ədəbiyyat"], 2),
      createQ("\"Sürrealizm\" cərəyanının banilərindən biri sayılan və əsərlərində əriyən saatları təsvir edən rəssam kimdir?", ["Salvador Dali", "Rene Maqrit", "Endi Uorhol", "Klod Mone"], 0),
      createQ("Memarlıqda daş və ya kərpicdən hörülmüş yarımdairəvi tavan konstruksiyası nə adlanır?", ["Kolonna", "Arxitrav", "Tağ", "Pilyastr"], 2),
    ],
    medium: [
      createQ("\"Qışqırıq\" (The Scream) rəsm əsərinin norveçli müəllifi kimdir?", ["Edvard Munk", "Yan Vermeer", "Qustav Klimt", "Alfons Muxa"], 0),
      createQ("İtaliya Renessansının \"Üç Böyük Ustadı\" kimlərdir?", ["Botiçelli, Tisian, Donatello", "Leonardo da Vinçi, Mikelancelo, Rafael", "Cotto, Brunelleski, Mazakko", "Karavaco, Tintoretto, Dürer"], 1),
      createQ("Kubizm sənət cərəyanının əsas yaradıcılarından biri kimdir?", ["Anri Matiss", "Pablo Pikasso", "Pol Qogen", "Vinsent van Qoq"], 1),
      createQ("Məşhur \"Sistine Şapeli\"nin tavanını freskalarla bəzəyən rəssam kimdir?", ["Rafael", "Leonardo da Vinçi", "Mikelancelo", "Sandro Botiçelli"], 2),
      createQ("Barokko dövrünün ən görkəmli bəstəkarı və \"Fuğanın atası\" adlandırılan şəxs kimdir?", ["Volfqanq Amadey Motsart", "Lüdviq van Bethoven", "İohann Sebastyan Bax", "Frans List"], 2),
      createQ("Memarlıqda Qədim Yunan məbədlərində istifadə olunan üç əsas sütun (kolonna) sırası (ordosu) hansılardır?", ["Barokko, Qotik, Roman", "Toskana, Kompozit, Korinf", "Dorik, İonik, Korinf", "Klassik, Modern, Futuristik"], 2),
      createQ("Rəssamın rəngləri kətana qalın qatlarla tətbiq etdiyi, üçölçülü bir görünüş yaradan rəsm texnikası nə adlanır?", ["Sfumato", "Qrafit", "İmpasto", "Akvarel"], 2),
      createQ("İlk dəfə \"Qara Kvadrat\" əsəri ilə məşhurlaşan və \"Suprematizm\" cərəyanının banisi olan rus rəssamı kimdir?", ["Vasili Kandinski", "Kazimir Maleviç", "Aleksandr Rodçenko", "Mark Şaqal"], 1),
      createQ("Musiqidə bir notun müəyyən müddət ərzində səslənmə müddəti nə adlanır?", ["Tonal", "Ritm", "Melodiya", "Harmonika"], 1),
      createQ("\"Dəfinə\" (The Kiss) əsəri ilə tanınan və Vyanada Modernizm hərəkatının görkəmli nümayəndəsi olan rəssam kimdir?", ["Eqon Şiele", "Qustav Klimt", "Oskar Kokoşka", "Paul Kle"], 1),
      createQ("Qədim Romada binaları bəzəmək üçün istifadə olunan kiçik rəngli daşlardan və ya şüşələrdən ibarət rəsm növü nə adlanır?", ["Freska", "Qravüra", "Mozaika", "Akvarel"], 2),
      createQ("Rəssamlıqda perspektiv qanunlarına əsasən, səhnənin bir nöqtəyə doğru birləşməsi nə adlanır?", ["Parallaks", "Kəsişmə", "Üfüq xətti", "İtki nöqtəsi"], 3),
      createQ("\"Açıq hava\" (plein air) rəsm texnikası hansı sənət cərəyanı üçün xarakterikdir?", ["Realizm", "Romantizm", "Klassisizm", "İmpressionizm"], 3),
      createQ("Mədəniyyət tarixində \"Qızıl əsr\" (XIX əsr) əsasən hansı ölkənin ədəbiyyatına və musiqisinə aid edilir?", ["Fransa", "İtaliya", "Rusiya", "Almaniya"], 2),
      createQ("Heç bir süjet və ya obyekt təsvir etməyən, yalnız formalar, rənglər və xətlərdən istifadə edən sənət növü nə adlanır?", ["Realizm", "Futurizm", "Abstrakt incəsənət", "Dadaizm"], 2),
      createQ("\"Bədii sənət\" anlayışını ilk dəfə istifadə edən və əsərlərində Qədim Yunan mifologiyasına qayıdan sənət cərəyanı hansıdır?", ["Romantizm", "Klassisizm", "Barokko", "İmpressionizm"], 1),
      createQ("Musiqidə dörd fərqli səsin eyni anda səslənməsi və harmonik qaydalarla qurulması nə adlanır?", ["Kontrapunkt", "Akord", "Kvartet", "Sonata"], 2),
      createQ("Holland Qızıl Dövrünün rəssamı Yan Vermeerin ən məşhur əsərlərindən biri olan, gənc qadının başının arxası təsvir edilən rəsm hansıdır?", ["Südçü qadın", "İncə toxunuş", "Mirvari sırğalı qız", "Delft mənzərəsi"], 2),
      createQ("XIX əsrin ikinci yarısında sənaye məhsullarını kütləvi incəsənətə gətirən və Pop Art cərəyanının əsasını qoyan amerikalı rəssam kimdir?", ["Cekson Pollok", "Mark Rotko", "Endi Uorhol", "Frensis Bekon"], 2),
      createQ("Memarlıqda Sütun başlığının (Kapitel) yarpaqları təqlid edən kompleks forması ilə seçilən ordo hansıdır?", ["Dorik", "İonik", "Korinf", "Toskana"], 2),
    ],
    hard: [
      createQ("Fransız Sürrealizminin manifestini yazan və hərəkatın intellektual lideri hesab edilən kimdir?", ["Salvador Dali", "Andre Breton", "Maks Ernst", "Rene Maqrit"], 1),
      createQ("Qədim Yunanıstanda heykəltəraşlıqda \"Kontrapposto\" (bir ayağa söykənmə) duruşunu ilk dəfə kim tətbiq etmişdir?", ["Fidi", "Praksitel", "Poliklet", "Skopas"], 2),
      createQ("XV əsrdə İtaliyada rəssamlıqda hava perspektivi və ya atmosfer perspektivi nəzəriyyəsini inkişaf etdirən rəssam kimdir?", ["Botiçelli", "Leonardo da Vinçi", "Rafael", "Mikelancelo"], 1),
      createQ("Teatrda aktyorların və tamaşaçıların eyni məkanda olduğu, ənənəvi səhnənin olmadığı teatr forması necə adlanır?", ["Komediya", "Melodram", "İmmersiv teatr", "Absurd teatrı"], 2),
      createQ("Rus Bədii Qrupu olan \"Mavi Süvari\" (Der Blaue Reiter) cərəyanının əsas nümayəndələri kimlər idi?", ["Maleviç və Rodçenko", "Kandinski və Mark", "Şaqal və Lissitski", "Popova və Stepanova"], 1),
      createQ("Musiqidə 12 tonluq sistemin yaradıcısı və atonal musiqinin inkişafında əsas rol oynayan kimdir?", ["İqor Stravinski", "Arnold Şönberq", "Klod Debüssi", "Dmitri Şostakoviç"], 1),
      createQ("Renessans memarlığında mükəmməl dairəvi formaya malik, simmetrik və bərabər pəncərələrlə bəzədilmiş \"ideal kilsə\" layihəsini kim təklif etmişdir?", ["Filippo Brunelleski", "Donato Bramante", "Andrea Palladio", "Alberti"], 1),
      createQ("\"Neoplastisizm\" cərəyanının banisi və əsasən ağ, qara və əsas rənglərdən istifadə edən holland rəssamı kimdir?", ["Piet Mondrian", "Yan van Eyk", "Hieronymus Boş", "Rene Maqrit"], 0),
      createQ("Musiqidə eyni səsin müxtəlif hündürlüklərdə təkrarı nəticəsində yaranan musiqi aralığı necə adlanır?", ["Sekunda", "Kvarte", "Oktava", "Tersiya"], 2),
      createQ("Məşhur \"Lass-Veqasın mənzərəsi\" əsərinin müəllifi, Pop Art cərəyanının Avropa nümayəndəsi olan ingilis rəssamı kimdir?", ["Devid Hockni", "Frensis Bekon", "Lusian Freyd", "Qrehem Saterlend"], 0),
      createQ("Cozef Boyes (Joseph Beuys) tərəfindən tətbiq edilən, rəssamın tamaşaçı qarşısında bir hərəkət həyata keçirdiyi sənət növü nə adlanır?", ["Qrafika", "Performans", "İllüstrasiya", "Aspekt"], 1),
      createQ("Yunan mifologiyasında memarlıqda caryatid adlanan, damı (entablaturu) dəstəkləyən qadın heykəli ilə məşhur məbəd hansıdır?", ["Partenon", "Erexteyon", "Zevs Məbədi", "Afina Nika Məbədi"], 1),
      createQ("XIII-XIV əsrlərdə İtaliya Renessansının qabaqcılı hesab edilən və rəsmlərində realist insan emosiyalarını tətbiq edən rəssam kimdir?", ["Cimabue", "Cotto", "Duccio", "Donatello"], 1),
      createQ("Qravüra sənət növündə rənglərin metal lövhə üzərindəki qazıntılardan köçürülməsi texnikası nə adlanır?", ["Litoqrafiya", "Ofset", "Ofort (Qazıma)", "Seriqrafiya"], 2),
      createQ("\"Fovizm\" cərəyanı hansı xüsusiyyəti ilə tanınırdı?", ["Həndəsi formaların istifadəsi", "Solğun rənglərin istifadəsi", "Kəskin və təbii olmayan parlaq rənglərin istifadəsi", "Fotoqrafik realizm"], 2),
      createQ("Yaponiyadan qaynaqlanan və ağac üzərində oyma texnikası ilə hazırlanan, əsasən mənzərələrin təsvir olunduğu qravüra növü nə adlanır?", ["Şodo", "Ukiyo-e", "İkebana", "Netsuke"], 1),
      createQ("Musiqidə əsas melodiyanın (vokalın) ardıcıl olaraq müxtəlif səslər tərəfindən təkrarlanması ilə yaranan musiqi parçası nə adlanır?", ["Kanon", "Sonatina", "Kvartet", "Kapriççio"], 0),
      createQ("Qədim Mayya və Astek mədəniyyətlərində istifadə olunan, dörd tərəfli, pilləli memarlıq forması necə adlanır?", ["Piramida", "Ziqurrat", "Mausoley", "Məbəd"], 0),
      createQ("1960-cı illərdə yaranan və sənət əsərlərini məkanın xüsusiyyətlərinə uyğunlaşdıran sənət növü (adətən açıq havada) nə adlanır?", ["Landşaft rəsmi", "İnstallasiya", "Land Art (Torpaq incəsənəti)", "Məkan sənəti"], 2),
      createQ("Rəssamın emalatxanasında (studiya) yaradılan, lakin açıq havada çəkilmiş təəssüratı verən rəsm janrı nə adlanır?", ["Eskiz", "Veduta", "Qrot", "Mənzərə (Peysaj)"], 3),
    ]
  },
  DIN: {
    easy: [
      createQ("İslamda müqəddəs kitab hansıdır?", ["Tövrat", "Quran", "İncil", "Zəbur"], 1),
      createQ("Müsəlmanların qibləsi hansı şəhərdədir?", ["Mədinə", "Qüds", "Məkkə", "Bağdad"], 2),
      createQ("İslam dininə görə peyğəmbərlərin sonuncusu kimdir?", ["İsa", "Musa", "İbrahim", "Məhəmməd"], 3),
      createQ("What is the holy book in Islam?", ["Torah", "Quran", "Bible", "Psalms"], 1, 'en'),
      createQ("In which city is the Qibla located?", ["Medina", "Jerusalem", "Mecca", "Baghdad"], 2, 'en'),
      createQ("Who is the last prophet in Islam?", ["Jesus", "Moses", "Abraham", "Muhammad"], 3, 'en'),
    ],
    medium: [
      createQ("Qurani-Kərimin neçə surəsi var?", ["100", "110", "114", "120"], 2),
      createQ("İslamda ilk xəlifə kim olmuşdur?", ["Əli", "Əbu Bəkir", "Ömər", "Osman"], 1),
      createQ("Qədir gecəsi hansı ayın hansı gecəsidir?", ["Ramazanın 21-ci gecəsi", "Ramazanın 23-cü gecəsi", "Ramazanın 25-ci gecəsi", "Ramazanın 27-ci gecəsi"], 3),
      createQ("How many Surahs are there in the Quran?", ["100", "110", "114", "120"], 2, 'en'),
      createQ("Who was the first Caliph in Islam?", ["Ali", "Abu Bakr", "Umar", "Uthman"], 1, 'en'),
      createQ("When is the Night of Power (Laylat al-Qadr)?", ["21st of Ramadan", "23rd of Ramadan", "25th of Ramadan", "27th of Ramadan"], 3, 'en'),
    ],
    hard: [
      createQ("\"Əl-Buhari\" kimdir?", ["Xəlifə", "Məşhur hədis alimi", "Filosof", "Şair"], 1),
      createQ("Qurani-Kərimin ilk nazil olan ayələri hansı surədəndir?", ["Fatiha", "Ələk", "Qələm", "Müddəssir"], 1),
      createQ("İslam hüququnun dörd əsas mənbəyi hansılardır?", ["Quran, Hədis, İcma, Qiyas", "Quran, Hədis, Rəy, İcma", "Quran, Sünni, İcma, İctihad", "Quran, Hədis, Fiqh, İcma"], 0),
      createQ("Who is Al-Bukhari?", ["Caliph", "Famous Hadith scholar", "Philosopher", "Poet"], 1, 'en'),
      createQ("Which Surah contains the first revealed verses of the Quran?", ["Fatiha", "Al-Alaq", "Al-Qalam", "Al-Muddathir"], 1, 'en'),
      createQ("What are the four main sources of Islamic law?", ["Quran, Hadith, Ijma, Qiyas", "Quran, Hadith, Rai, Ijma", "Quran, Sunnah, Ijma, Ijtihad", "Quran, Hadith, Fiqh, Ijma"], 0, 'en'),
    ]
  },
  FANTASTIK: {
    easy: [
      createQ("\"Harri Potter\" seriyasının müəllifi kimdir?", ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "C.S. Lewis"], 1),
      createQ("\"Harri Potter\" seriyasında baş qəhrəmanın oxuduğu Sehrbazlıq Məktəbi necə adlanır?", ["Beauxbatons", "Durmstranq", "Hoqvarts", "Akademiya"], 2),
      createQ("\"Üzüklərin Ağası\" (The Lord of the Rings) fentezi hekayəsinin müəllifi kimdir?", ["C.S. Lyuis", "C.R.R. Tolkin", "Q.R.R. Martin", "Artur Klark"], 1),
      createQ("\"Ulduz Müharibələri\" (Star Wars) seriyasında Cedayların istifadə etdiyi əsas silah nədir?", ["Lazer tüfəngi", "İşın qılıncı (Lightsaber)", "Plazma topu", "Enerji qalxanı"], 1),
      createQ("Supermen (Superman) personajı hansı uydurma planetdən Yerə gəlmişdir?", ["Mars", "Krypton", "Saylon", "Vulkan"], 1),
      createQ("\"Transformerlər\" seriyasında avtomobillərə və ya başqa texnikaya çevrilə bilən robotlar necə adlanır?", ["Saylonlar", "Kiborqlar", "Decepticon və Autobotlar", "Droidlər"], 2),
      createQ("\"Yad\" (Alien) film seriyasında əsas düşmən olan yad məxluq nədir?", ["Predetor", "Ksenomorf", "İth", "Qremlin"], 1),
      createQ("Ulduz gəmisi \"Enterprise\" hansı məşhur elm-fantastika seriyasına aiddir?", ["Battlestar Galactica", "Star Trek (Ulduz Yolu)", "Babylon 5", "Firefly"], 1),
      createQ("Hörümçək adam (Spider-Man) güclərini haradan almışdır?", ["Kosmosdan", "Radioaktiv hörümçəyin dişləməsindən", "Qədim magiyadan", "Elmi təcrübədən"], 1),
      createQ("Q.R.R. Martinin \"Buz və Alov Nəğməsi\" (Game of Thrones) seriyasının uydurma dünyası necə adlanır?", ["Orta Yer", "Narniya", "Vesteros", "Arrakis"], 2),
      createQ("\"Matriks\" (The Matrix) filmində baş qəhrəman Neo hansı adla tanınırdı (əvvəl)?", ["Tomas Anderson", "Morfius", "Agent Smit", "Sifer"], 0),
      createQ("2010-cu illərdə məşhurlaşan və baş qəhrəman Katnis Everdinin iştirak etdiyi distopik film seriyası hansıdır?", ["Divergent", "Açlıq Oyunları (The Hunger Games)", "Labirint Qaçışçısı", "Narniya Salnamələri"], 1),
      createQ("\"Doktor Kim\" (Doctor Who) serialında baş qəhrəmanın zaman səyahəti etdiyi maşın nə adlanır?", ["DeLorean", "TARDIS", "Milennium Falcon", "Enterprise"], 1),
      createQ("Robert Haynlaynın məşhur elmi-fantastika romanı olan və yad məxluqlara qarşı mübarizə aparan əsgərləri təsvir edən əsəri hansıdır?", ["Duna", "Ulduz əsgərləri (Starship Troopers)", "Varislik", "Əbədi müharibə"], 1),
      createQ("Məşhur fentezi dünyası olan \"Narniya Salnamələri\"ndə uşaqların gizli dünyaya keçdiyi qapı nədir? ", ["Güzgü", "Şkaf (Dolab)", "Kitab", "Tunel"], 1),
      createQ("\"Frankenşteyn\" romanındakı əsas canavarı (məxluqu) yaradan alimin adı nədir?", ["Doktor Cekill", "Viktor Frankenşteyn", "Van Helsenq", "Doktor Morqan"], 1),
      createQ("\"Yer kürəsi dayandı\" (The Day the Earth Stood Still) filmində Yer kürəsinə gələn yadplanetlinin adı nədir?", ["Qort", "Klatu", "Yoda", "Spok"], 1),
      createQ("\"Jurasik Park\" filmində alimlər hansı heyvanları diriltmişdilər?", ["Mamontları", "Dinazavrları", "Quşları", "Pələngləri"], 1),
      createQ("Hansı filmdə zaman səyahəti \"DeLorean\" markalı avtomobillə həyata keçirilir?", ["Terminator", "Gələcəyə Dönüş (Back to the Future)", "Looper", "Planetlər arası"], 1),
      createQ("Süni intellektlə (AI) bağlı olan və \"Mən robotam\" (I, Robot) əsərinin müəllifi kimdir?", ["Artur Klark", "Ayzek Asimov", "Filip K. Dik", "Stiven Kinq"], 1),
    ],
    medium: [
      createQ("\"The Hobbit\" və \"Üzüklərin Hökmdarı\" hansı kainatda cərəyan edir?", ["Narnia", "Middle-earth (Orta Dünya)", "Westeros", "Azeroth"], 1),
      createQ("Lyuk Skauokerin (Ulduz Müharibələri) uşaqlığının keçdiyi və yeraltı evləri ilə tanınan planet hansıdır?", ["Coruskant", "Tatuin", "Alderaan", "Hoth"], 1),
      createQ("Artur Klarkın məşhur elmi-fantastik romanı olan və Yer kürəsində yadplanetli texnologiyasının tapılması ilə başlayan əsər hansıdır?", ["Kosmos Odisseyası 2001", "Rəma ilə görüş", "Uşaqlıq sonu", "3001"], 2),
      createQ("\"Blade Runner\" filmi hansı yazıçı tərəfindən yazılmış roman əsasında çəkilmişdir?", ["Qreq Bear", "Filip K. Dik", "Uilyam Gibson", "Nil Qeyman"], 1),
      createQ("\"Valar Moqulis\" (Bütün insanlar ölməlidir) ifadəsi hansı fentezi seriyasından gəlir?", ["Üzüklərin Ağası", "Taxt Oyunları (Game of Thrones)", "Cadugər (The Witcher)", "Mütləq Məcburiyyət"], 1),
      createQ("\"Duna\" (Dune) elmi-fantastik seriyasında qəhrəmanların əsas sərvəti və güc mənbəyi sayılan maddə nədir?", ["Kriptonit", "Spice (Ədviyyat/Mürəkkəb)", "Vibranium", "Unobtanium"], 1),
      createQ("Qabriel Ferenheytin temperatur ölçü vahidini kəşf etməsi nəyi sübut edir?", ["Zaman səyahətinin mümkünlüyünü", "Elmi-fantastika deyil, tarixi fakt olduğunu", "Paralel kainatların varlığını", "Süni intellektin üstünlüyünü"], 1),
      createQ("1984-cü ildə Con Ueylesin yazdığı və Böyük Qardaş (Big Brother) konsepsiyası ilə məşhur olan distopik roman hansıdır?", ["Cəsur Yeni Dünya", "1984", "Ferma heyvanları", "Biz"], 1),
      createQ("\"Terminator\" filmlərində, gələcəkdən gələn və insanlara qarşı müharibə aparan süni intellekt sistemi necə adlanır?", ["HAL 9000", "Skynet", "VİKİ", "Deep Blue"], 1),
      createQ("Hansı superqəhrəman \"Marvel\" kainatında \"Qeyri-adi Halk\" (The Incredible Hulk) kimi tanınır?", ["Piter Parker", "Brüs Banner", "Toni Stark", "Stiven Rocers"], 1),
      createQ("\"Yeraltı dünya\" (The Underland Chronicles) fentezi seriyasında əsas personajlar Yer səthindən hansı vasitə ilə keçirlər?", ["Sehrli portal", "Qədim zindanlar", "Şəhər kanalizasiya sistemi", "Vulkan"], 2),
      createQ("Elm-fantastikada \"Sayberpank\" (Cyberpunk) janrının əsasını qoyan və \"Neyromant\" (Neuromancer) romanının müəllifi kimdir?", ["Nil Stivenson", "Uilyam Gibson", "Filip K. Dik", "Con Skalzi"], 1),
      createQ("\"Nibelunqların Üzüyü\" adlı opera əsəri hansı fentezi janrının prototipi sayılır?", ["Qotik", "Post-apokaliptik", "Yüksək Fentezi (High Fantasy)", "Steampunk"], 2),
      createQ("Süni intellektlə bağlı olan və robotların üç qanunu (Three Laws of Robotics) kim tərəfindən irəli sürülmüşdür?", ["Corc Lukas", "Ayzek Asimov", "Filip K. Dik", "Artur Klark"], 1),
      createQ("Marvel Kinematoqrafiya Kainatında (MCU) \"Sonsuzluq daşları\"nı (Infinity Stones) toplamağa çalışan düşmən kimdir?", ["Loki", "Ultron", "Tanos", "Zemo"], 2),
      createQ("Distopik roman olan \"Cəsur Yeni Dünya\"da (Brave New World) insanlar hansı üsulla siniflərə bölünürlər?", ["Maliyyə vəziyyəti", "Genetik modifikasiya (yumurtalıqdan çıxarılma)", "İmtahan nəticələri", "Hərbi rütbələr"], 1),
      createQ("\"Metropolis\" (1927) səssiz filmi hansı janrın ilk böyük nümunəsi hesab olunur?", ["Qorxu", "Komediya", "Elm-fantastika/Distopiya", "Fentezi"], 2),
      createQ("\"Yaddaş\" (Total Recall) filmi hansı Filip K. Dik qısa hekayəsi əsasında çəkilib?", ["Minority Report", "Do Androids Dream of Electric Sheep?", "We Can Remember It for You Wholesale", "The Adjustment Bureau"], 2),
      createQ("\"Odisseyin Uşaqları\" (Children of the Odyssey) seriyası hansı yunan mifoloji fiqurunun fantastik macərasıdır?", ["Herakl", "Persey", "Odissey", "Yason"], 2),
      createQ("\"Fantastik dördlük\" (Fantastic Four) komandasında özünü alovlandıra bilən personaj kimdir?", ["Mr. Fantastic", "Human Torch", "Thing", "Invisible Woman"], 1),
      createQ("\"Yer kürəsi dayandı\" (The Day the Earth Stood Still) filminin əsas süjeti hansı dövrün sosial gərginliyini əks etdirir?", ["Birinci Dünya müharibəsi", "Soyuq müharibə", "Böyük böhran", "Vyetnam müharibəsi"], 1),
    ],
    hard: [
      createQ("\"Neuromancer\" əsərinin müəllifi kimdir?", ["William Gibson", "Neal Stephenson", "Bruce Sterling", "Philip K. Dick"], 0),
      createQ("Fentezi ədəbiyyatında \"Grimdark\" (Qaranlıq) alt-janrı ən çox hansı xüsusiyyətləri ilə tanınır?", ["Saf qəhrəmanlar və xoşbəxt son", "Yüksək səviyyəli texnologiya", "Mənəvi qeyri-müəyyənlik, qəddarlıq", "Uşaqlar üçün yazılmış hekayələr"], 2),
      createQ("Ayzek Asimovun \"Vəqf\" (Foundation) seriyasında cəmiyyətin gələcək inkişafını riyazi olaraq proqnozlaşdıran elm sahəsi necə adlanır?", ["Kvant mexanikası", "Psixotarix (Psychohistory)", "Sosiologiya", "Genetik mühəndislik"], 1),
      createQ("Corc Oruellin \"1984\" romanındakı \"Yeni danışıq\" (Newspeak) dilinin əsas məqsədi nədir?", ["Ünsiyyəti asanlaşdırmaq", "İnsanların tənqidi düşüncəsini məhdudlaşdırmaq", "Şeiriyyəti artırmaq", "Texnoloji inkişafı sürətləndirmək"], 1),
      createQ("\"Star Trek\" kainatında \"Vulcan\" irqinin əsas fəlsəfəsi və məntiqə əsaslanan həyat tərzi necə adlanır?", ["Qanuni həyat tərzi", "İntellektual birlik", "Kollektiv şüur", "Qeyri-emosionallıq"], 3),
      createQ("Filip K. Dik əsərlərinin əsas mövzusu nədir?", ["Zaman səyahəti", "Reallığın və insan kimliyinin tərifi", "Orta əsrlər fantaziyası", "Uşaqların macəraları"], 1),
      createQ("\"Neuromant\" romanında təsvir edilən, bütün insanların kompüterlərə qoşulduğu kütləvi virtual reallıq məkanı necə adlanır?", ["Kosmos", "Simulyasiya", "Sayberspeys (Cyberspace)", "Metaver"], 2),
      createQ("Məşhur fentezi romanı olan \"Cadugər\" (The Witcher) seriyasının müəllifi kimdir?", ["C.R.R. Tolkin", "Stiven Kinq", "Andrzey Sapkovski", "Neil Gaiman"], 2),
      createQ("\"Ulduz Müharibələri\"ndə Cedayların pis tərəfi olan, qara geyimli və İşın qılıncından istifadə edən sərkərdələr necə adlanır?", ["Sith Lordları", "Bounty Hunter", "Yeraltı dünya", "Rebel"], 0),
      createQ("Elmi-fantastikada \"Steampunk\" alt-janrı əsasən hansı tarixi dövrün estetikasını və texnologiyasını təqlid edir?", ["Antik Roma", "Viktorian dövrü (Buxar maşınları)", "İkinci Dünya müharibəsi", "Orta əsrlər"], 1),
      createQ("Frenk Herbertin \"Duna\" seriyasında yadplanetli qüvvələrə qarşı döyüşən, dindən çox güc alan sərkərdələr kimlərdir?", ["Harkonnenlər", "Fremenlər", "Cedaylar", "Mentatlar"], 1),
      createQ("\"Əbədi müharibə\" (The Forever War) romanı hansı fiziki fenomendən istifadə edərək süjetdə zaman sürüşmələri yaradır?", ["Qara dəliklər", "Nisbilik effekti (Vaxtın ləngiməsi)", "Sonsuz enerji", "Anti-maddə"], 1),
      createQ("\"Bədən dəyişməsi\" (Body Snatchers) filmlərinin əsas süjet xətti nədir?", ["Robotların Yeri işğal etməsi", "Yadplanetlilərin insanların yerini fiziki olaraq kopyalaması", "Virusun bədənləri dəyişməsi", "Zaman səyahəti"], 1),
      createQ("\"Silmarillion\" əsəri hansı böyük fentezi dünyasının mifoloji və tarixi əsasını təşkil edir?", ["Vesteros", "Orta Yer", "Narniya", "Erdsea"], 1),
      createQ("Ayzek Asimovun \"Yaşamaq üçün Yer\" (The Caves of Steel) romanında, insan cəmiyyətinin Yer kürəsində tamamilə yer altındakı şəhərlərə köçməsinin əsas səbəbi nədir?", ["Yadplanetli hücumu", "Əhalinin artması və ekoloji dağıntı", "Nüvə müharibəsi", "Robotların idarəetməsi"], 1),
      createQ("Superqəhrəman komandası olan \"X-Men\" (İks Adamlar) personajları hansı xüsusiyyətlərinə görə cəmiyyətdən fərqlənirlər?", ["Sehrli güclər", "Genetik mutasiyalar (Mutantlar)", "Texnoloji kostyumlar", "Başqa planetdən gəlmələri"], 1),
      createQ("Məşhur \"Planetlər Arası\" (Interstellar) filminin elmi əsasını təşkil edən və filmin məşhur professorunun adını daşıyan \"Dəlik\" (Portal) necə adlanır?", ["Qara dəlik", "Qurd dəliyi (Wormhole)", "Tərs dəlik", "Zaman tuneli"], 1),
      createQ("Elmi-fantastikada \"Sivilizasiyaların Yüksəlişi\" (The Rise of Civilization) süjet xəttinin əsas mövzusu nədir?", ["Robotların qiyamı", "Düşmüş bir sivilizasiyanın qalıqlarından yenidən yüksəlməsi", "Əbədi həyat axtarışı", "Zaman dövrələri"], 1),
      createQ("Harri Potter seriyasında \"Ölüm Yeyənlər\"in lideri kimdir?", ["Qellert Qrindelvald", "Voldemort", "Severus Sneyk", "Albus Dambldor"], 1),
      createQ("Elm-fantastikada \"Terraformasiya\" termini nə deməkdir?", ["Bir planetin məhv edilməsi", "Bir planetin Yer kürəsinin ekosistemlərinə uyğunlaşdırılması", "İnsanların robotlara çevrilməsi", "Yer kürəsinin sirrini kəşf etmək"], 1),
      createQ("\"Valerian və min planet şəhəri\" filminin çəkildiyi əsas uydurma məkan olan böyük stansiya necə adlanır?", ["Kosmik Liman", "Alpha", "Beta", "Xanadu"], 1),
    ]
  },
  FILM: {
    easy: [
      createQ("Titanik filminin baş qəhrəmanlarının adları nədir?", ["Skarlet və Rett", "Cek və Rouz", "Han Solo və Leya", "Romeo və Cülyetta"], 1),
      createQ("Məşhur \"Ulduz Müharibələri\" (Star Wars) sagasının rejissoru kimdir?", ["Stiven Spilberq", "Ceyms Kameron", "Corc Lukas", "Kristofer Nolan"], 2),
      createQ("\"Oskar\" mükafatları hansı sənət sahəsindəki nailiyyətlərə görə verilir?", ["Musiqi", "Ədəbiyyat", "Kino", "Rəqs"], 2),
      createQ("Animasiya filmləri istehsal edən məşhur \"Pixar\" studiyası hansı böyük şirkətə məxsusdur?", ["Warner Bros.", "Paramount", "Disney", "Universal"], 2),
      createQ("\"Hörümçək adam\" (Spider-Man) personajını canlandıran ilk filmdə (2002) aktyor kim idi?", ["Tom Holland", "Tobey Maquayr", "Endryu Qarfild", "Kris Evans"], 1),
      createQ("Məşhur Britaniya casusu Ceyms Bondun agent nömrəsi nədir?", ["001", "007", "009", "070"], 1),
      createQ("\"Qisasçılar\" (Avengers) film seriyasında əsas düşmən kimdir?", ["Loki", "Ultron", "Tanos", "Red Skull"], 2),
      createQ("Hansı filmdə Leonardo di Kaprio yuxuları oğurlayan bir casusu canlandırır?", ["Şutter Adası", "Başlanğıc (Inception)", "Vol Strit Canavarı", "Qan almazı"], 1),
      createQ("\"Üzüklərin Ağası\" (The Lord of the Rings) trilogiyasının çəkildiyi əsas ölkə hansıdır?", ["Kanada", "Avstraliya", "Yeni Zelandiya", "İrlandiya"], 2),
      createQ("\"Terminator\" filmində əsas personaj olan kiborq rolunu kim canlandırıb?", ["Silvestr Stallone", "Brüs Uillis", "Arnold Şvartsenegger", "Mel Gibson"], 2),
      createQ("Qəhrəmanı Betmen olan film seriyasının yerləşdiyi şəhər necə adlanır?", ["Nyu York", "Qotem Siti", "Metropolis", "Oukland"], 1),
      createQ("Uğurlu rejissor işlərinə görə \"Oskar\" qazanmış ilk qadın rejissor kimdir?", ["Ketrin Biqelou", "Qreta Herviq", "Sofiya Koppola", "Ceyn Kempion"], 0),
      createQ("Kino sənətində rejissorun çəkdiyi ilk film adətən necə adlanır?", ["Baş film", "Debüt", "Epizod", "Seqvel"], 1),
      createQ("\"Forrest Qamp\" filmində baş rolu oynayan aktyor kimdir?", ["Robert de Niro", "Tom Henks", "Conni Depp", "Bred Pitt"], 1),
      createQ("Qorxu filmi janrında səs effektlərindən və qan səhnələrindən istifadə edilən alt-janr necə adlanır?", ["Triller", "Psixoloji qorxu", "Sleşer (Slasher)", "Komediya"], 2),
      createQ("Film çəkilişləri zamanı istifadə olunan, səs və görüntünün sinxronizasiyası üçün vacib olan taxta qurğu nə adlanır?", ["Kulis", "Ştativ", "Klaket", "Lampa"], 2),
      createQ("Əsas mövzusu Qədim Qərb (ABŞ) olan janr necə adlanır?", ["Fantastik", "Vestern", "Tarixi", "Komediya"], 1),
      createQ("Qara-ağ filmlərdən rəngli filmlərə keçid əsasən hansı əsrdə baş vermişdir?", ["XIX əsr", "XX əsr", "XXI əsr", "XVIII əsr"], 1),
      createQ("\"Karib dənizinin quldurları\" (Pirates of the Caribbean) filmində Kapitan Cek Spara rolunu kim canlandırıb?", ["Orlando Blum", "Conni Depp", "Kris Hemsvort", "Kianu Rivz"], 1),
      createQ("\"Cazda yalnız qızlar\" (Some Like It Hot) klassik komediyasında baş qadın rolunu oynayan aktrisa kimdir?", ["Elizabet Teylor", "Merilin Monro", "Odri Hepbern", "Cudi Qarland"], 1),
    ],
    medium: [
      createQ("Alfred Hiçkokun məşhur psixoloji trilleri olan və duş səhnəsi ilə yadda qalan film hansıdır?", ["Quşlar", "Psixo", "Arxa Pəncərə", "Vertiqo"], 1),
      createQ("\"Pulp Fiction\" filminin rejissoru kimdir?", ["Martin Skorseze", "Kventin Tarantino", "Spayk Li", "Deyvid Finçer"], 1),
      createQ("Akira Kurosavanın məşhur samurai filmi olan və Hollivudda \"Yeddi Möhtəşəm Adam\" kimi yenidən çəkilən əsər hansıdır?", ["Raşomon", "Yeddi Samurai", "Ran", "Qan Taxtı"], 1),
      createQ("\"Birinci hissə\", \"İkinci hissə\" və \"Üçüncü hissə\" adları ilə tanınan \"Xa-çəkmə ata\" (The Godfather) trilogiyasının rejissoru kimdir?", ["Brian de Palma", "Frensis Ford Koppola", "Maykl Man", "Corc Lukas"], 1),
      createQ("1999-cu ildə çəkilmiş və \"qırmızı tablet\" və \"mavi tablet\" seçimi ilə məşhur olan kiberpank filmi hansıdır?", ["Tron", "Matriks", "Blade Runner", "Yaddaş"], 1),
      createQ("Hollivudun \"Qızıl dövrü\" aktrisalarından biri olan və \"Tiffanidə Səhər Yeməyi\" filmi ilə məşhurlaşan aktrisa kimdir?", ["Elizabet Teylor", "Odri Hepbern", "Qreys Kelli", "Cin Harlou"], 1),
      createQ("Məşhur \"Citizen Kane\" (Vətəndaş Keyn) filminin rejissoru və baş rol ifaçısı kimdir?", ["Frensis Ford Koppola", "Orson Uells", "Sesil B. de Mille", "Ceyms Stüart"], 1),
      createQ("Xüsusi vizual effektlər üçün kompüter qrafikasının (CGI) geniş tətbiq olunmasına səbəb olan ilk böyük film hansıdır (1993)?", ["Avatar", "Yura Parkı", "Terminator 2", "Ulduz Müharibələri"], 1),
      createQ("Fransız Yeni Dalğası (Nouvelle Vague) cərəyanının əsas banilərindən biri və \"Nəfəssiz\" (À bout de souffle) filminin rejissoru kimdir?", ["Fransua Trüffo", "Jan-Lük Qodar", "Erik Römer", "Klod Şabrol"], 1),
      createQ("Bir filmin büdcəsinin gəlirindən az olması, yəni kommersiya uğursuzluğu nə adlanır?", ["Blockbuster", "Flop", "Box Office", "Prodüser"], 1),
      createQ("Məşhur \"Lawrence of Arabia\" filminin rejissoru kimdir?", ["Stiven Spilberq", "Frensis Ford Koppola", "David Lin", "Stenli Kubrik"], 2),
      createQ("\"Gecə yarısı Ekspresi\" (Midnight Express) filminin ssenaristi olan və \"Oskar\" qazanan rejissor kimdir?", ["Oliver Stoun", "Martin Skorseze", "Kventin Tarantino", "Vudi Allen"], 0),
      createQ("Film sənayesində bir aktyor və ya rejissorun karyerasının ilk böyük, uğurlu roluna və ya filminə nə deyilir? (Breakout role)", ["Prequel", "Qrand-pri", "Çıxış rolu", "Seqvel"], 2),
      createQ("Hansı rejissor \"Qara Kvadrat\" və \"Requiem for a Dream\" kimi dramatik və emosional filmləri ilə tanınır?", ["Darren Aronofski", "Kristofer Nolan", "Devid Linç", "Vudi Allen"], 0),
      createQ("\"Şindler'in siyahısı\" (Schindler's List) filmi hansı tarixi hadisəni əhatə edir?", ["Vyetnam müharibəsi", "Holokost", "Birinci Dünya müharibəsi", "Soyuq müharibə"], 1),
      createQ("Hansı film janrında əsas məqsəd tamaşaçını qəsdən çaşdırmaq və ya aldatmaqdır (son səhnəyə qədər həqiqəti gizlətmək)?", ["Müzikl", "Neo-noir", "Triller", "Qara komediya"], 2),
      createQ("Məşhur \"Rambo\" və \"Rokki\" film seriyalarında baş rolu canlandıran aktyor kimdir?", ["Arnold Şvartsenegger", "Brüs Uillis", "Silvestr Stallone", "Cen-Klod Van Damm"], 2),
      createQ("Filmdə dramatik məqamı vurğulamaq üçün əsas personajın üzünün böyüdülmüş (yaxın) planı necə adlanır?", ["Ümumi plan", "Orta plan", "Yaxın plan (Close-up)", "Montaj"], 2),
      createQ("\"Ameli\" (Amélie) filminin çəkildiyi əsas şəhər hansıdır?", ["Roma", "London", "Berlin", "Paris"], 3),
      createQ("Hansı rejissor \"Oskar\" mükafatına namizəd olsa da, heç vaxt mükafatı qazanmadığına görə tanınır?", ["Martin Skorseze", "Stenli Kubrik", "Kventin Tarantino", "Kristofer Nolan"], 1),
    ],
    hard: [
      createQ("Stenli Kubrikin 1968-ci ildə çəkdiyi və hələ də elm-fantastika janrının ən böyük əsərlərindən sayılan film hansıdır?", ["A Clockwork Orange", "2001: Space Odyssey", "Dr. Strangelove", "Spartak"], 1),
      createQ("Orson Uellsin rejissorluğu ilə çəkilmiş və kino tarixində ən böyük filmlərdən biri hesab edilən 1941-ci ilin filmi hansıdır?", ["Ambersonlar", "Vətəndaş Keyn (Citizen Kane)", "Şərin toxunuşu", "Xanım Şanxaydan"], 1),
      createQ("\"Dogme 95\" bəyannaməsi əsasən hansı ölkənin rejissorları tərəfindən irəli sürülmüşdür?", ["Fransa", "İsveç", "Danimarka", "Polşa"], 2),
      createQ("1950-ci illərdə Hindistan kinosunda yaranmış və qərb kinematoqrafiyasının təsirini rədd edən \"Paralel Kino\" (Art Film) cərəyanının əsas nümayəndəsi kimdir?", ["Tac Mahal", "Satyacit Ray", "Şahruk Xan", "Amr Kedi"], 1),
      createQ("\"Oskar\" tarixində eyni ildə ən çox namizədlik (11 namizədlik) qazanan və heç bir mükafat almayan film hansıdır?", ["The Turning Point (1977)", "The Color Purple (1985)", "Qanqsterin Sevgi Macərası", "O, Hardadır?"], 0),
      createQ("1927-ci ildə çəkilmiş və Alman ekspressionizminin zirvəsi hesab edilən, gələcəyin şəhərini təsvir edən səssiz film hansıdır?", ["Das Kabinett des Dr. Caligari", "Nosferatu", "Metropolis", "M"], 2),
      createQ("Filmdə kamera personajın (xüsusilə sərxoş və ya ruhi pozğunluq keçirən) baxış bucağını təqlid etdiyi xüsusi çəkiliş texnikası necə adlanır?", ["Zoom", "Vertigo effekti (Dolly Zoom)", "Steadicam", "Montaj"], 1),
      createQ("Məşhur \"Tokyo Story\" (Tokyo hekayəsi) filminin rejissoru, Yapon kinosunun ustası kimdir?", ["Akira Kurosava", "Yasuciro Ozu", "Hayao Miyazaki", "Takeshi Kitano"], 1),
      createQ("Qısa müddət ərzində ardıcıl olaraq çəkilmiş, lakin sonradan tamamilə fərqli bir ardıcıllıqla montaj olunmuş səhnələrdən ibarət film hansıdır?", ["Başlanğıc (Inception)", "Memento", "Pi həyatı", "2001: Space Odyssey"], 1),
      createQ("\"Cineaste\" tərəfindən \"ən böyük rejissor\" adlandırılan və \"Sərgüzəşt\" (L'Avventura) filmi ilə tanınan italyan rejissoru kimdir?", ["Federiko Fellini", "Mikelancelo Antonioni", "Vitorio De Sika", "Roberto Rossellini"], 1),
      createQ("İncəsənət Kinosunda istifadə olunan, filmin hekayə xəttinin başlanğıc, orta və son hissəsi olmadan, axıcı şəkildə davam etməsi nə adlanır?", ["Səbəb-nəticə montajı", "Episodik struktur", "Qeyri-nəqli (Non-narrative) struktur", "Struktur-hekayə"], 2),
      createQ("Film sənayesində bir studiyanın il ərzində buraxdığı filmlərin sayı və ya növü haqqında nəzərdə tutulmuş planı necə adlanır?", ["Portfel", "Slate", "Vizual plan", "Seqment"], 1),
      createQ("Məşhur \"Vəhşi dəstə\" (The Wild Bunch) filminin rejissoru, Vestern janrına qəddarlıq və vizual dramatizm gətirən kimdir?", ["Serco Leone", "Sam Pekinpa", "Klint İstvud", "Con Ford"], 1),
      createQ("Rejissorun müəllif hüququnu qoruyan və son montaj qərarını verdiyi kino konsepsiyası necə adlanır?", ["Prodüser versiyası", "Studi versiyası", "Auteur (Müəllif) Nəzəriyyəsi", "Vizual təqdimat"], 2),
      createQ("Hindistanın Mumbay şəhərində yerləşən, dünyanın ən böyük film istehsal mərkəzi necə adlanır?", ["Tollyvud", "Lolivud", "Bollivud", "Nolivud"], 2),
      createQ("Film çəkilişləri zamanı istifadə olunan və kameranın hərəkətini (relslər üzərində) yumşaq və axıcı edən qurğu nə adlanır?", ["Gimbal", "Dolly", "Kran", "Ştativ"], 1),
      createQ("Məşhur \"Blade Runner\" filmi hansı tanınmış elm-fantastik yazıçı tərəfindən yazılmış roman əsasında çəkilmişdir?", ["Ayzek Asimov", "Artur Klark", "Filip K. Dik", "Robert Haynlayn"], 2),
      createQ("Əksər hallarda ən qədim film hesab edilən və 1888-ci ildə çəkilmiş qısametrajlı film hansıdır?", ["Treynin gəlişi", "Roundhay Garden Scene", "Aya səyahət", "Böyük qatar soyğunçuluğu"], 1),
      createQ("Hansı filmdə aktyor Deniel Dey-Lüis Prezident Abraham Linkolnu canlandırıb və \"Oskar\" qazanıb?", ["Qan almazı", "Lincoln", "Nyu York qanqsterləri", "Mənim sol ayağım"], 1),
      createQ("\"Oskar\" mükafatını qazanan ilk qeyri-ingilisdilli film (1956) hansı ölkəyə məxsus idi (müsabiqə yolu ilə)?", ["İtaliya", "Fransa", "Yaponiya", "Meksika"], 1),
    ]
  },
  TEXNOLOGIYA: {
    easy: [
      createQ("Şəxsi kompüterlərdə istifadə olunan əsas əməliyyat sistemi nədir?", ["Microsoft Word", "Adobe Photoshop", "Windows", "Google Chrome"], 2),
      createQ("İnternetdə məlumatları axtarmaq üçün istifadə edilən proqramlara nə ad verilir?", ["Elektron cədvəl", "Veb-brauzer", "Əməliyyat sistemi", "Mətn redaktoru"], 1),
      createQ("Kompüterin \"beyni\" adlandırılan əsas komponent hansıdır?", ["RAM", "Ana plata (Motherboard)", "Mərkəzi Prosessor Bloku (CPU)", "Sərt disk (HDD)"], 2),
      createQ("Məlumatları müvəqqəti olaraq saxlayan və kompüter söndükdə məlumatları itirən yaddaş növü hansıdır?", ["ROM (Yalnız oxunur yaddaş)", "HDD (Sərt disk)", "RAM (Təsadüfi girişli yaddaş)", "SSD (Bərk hallı disk)"], 2),
      createQ("İnternetdə ünsiyyət qurmaq və məlumat mübadiləsi üçün istifadə olunan əsas protokol hansıdır?", ["HTTP", "USB", "HDMI", "VGA"], 0),
      createQ("Mobil telefonlarda istifadə olunan iki əsas əməliyyat sistemi hansılardır?", ["Linux və Unix", "Windows və macOS", "Android və iOS", "ChromeOS və FirefoxOS"], 2),
      createQ("Kompüterə məlumat daxil etmək üçün istifadə olunan əsas giriş qurğusu hansıdır?", ["Monitor", "Printer", "Klaviatura", "Dinamik"], 2),
      createQ("Wi-Fi nə deməkdir?", ["Sürətli internet", "Simli əlaqə", "Simsiz yerli şəbəkə", "Telefon xətti"], 2),
      createQ("Elektron poçt ünvanının mütləq olmalıdır nədir?", ["/", "@", "#", "$"], 1),
      createQ("Bir kilobayt (KB) neçə baytdan ibarətdir?", ["10", "100", "1024", "10000"], 2),
      createQ("Kompüterdə qrafik məlumatların çıxarılması üçün istifadə olunan əsas qurğu hansıdır?", ["Səs kartı", "Ekran (Monitor)", "Klaviatura", "Sərt disk"], 1),
      createQ("Məlumatları kağız üzərinə çıxarmaq üçün istifadə olunan qurğu nə adlanır?", ["Skaner", "Proyektor", "Printer", "Modem"], 2),
      createQ("Kompüter proqramlarının hazırlanması üçün istifadə olunan dil nə adlanır?", ["Təbii dil", "Proqramlaşdırma dili", "Texniki lüğət", "İnsan dili"], 1),
      createQ("Dünyanın ən böyük onlayn ensiklopediyası hansıdır?", ["Britannica", "Wikipedia", "Google", "YouTube"], 1),
      createQ("Kompüteri viruslardan qorumaq üçün hansı proqramdan istifadə olunur?", ["Veb-brauzer", "Əməliyyat sistemi", "Antivirus proqramı", "Mətn redaktoru"], 2),
      createQ("Bir internet səhifəsinin ünvanı necə adlanır?", ["LAN", "CPU", "URL", "HTML"], 2),
      createQ("Optik sürücülərdə (CD/DVD) məlumatın oxunması üçün nə istifadə olunur?", ["Maqnit başlıq", "Lazer şüası", "Elektrik cərəyanı", "Sensor"], 1),
      createQ("Smartfonlarda səsli əmrləri yerinə yetirən süni intellekt köməkçiləri necə adlanır?", ["Elektron cədvəl", "Virtual köməkçi", "Məlumat bazası", "Veb sayt"], 1),
      createQ("Məlumatların uzaq serverlərdə saxlanılması və internet üzərindən əldə edilməsi texnologiyası necə adlanır?", ["Bulud texnologiyası (Cloud)", "Lokal şəbəkə", "Bluetooth", "VPN"], 0),
      createQ("HTML nə üçün istifadə olunur?", ["Şəkilləri redaktə etmək üçün", "Veb səhifələrin strukturunu yaratmaq üçün", "Video çəkmək üçün", "Antivirus funksiyaları üçün"], 1),
    ],
    medium: [
      createQ("Süni intellektdə istifadə olunan və maşınların təcrübədən öyrənməsinə imkan verən əsas yanaşma nədir?", ["Proqram təminatı", "Maşın öyrənməsi (Machine Learning)", "Kvant hesablaması", "Kriptoqrafiya"], 1),
      createQ("Məlumatların bir şəbəkədə kiçik hissələrə bölünərək göndərilməsi və sonra birləşdirilməsi prosesi necə adlanır?", ["Simli ötürülmə", "Paket kommutasiyası", "Tezlik modulyasiyası", "Serial ötürülmə"], 1),
      createQ("Proqramlaşdırmada bir obyektin xüsusiyyətlərini və davranışını təyin edən struktur nə adlanır?", ["Funksiya", "Dəyişən", "Sinif (Class)", "Massiv"], 2),
      createQ("IP ünvanları insanların oxuya biləcəyi domen adlarına çevirən xidmət nə adlanır?", ["HTTP", "DNS (Domain Name System)", "FTP", "SMTP"], 1),
      createQ("Veb-saytlarda hərəkətliliyi (animasiya, interaktivlik) təmin edən proqramlaşdırma dili hansıdır?", ["HTML", "CSS", "JavaScript", "Python"], 2),
      createQ("Həssas məlumatları kodlaşdırmaqla icazəsiz girişdən qoruyan texnologiya nə adlanır?", ["Dekompressiya", "Kriptoqrafiya", "Virtualizasiya", "Optimizasiya"], 1),
      createQ("Kompüter şəbəkəsində məlumatların təhlükəsizliyini təmin etmək üçün istifadə olunan \"maneə\" sistemi nə adlanır?", ["Router", "Firewall (Təhlükəsizlik divarı)", "Switch", "Server"], 1),
      createQ("Süni intellektdə insanın öyrənmə prosesini təqlid edən alqoritmik struktur nə adlanır?", ["Məlumat bazası", "Neyron şəbəkəsi", "Funksional proqramlaşdırma", "Bulud texnologiyası"], 1),
      createQ("Təkrarlanan əməliyyatları avtomatlaşdıran və ya idarə edən mexaniki, elektron və ya proqram təminatı sistemi necə adlanır?", ["Hiperlink", "Robot", "Modem", "Server"], 1),
      createQ("Verilənlər Bazasının İdarəetmə Sistemləri (VBİS) üçün standart sorğu dili hansıdır?", ["Python", "SQL", "C++", "Java"], 1),
      createQ("Fərdi kompüterlərdə istifadə olunan, məlumatları sürətli şəkildə saxlayan və mexaniki hissələri olmayan yaddaş növü hansıdır?", ["HDD", "Floppy Disk", "SSD", "CD-ROM"], 2),
      createQ("Məlumatların bir nöqtədən digərinə ardıcıl şəkildə (bit-bit) ötürülməsi nə adlanır?", ["Paralel ötürmə", "Serial ötürmə", "Optik ötürmə", "Simli ötürmə"], 1),
      createQ("Sənaye robotlarının və ya avtomatlaşdırılmış sistemlərin idarə edilməsində əsas rolu olan mühəndislik sahəsi nədir?", ["Kvant fizikası", "Mexatronika", "Molekulyar biologiya", "Termodinamika"], 1),
      createQ("Veb səhifələrin vizual görünüşünü və stilini (rəng, şrift, layout) təyin edən dil hansıdır?", ["HTML", "JavaScript", "CSS (Cascading Style Sheets)", "PHP"], 2),
      createQ("Proqramlaşdırmada bir şərtin doğru və ya yanlış olmasından asılı olaraq icranın istiqamətini dəyişməsi nə adlanır?", ["Dövr (Loop)", "Şərti budaqlanma", "Rekursiya", "Məlumat tipləri"], 1),
      createQ("Böyük həcmdə verilənlərin (Big Data) saxlanılması, emalı və analizi üçün istifadə olunan məşhur açıq mənbəli çərçivə nədir?", ["MySQL", "Microsoft Access", "Apache Hadoop", "Adobe Spark"], 2),
      createQ("Bir internet şəbəkəsində birdən çox LAN-ı birləşdirən və məlumat paketlərini marşrutlaşdıran qurğu hansıdır?", ["Switch", "Modem", "Router", "Hub"], 2),
      createQ("\"Blokçeyn\" texnologiyasının əsasını təşkil edən xüsusiyyət nədir?", ["Mərkəzləşdirilmiş idarəetmə", "Dəyişdirilə bilməyən paylanmış registr", "Məlumatların sürətli silinməsi", "Yüksək miqdarda enerji tələbatı"], 1),
      createQ("Hər hansı bir məlumatı fiziki (disk, lent) formada deyil, yalnız optik və ya elektrik siqnalları ilə ötürən telekommunikasiya kanalı nədir?", ["Koaksial kabel", "Burulmuş cüt", "Optik lif", "Enerji kabelləri"], 2),
      createQ("\"FinTech\" termini hansı iki sahənin birləşməsindən yaranıb?", ["Qida və Texnologiya", "Kino və Texnologiya", "Maliyyə və Texnologiya", "Fitnes və Texnologiya"], 2),
    ],
    hard: [
      createQ("Kvant Kompüterlərinin əsas hesablama vahidi olan və həm 0, həm də 1 ola bilən vahid necə adlanır?", ["Bayt", "Kvant bit (Qubit)", "Tranzistor", "Neyron"], 1),
      createQ("İlk dəfə internet vasitəsilə məlumat paketlərini göndərən və ilkin internetin təməli sayılan şəbəkənin adı nədir?", ["NSFNET", "ARPANET", "Telenet", "Bitnet"], 1),
      createQ("Proqramlaşdırmada \"Polimorfizm\" (Çoxşəkillilik) prinsipi hansı proqramlaşdırma paradiqmasına aiddir?", ["Struktur proqramlaşdırma", "Obyekt-yönümlü proqramlaşdırma (OOP)", "Məntiqi proqramlaşdırma", "Funksional proqramlaşdırma"], 1),
      createQ("Bir prosesin və ya sistemin real dünyada necə işlədiyini göstərmək üçün proqram təminatının yaradılması nə adlanır?", ["Virtualizasiya", "Emulyasiya", "Simulyasiya", "Abstraksiya"], 2),
      createQ("TCP/IP modelində məlumatların paketlərə ayrıldığı və IP ünvanlarının əlavə olunduğu təbəqə hansıdır?", ["Tətbiqi təbəqə", "Nəqliyyat təbəqəsi", "İnternet təbəqəsi", "Şəbəkə çıxışı təbəqəsi"], 2),
      createQ("Verilən şəbəkədəki bütün kompüterlərin özlərinin fərdi olaraq məlumatları emal etdiyi, mərkəzi serverin olmadığı şəbəkə arxitekturası necə adlanır?", ["Mərkəzi server arxitekturası", "Peer-to-Peer (Bərabərhüquqlu) şəbəkə", "Client-Server arxitekturası", "Bulud arxitekturası"], 1),
      createQ("Kompüter prosessorunda icra olunan əməliyyatların məntiqi ardıcıllığını və nizamlanmasını təmin edən qurğu hansıdır?", ["Aritmetik-Məntiq Qurğusu (ALU)", "Registr", "İdarəetmə Qurğusu (Control Unit)", "Keş yaddaşı"], 2),
      createQ("Veb 3.0-ın əsas hədəfi olan və maşınların verilənləri daha yaxşı anlamasına imkan verən texnologiya nədir?", ["Hiper-mətn", "Semantik Veb", "CSS", "HTML"], 1),
      createQ("Proqramlaşdırmada bir funksiyanın özünü çağırması nəticəsində yaradılan proses necə adlanır?", ["İterasiya", "Rekursiya", "Asinxron funksiya", "Sinxron funksiya"], 1),
      createQ("Enerji istehlakını azaltmaq və əməliyyat sürətini artırmaq üçün çip üzərindəki tranzistorların sayını iki ildən bir iki dəfə artırmağı proqnozlaşdıran qanun hansıdır?", ["Dalton qanunu", "Moore qanunu", "Nyuton qanunu", "Fiqma qanunu"], 1),
      createQ("\"Internet of Things\" (IoT) arxitekturasının ən aşağı təbəqəsi və fiziki mühitlə birbaşa əlaqə quran hissəsi hansıdır?", ["Server təbəqəsi", "Tətbiq təbəqəsi", "Sensor təbəqəsi", "Şəbəkə təbəqəsi"], 2),
      createQ("Proqram təminatının əməliyyat sistemindən asılı olmadan, müxtəlif platformalarda işləməsinə imkan verən vasitə nə adlanır?", ["Sürücü (Driver)", "Virtual maşın", "BIOS", "Firewall"], 1),
      createQ("E-ticarətdə məlumatların təhlükəsizliyini təmin etmək üçün brauzerlə server arasında şifrələnmiş əlaqə yaratmaq üçün istifadə olunan protokol hansıdır?", ["HTTP", "SMTP", "HTTPS (SSL/TLS)", "POP3"], 2),
      createQ("3D printerlərdə istifadə olunan və materialı lay-lay əlavə edərək obyekti yaradan istehsal üsulu necə adlanır?", ["Substraktiv istehsal", "Additiv istehsal", "Dövri istehsal", "Mexaniki istehsal"], 1),
      createQ("Kompüter elmlərində \"Halting Problem\" (Dayanma Problemi) nəyi sübut edir?", ["Bütün proqramların dayana biləcəyini", "Bəzi proqramların sonsuz dövrə düşə biləcəyini", "Alqoritmin bitib-bitməyəcəyini əvvəlcədən təyin etməyin mümkün olmadığını", "Kompüterlərin qeyri-müəyyənliklə işləyə biləcəyini"], 2),
      createQ("Sürətli internet çıxışı təmin edən və səs, video və məlumatları eyni xətt üzərindən rəqəmsal şəkildə ötürən texnologiya nə adlanır?", ["GSM", "LTE", "Broadband (Genişzolaqlı)", "Dial-up"], 2),
      createQ("Kibertəhlükəsizlikdə \"Phishing\" (Fişinq) hücumu nəyi nəzərdə tutur?", ["Şəbəkəyə fiziki giriş", "İstifadəçini aldadaraq şəxsi məlumatlarını (parol, kart nömrəsi) ələ keçirmək", "DDoS hücumları", "Məlumatların kodlaşdırılması"], 1),
      createQ("Robot texnikasında, bir robotun ətraf mühitdə hərəkət etmək üçün xəritə yaratması və öz mövqeyini müəyyənləşdirməsi prosesi nə adlanır?", ["Simulyasiya", "SLAM (Simultaneous Localization and Mapping)", "Təsadüfi yerləşmə", "Sensor analizi"], 1),
      createQ("\"Açıq mənbəli proqram təminatı\"nın (Open Source) əsas prinsipi nədir?", ["Yalnız pullu proqramlar yaratmaq", "Mənbə kodunun hər kəs üçün əlçatan və dəyişdirilə bilən olması", "Hökumətə məxsus olması", "İstifadəçilərin yalnız oxuya bilməsi"], 1),
      createQ("Verilənlər Bazasında məlumatların dörd əsas əməliyyatını (Yaratmaq, Oxumaq, Yeniləmək, Silmək) ifadə edən akronim hansıdır?", ["HTML", "SQL", "CRUD (Create, Read, Update, Delete)", "JSON"], 2),
    ]
  },
  IDMAN: {
    easy: [
      createQ("Futbolda bir komandada meydanda neçə oyunçu olur?", ["9", "10", "11", "12"], 2),
      createQ("Qədim Olimpiya Oyunları hansı ölkədə yaranmışdır?", ["Roma", "Yunanıstan", "Misir", "Çin"], 1),
      createQ("Basketbol idman növü hansı ölkədə yaranmışdır?", ["Kanada", "ABŞ", "Fransa", "Böyük Britaniya"], 1),
      createQ("Cüdo idman növünün vətəni hansı ölkədir?", ["Çin", "Koreya", "Yaponiya", "Tailand"], 2),
      createQ("Futbolda sarı kart nəyi ifadə edir?", ["Qol vurulması", "Qayda pozuntusu və xəbərdarlıq", "Oyunçunun meydanı tərk etməsi", "Hakim dəyişikliyi"], 1),
      createQ("Paralimpiya Oyunlarında kimlər iştirak edir?", ["Peşəkar idmançılar", "Gənc idmançılar", "Əlilliyi olan idmançılar", "Yalnız qadın idmançılar"], 2),
      createQ("Tennisdə ən böyük dörd turnir (Grand Slam) hansılardır?", ["Madrid, Roma, Paris, London", "Uimbldon, ABŞ Açıq, Avstraliya Açıq, Fransa Açıq", "Münhen, Berlin, Vyana, Sürix", "Pekin, Tokio, Seul, Şanxay"], 1),
      createQ("Formula 1 yarışlarında pilotlar nə sürürlər?", ["Motosikl", "Yük maşını", "Tək oturacaqlı açıq təkərli avtomobil", "Velosiped"], 2),
      createQ("Üzgüçülük idman növündə məsafəni ən sürətli qət etməyə imkan verən üsul hansıdır?", ["Arxa üstə", "Brass", "Krol (Sərbəst)", "Batterflay"], 2),
      createQ("Boks idman növündə ən ağır çəki kateqoriyası necə adlanır?", ["Yüngül çəki", "Ağır çəki", "Orta çəki", "Yarım ağır çəki"], 1),
      createQ("Buz üstündə fiqurların cüt şəkildə ifa edildiyi idman növü hansıdır?", ["Xokkey", "Konki sürmə", "Fiqurlu konkisürmə", "Kerlinq"], 2),
      createQ("Yay Olimpiya Oyunları neçə ildən bir keçirilir?", ["Hər il", "2 ildən bir", "4 ildən bir", "5 ildən bir"], 2),
      createQ("İdman yarışlarında ədalətli oyunu təmin edən şəxs kimdir?", ["Məşqçi", "Həkim", "Hakim", "Menecer"], 2),
      createQ("Voleybolda topu rəqib sahəyə zərbə ilə endirmə hərəkəti necə adlanır?", ["Qəbul", "Pas", "Smeç", "Blok"], 2),
      createQ("Hansı idman növündə \"Home Run\" termini istifadə olunur?", ["Futbol", "Basketbol", "Beysbol", "Qolf"], 2),
      createQ("Qol topu (Həndbol) bir komandada meydanda neçə oyunçu ilə oynanılır?", ["5", "6", "7", "8"], 2),
      createQ("Velosiped yarışlarının ən məşhuru olan \"Tour de France\" hansı ölkədə keçirilir?", ["İtaliya", "İspaniya", "Fransa", "Belçika"], 2),
      createQ("Şahmat idman növündə ən güclü fiqur hansıdır?", ["At", "Fil", "Vəzir", "Şah"], 2),
      createQ("\"Olimpiya Atəşi\" simvolu nəyi təmsil edir?", ["Sülh və harmoniyanı", "Birlik və davamlılığı", "İrəliləyiş və tərəqqini", "Rəqabəti"], 1),
      createQ("Hansı idman növü \"Kral oyunu\" adlanır?", ["Boks", "Şahmat", "Qolf", "Atçılıq"], 1),
    ],
    medium: [
      createQ("Snuker idman növündə stol üzərində neçə qırmızı şar olur?", ["10", "15", "20", "22"], 1),
      createQ("Paralimpiya Oyunları nə zaman və kimin təşəbbüsü ilə yaradılmışdır?", ["1936, Adolf Hitler", "1948, Lüdviq Quttman", "1960, Con F. Kennedi", "1980, Xuan Antonio Samarank"], 1),
      createQ("Formula 1 yarışlarında ən çox dünya çempionluğu qazanmış sürücü kimdir (7 çempionluq)?", ["Ayrton Senna", "Mişel Şumaxer", "Lyuis Hemilton", "Alain Prost"], 2),
      createQ("Futbolda \"Offside\" (Oyundankənar vəziyyət) qaydası ilk dəfə neçənci ildə tətbiq olunmuşdur?", ["1863", "1900", "1925", "1950"], 0),
      createQ("Amerikan futbolunda əsas qol (Touchdown) neçə xal gətirir?", ["3", "6", "7", "1"], 1),
      createQ("Voleybolda topa eyni oyunçu ardıcıl olaraq neçə dəfə toxuna bilər?", ["1", "2", "3", "Sonsuz"], 0),
      createQ("Ən məşhur beynəlxalq reqbi yarışı necə adlanır?", ["Dünya Seriyası", "Reqbi Dünya Kuboku", "Reqbi Çempionatlar Liqası", "Altı Millət"], 1),
      createQ("Olimpiya Oyunlarının devizi olan \"Citius, Altius, Fortius\" ifadəsinin mənası nədir?", ["Sürət, Hörmət, Birlik", "Daha sürətli, Daha hündür, Daha güclü", "Cəsarət, Şərəf, Güc", "Sülh, Dostluq, Yarış"], 1),
      createQ("Qolf idman növündə ən böyük (ağır) çəngəl dəyənək (klab) nə adlanır?", ["Qum", "Ütü", "Puter", "Vud (Wood)"], 3),
      createQ("Boksda rəqibin başını qorumaq üçün istifadə olunan qoruyucu vasitə nə adlanır?", ["Şlem", "Kask", "Bandaj", "Kap"], 3),
      createQ("Atçılıqda atın bir maneəni aşmaq üçün sürətləndiyi məsafəyə nə deyilir?", ["Təkan", "Maneə", "Cırılma", "Sıçrayış"], 0),
      createQ("Hansı Avropa futbol klubu ən çox UEFA Çempionlar Liqası titulunu qazanmışdır?", ["Barselona", "Liverpul", "Real Madrid", "Milan"], 2),
      createQ("Atletizmdə ən qədim və ən uzun müddət davam edən qaçış növü hansıdır?", ["Sprinter", "Maraton", "Estafet", "Orta məsafə"], 1),
      createQ("Kriketdə Avstraliya və İngiltərə arasında keçirilən məşhur test seriyası necə adlanır?", ["Dünya Seriyası", "The Ashes (Kül)", "Böyük Döyüş", "Böyük Kubok"], 1),
      createQ("Peşəkar basketbol (NBA) tarixində ən çox çempionluq üzüyü qazanan oyunçu kimdir?", ["Maykl Cordan", "Lebron Ceyms", "Bill Rassell", "Kərim Abdul-Cabbar"], 2),
      createQ("Futbolda \"Panenka\" zərbəsi nə deməkdir?", ["Uzaq məsafədən sürətli zərbə", "Cərimə zərbəsinin topu yüngülcə qapıya qaldıraraq vurulması", "Başla vurulan zərbə", "Künc zərbəsinin birbaşa qapıya vurulması"], 1),
      createQ("Gimnastika idman növündə məşhur \"Volta\" hərəkəti hansı alətdə icra olunur?", ["Türnük", "Halqalar", "Kon", "At (Kürə)"], 3),
      createQ("Avstraliya Açıq (Australian Open) Tennis turniri hansı səth üzərində keçirilir?", ["Ot", "Torpaq (Qum)", "Sərt", "Sintetik"], 2),
      createQ("Olimpiya Oyunlarında qızıl medal qazanan ilk qadın (adını bilmədən, ümumi olaraq) neçənci ildə qazanmışdır?", ["1896", "1900", "1908", "1924"], 1),
      createQ("Xokkeydə komandaların eyni sayda oyunçu ilə mübarizə apardığı hissə necə adlanır?", ["Güc oyunu", "Qısa əl", "Bərabər heyət", "Buz vaxtı"], 2),
    ],
    hard: [
      createQ("1904-cü ildə Sent-Luisdə keçirilən Olimpiya Oyunlarında marafon yarışının ən qeyri-adi qalibi (Fred Lorz hadisəsi) necə qalib gəlmişdi?", ["Qısa yol kəsmişdi", "Avtomobillə yolun bir hissəsini keçmişdi", "Əvvəldən diskvalifikasiya edilmişdi", "Başqa idmançının forması ilə qaçmışdı"], 1),
      createQ("Basketbol (NBA) tarixində ən çox sayda asist və top oğurluğu rekorduna sahib olan oyunçu kimdir?", ["Maykl Cordan", "Con Stokon", "Ceyson Kidd", "Kris Pol"], 1),
      createQ("Futbolda (FIFA) qapıdan qapıya vurulan zərbənin qol hesab olunması qaydası neçənci ildə tətbiq olunmuşdur?", ["1863", "1872", "1901", "1903"], 3),
      createQ("Yelkənli qayıq yarışlarında dünyanın ən köhnə beynəlxalq idman mükafatı hansıdır?", ["Dünya Kuboku", "Kələn Kuboku", "Amerika Kuboku", "Qızıl Yelken"], 2),
      createQ("İdman tarixində, yüngül atletika üzrə 400 metr məsafəyə qaçışda ən çox dünya rekordunu qırmış xanım idmançı kimdir?", ["Marit Canssen", "Meri Qeyz", "Marita Kox", "Ceki Cerner"], 2),
      createQ("Xokkeydə (NHL) qolun \"qayda pozuntusu\" səbəbindən sayılmaması prosesi necə adlanır?", ["Icing", "Ofsayd", "Disallow", "Xəta"], 2),
      createQ("Tennisdə ən sürətli servis (və ya topun sürəti) rekordunun sahibi olan kişi oyunçu kimdir?", ["Roce Federer", "Endi Roddik", "Con İzner", "Milos Raoniç"], 2),
      createQ("Futbolda istifadə olunan, oyunçunun məlumatlarını (ürək döyüntüsü, qaçış məsafəsi) ölçən texnologiya necə adlanır?", ["VAR", "GPS/EPTS (Electronic Performance and Tracking System)", "Qol xətti texnologiyası", "Ofsayd texnologiyası"], 1),
      createQ("Cüdo idman növündə rəqibin tamamilə məğlubiyyəti (yəni 10 tam xal) hansı terminlə ifadə olunur?", ["Vaza-ari", "Yuko", "İppon", "Koka"], 2),
      createQ("Fiqurlu konkisürmədə bir hərəkətin (Təkanın) tam dövrünün havada icra edilməsi nəticəsində əldə edilən xal növləri necə adlanır?", ["Təkan xalı", "Texniki element xalı", "Komponent xalı", "Xarakteristika xalı"], 1),
      createQ("Avtomobil yarışlarında (Le Mans 24h, F1) yanacağın miqdarını və yanma səmərəliliyini azaltmaq üçün istifadə olunan hərəkət enerjisi bərpası sistemi nə adlanır?", ["KERS (Kinetik Enerji Bərpası Sistemi)", "Turbo şarj", "Təkan sistemi", "Hidravlik sistem"], 0),
      createQ("Hansı idman növü üçün \"Hərəkət edən şahmat\" ifadəsi işlədilir?", ["Boks", "Reqbi", "Basketbol", "Su polosu"], 3),
      createQ("1968-ci il Mexiko Olimpiya Oyunlarında \"Qara Güc\" salamı ilə məşhurlaşan amerikalı sprinterlər kimlər idi?", ["Karl Lyuis və Cessi Ovens", "Con Karlos və Tommi Smit", "Ceffri Houm və Tim Montqomeri", "Maykl Conson və Moris Qrin"], 1),
      createQ("Qolfda bir dəlikdə par-dan iki zərbə daha az nəticə göstərmək necə adlanır?", ["Birdie", "Eagle", "Albatros", "Boqey"], 2),
      createQ("Beysbolda \"Siklus vurmaq\" (Hitting for the Cycle) nə deməkdir?", ["Dörd qol vurmaq", "Eyni oyunda single, double, triple və home run vurmaq", "Dörddən çox zərbə vurmaq", "Bütün bazaları qaçmaq"], 1),
      createQ("Futbolda qapıçıların biləklərinə qoyulan, topu atmaq üçün istifadə olunan \"gözəl qəbz\" (Grip) texnikası necə adlanır?", ["Drop-kick", "Torba tutuşu", "Dəmir tutuş", "Kəpənək"], 1),
      createQ("Qədim Olimpiya Oyunlarında qadınlar üçün ayrıca təşkil olunan yarışlar necə adlanırdı?", ["Qineya", "Hera Oyunları (Heraea)", "Femina", "Olimpiya Xanımları"], 1),
      createQ("Avropa futbol çempionatlarında \"Avro\" (Euro) turniri ilk dəfə hansı ildə keçirilmişdir?", ["1956", "1960", "1972", "1980"], 1),
      createQ("Xokkeydə qapıçıların diz üstü sürüşərək qapını bağladığı geniş yayılmış qapıçı texnikası necə adlanır?", ["Keçib getmək", "Kəpənək tərzi", "Bloker", "Qapıçı duruşu"], 1),
      createQ("Atletizmdə 4x100m estafet yarışında qaçışçının hərəkət etməsinə icazə verilən dəyişmə zonası nə qədərdir?", ["5 metr", "10 metr", "20 metr", "30 metr"], 2),
    ]
  }
};

// Returns questions filtered by language
export const getQuestionsByTopic = (topicId: string, seenQuestions: string[], lang: 'az' | 'en' = 'az'): Question[] => {
  const topicData = DB[topicId];
  if (!topicData) return [];
  
  // Attach difficulty to each question for easier filtering later
  const easy = topicData.easy.map(q => ({...q, difficulty: 'easy'}));
  const medium = topicData.medium.map(q => ({...q, difficulty: 'medium'}));
  const hard = topicData.hard.map(q => ({...q, difficulty: 'hard'}));

  const allLevels = [...easy, ...medium, ...hard];

  // 1. Filter by language (Default to 'az' if undefined in DB object)
  // 2. Filter out seen questions (optional, can be disabled if we want infinite play with repetition)
  return allLevels.filter(q => {
     const qLang = q.language || 'az'; 
     return qLang === lang && !seenQuestions.includes(q.text);
  });
};
